### PR TITLE
[scripts][magic-training] Isolating class variables into the actual class

### PR DESCRIPTION
**Pull request by MahtraDR**
This is required for Ruby3, as it's a lot more fussy about class variables outside of a class... No change in functionality, and it works as is like this.

### CODE REVIEW

**Comment by MahtraDR** [comment]
@rpherbig Is this a sane/reasonable way to access class variables from outside the class?

**Comment by Raykyn55** [comment]
What's the difference between:
```ruby
  def self.time_in
    @@time_in
  end
  ```
and
```ruby
  def self.time_in
    Time.now
  end
```
if we're just using the method from outside the class?

**Comment by MahtraDR** [comment]
> What's the difference between:
> 
> ```ruby
>   def self.time_in
>     @@time_in
>   end
> ```
> 
> and
> 
> ```ruby
>   def self.time_in
>     Time.now
>   end
> ```
> 
> if we're just using the method from outside the class?

The first instance sets Time.now to the time the variable was initialized, and any time the def is called, it returns that fixed time.

The second instance return `Time.now` at the time the def is called each time.

**Comment by Raykyn55** [comment]
> > What's the difference between:
> > ```ruby
> >   def self.time_in
> >     @@time_in
> >   end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```ruby
> >   def self.time_in
> >     Time.now
> >   end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if we're just using the method from outside the class?
> 
> The first instance sets Time.now to the time the variable was initialized, and any time the def is called, it returns that fixed time.
> 
> The second instance return `Time.now` at the time the def is called each time.

Ah, because the script is still running, so it doesn't run a new version and redefine the variable. In that case, does it need to be a global variable? If you're fetching it from a class, could it be a class variable?

**Comment by Raykyn55** [comment]
something like:
```ruby
  @time_in = Time.now
  @aug_in = DRSkill.getxp('Augmentation')
  @ward_in = DRSkill.getxp('Warding')
  @util_in = DRSkill.getxp('Utility')
  @sorc_in = DRSkill.getxp('Sorcery')

  attr_reader :time_in, :aug_in, :ward_in, :util_in, :sorc_in
  ```

**Comment by MahtraDR** [comment]
> something like:
> 
> ```ruby
>   @time_in = Time.now
>   @aug_in = DRSkill.getxp('Augmentation')
>   @ward_in = DRSkill.getxp('Warding')
>   @util_in = DRSkill.getxp('Utility')
>   @sorc_in = DRSkill.getxp('Sorcery')
> 
>   attr_reader :time_in, :aug_in, :ward_in, :util_in, :sorc_in
> ```

This is an instance variable like this. 

The original, and my version, are both class variables. 

I just changed where they're stored. I wanted to make the smallest change needed, whilst keeping the same functionality.

**Pull request merged**
