### PR TITLE
Add tattoo_tm support to Combat-Trainer

### PR DESCRIPTION
**Pull request by jayRyan24**

### CODE REVIEW

**Comment by rpherbig** [comment]
Remind me to merge this in a few days

**Comment by jayRyan24** [comment]
> Remind me to merge this in a few days

Will do.

**Comment by jayRyan24** [comment]
It's been 2 days, is this ready for merging?

**Comment by rpherbig** [comment]
Give it one more

**Comment by jayRyan24** [comment]
@rpherbig Ready for merge today sometime.

**Pull request merged**
