### PR TITLE
[script] [feed-cloak] Increase timeout to wait for feeding to finish

### PR DESCRIPTION
**Pull request by KatoakDR**
Depends on #4545

_Note, the commit check build will fail until the dependent PR is merged to introduce the method this PR requires._

### CODE REVIEW

**Comment by rpherbig** [comment]
Could you prefix `wput` with `DRC.`?

**Comment by rpherbig** [comment]
Looks good otherwise ✔️ 

Remind me in a few days to merge this

**Comment by KatoakDR** [comment]
> Could you prefix `wput` with `DRC.`?

Yep, done, thanks!

**Comment by KatoakDR** [comment]
@rpherbig friendly reminder to merge this pull request, thanks!

**Pull request merged**
