### PR TITLE
Unify crafting waggle sets to remove duplication

### PR DESCRIPTION
**Pull request by Sarvatt**
I don't see any reason to have to have separate waggle sets for each craft, if you want to buff one you'd want to buff them all?

### CODE REVIEW

**Comment by jandersson** [comment]
Its for a more granular approach to buffing. Everyone likes to train in their own way. I would add in a general 'crafting' buff set in addition to the existing ones.

**Comment by Sarvatt** [comment]
make it call buff twice then?

**Comment by jandersson** [comment]
Yea

**Comment by jandersson** [comment]
With the exception of PHK, crafting buff spells target a single crafting skill

**Comment by Sarvatt** [comment]
oh that makes more sense, this should just be closed then

**Pull request closed without merging**
