### PR TITLE
crossing-training.lic: Switch over to using athletics.lic for learning.

### PR DESCRIPTION
**Pull request by Sarvatt**

### CODE REVIEW

**Comment by rpherbig** [comment]
❓ How has this been tested?

**Comment by Sarvatt** [comment]
No it hasn't, please don't pull it yet, sorry I was just getting it out early.

**Comment by Sarvatt** [comment]
in case someone spotted an obvious mistake

**Comment by rpherbig** [comment]
A bunch of my guys have had issues with `athletics.lic` - let me check on that tonight before merging this.

**Comment by Sarvatt** [comment]
thanks for checking that, hopefully it was just the dirty zills during climb practice thing that was already fixed

**Pull request merged**
