### PR TITLE
bescort.lic: Hide when taking transportation.

### PR DESCRIPTION
**Pull request by Sarvatt**
Thieves need to point you out to steal, at least this will stop anonymous theft.

### CODE REVIEW

**Comment by rpherbig** [comment]
What do you think about making a helper to do this? That will help us remember the next time something gets added to `bescort`.

**Comment by Sarvatt** [comment]
Do you think that's necessary? Every new entry is a cut and paste of a previous one from what it looks like, they would pick up the hide :)

**Comment by jandersson** [comment]
It would be nice to have a generic ride method, if it doesn't make it too rigid

**Comment by Sarvatt** [comment]
I'll just close this then, not up for that

**Comment by jandersson** [comment]
Well i meant in general. I think making a generic ride method is another PR

**Comment by rpherbig** [comment]
I'm not opposed to merging this if it helps people out.

**Comment by Sarvatt** [comment]
I was running this for a while and now that I stopped I got stolen from waiting for a ferry and couldn't join it so things just hung up, would still like this to get pulled if possible.

**Comment by jandersson** [comment]
This would be nice for caravan trading as well

**Pull request merged**
