### PR TITLE
[multiple scripts] Renamed Scouting to Instinct

### PR DESCRIPTION
**Pull request by MahtraDR**
As per title. Just a simple rename/search and replace. No functionality changed.

### CODE REVIEW

**Comment by Kiriawen** [comment]
Merge it

**Comment by asechrest** [comment]
Wondering about renaming `scouting.lic`. I guess we shouldn't incase folks have it named as such in their yamls?

**Comment by MahtraDR** [comment]
> Wondering about renaming `scouting.lic`. I guess we shouldn't incase folks have it named as such in their yamls?

There is a way to rename the script and create a backwards compatible alias for scouting to point to instinct. If we can additionally add a deprecation notice, that would make it clean. Or add a note now to scouting.lic that it'll be renamed on X date and we just rename it then.

**Comment by asechrest** [comment]
Now that I typed that, I bet the command to use a trail is still `scout trail`, so there is an argument that the script is designed to scout a trail and `scouting.lic` isn't a misnomer.

**Pull request merged**
