### PR TITLE
[script][common] - Log to window

### PR DESCRIPTION
**Pull request by asechrest**
Logs a message to specified window. Come to find out window names are case sensitive, so specifically not forcing case here.

### CODE REVIEW

**Comment by MahtraDR** [comment]
Opinions on deprecating the window specific atmo method, and just changing it to use this method instead?

**Comment by asechrest** [comment]
> Opinions on deprecating the window specific atmo method, and just changing it to use this method instead?

If [this search](https://github.com/rpherbig/dr-scripts/search?q=atmo) is correct and we've only got one script using the `DRC.atmo`, agreed.

**Comment by asechrest** [comment]
Some final changes, and now ready. Options to create the window if it doesn't exist (tested on Wrayth and Genie), as well as pre-clear the window before logging if the user desires.

Also updated the only script that uses `atmo()`, as well as changing the atmo def to simply call `log_window`.

**Comment by asechrest** [comment]
Screenshot 2022-07-04 121111

**Review by MahtraDR — APPROVED** [review]
Looks good to me. Tested on all my windows, I have the tarantula script going too, that also works exactly the same. Neat change!

**Pull request merged**
