### PR TITLE
safe-room.lic: Move on from pc empath for other messages.

### PR DESCRIPTION
**Pull request by Sarvatt**
2 other common ones in use:
XXXXXX whispers, "You're not even injured, ya doofus" (in case someone runs ;safe-room force)
XXXXXX whispers, "All set Sarvatt"

### CODE REVIEW

**Comment by Sarvatt** [comment]
I need to test if this works first, please don't pull.

**Comment by Sarvatt** [comment]
Fixed and tested.

**Comment by jandersson** [comment]
Can we just check if the empath whispers to you? Adding each message someone can think of would add up.

**Comment by Sarvatt** [comment]
I was thinking about that but the problem is the heal script that a bunch of people use has this in it if they are too injured to heal `fput('whisper "#{target} I'm a little too injured for that right now.  Give me a moment to heal up and I'll get right to you")` and then it runs healme until your health goes under a certain score before healing.

**Comment by jandersson** [comment]
Good call, I hadn't considered that

**Pull request merged**
