### PR TITLE
Add idling to coordinator.lic

### PR DESCRIPTION
**Pull request by jandersson**
This will let the coordinator script idle in a saferoom until a new task becomes available/ready. This is useful for rested exp training where you would like to idle while your target skills drain.

### CODE REVIEW

**Comment by jandersson** [comment]
Ill make this as ready once i rebase on master and get the afk changes merged.

**Comment by rpherbig** [comment]
Looks good so far

**Comment by Sarvatt** [comment]
submitted a PR to jandersson's branch here to merge with master and fix up afk.lic, it should be good to go after that.

**Comment by jandersson** [comment]
I still need to rebase on master, is that some thing that will take care of the pull request?

**Comment by jandersson** [comment]
@rpherbig Rebased and moved out of draft stage, im all set

**Pull request merged**
