### PR TITLE
[script] [events] Store raw match data so can use named groups

### PR DESCRIPTION
**Pull request by KatoakDR**
### Background
* Suggested by @rcuhljr (https://github.com/rpherbig/dr-scripts/pull/4890#discussion_r612112575) to facilitate using named capturing groups in regular expressions used with `Flags` class.
* I'm planning to use named capturing groups with a revised regex for identifying ammo shot in `combat-trainer`

### Changes
* Store the raw regex match data in the flag rather than an array of the captured groups

### regex without names can reference groups by number (regression test)
GIVEN:
```
Your birthday is more than 4 months away.
```
THEN:
```ruby
    Flags.add('birthday', /Your birthday is more than (\d+) (\w+) away/)
    fput('info')
    echo Flags['birthday'][1] # 4
    echo Flags['birthday'][2] # months
```

### regex with names can reference groups by name (new functionality)
GIVEN:
```
Your birthday is more than 4 months away.
```
THEN:
```ruby
    Flags.add('birthday', /Your birthday is more than (?<qty>\d+) (?<unit>\w+) away/)
    fput('info')
    echo Flags['birthday'][:qty] # 4
    echo Flags['birthday'][:unit] # months
```

### CODE REVIEW

**Comment by wstampley** [comment]
Are they still indexable with the same index key as matchers, or is this going to force any flag based regexs to update to the new syntax?

**Comment by rcuhljr** [comment]
The change will allow both versions to work, it should be a non breaking change in all situations unless some complete madman was type checking the flag return values for arrays as some kind of boolean check. In which case they should feel bad and deserve to have it break. (alternatively someone might loop over all the flag matches but that's a one line fix)

**Comment by KatoakDR** [comment]
> Are they still indexable with the same index key as matchers, or is this going to force any flag based regexs to update to the new syntax?

Reiterating **rcuhljr** said, "The change will allow both versions to work, it should be a non breaking change".

The only gotcha I'm aware of is that if a regex mixes named groups with unnamed groups then you should **only** extract matches out of the result by the named groups. This is because when a named group exists then there's no guarantee to the index/order of the unnamed groups. I noticed this in testing and read about it [here](https://www.regular-expressions.info/named.html) -- "Mixing named and numbered capturing groups is not recommended because flavors are inconsistent in how the groups are numbered. If a group doesn't need to have a name, make it non-capturing..."

For example:

**GOOD: unnamed groups and access results by index**
```
    Flags.add('birthday', /Your birthday is more than (\d+) (\w+) away/)
    fput('info')
    echo Flags['birthday'][1] # 4
    echo Flags['birthday'][2] # months
```

**GOOD: named groups and access results by name**
```
    Flags.add('birthday', /Your birthday is more than (?<qty>\d+) (?<unit>\w+) away/)
    fput('info')
    echo Flags['birthday'][:qty] # 4
    echo Flags['birthday'][:unit] # months
```

**GOOD: mix of named and unnamed groups and access only by name**
```
    Flags.add('birthday', /Your birthday is more than (\d+) (?<unit>\w+) away/)
    fput('info')
    echo Flags['birthday'][:unit] # months
```

**BAD: mix of named and unnamed groups and access only by index**
```
    Flags.add('birthday', /Your birthday is more than (\d+) (?<unit>\w+) away/)
    fput('info')
    echo Flags['birthday'][1] # this MAY or MAY NOT be what you think it should be, no guarantee
```

**Comment by Hiinky** [comment]
This is currently breaking random scripts, most notably killing moonies trying to walk the ways with ;bescort.  Should we revert it while the issues get sorted out?

**Comment by rcuhljr** [comment]
`     harness_mana([20]) unless Flags['harness-check'].include?('effortlessly')` is the line to fix bescort, someone meant to write [0] but used includes incorrectly.

**Pull request merged**
