### PR TITLE
Better ferry logic

### PR DESCRIPTION
**Pull request by ServerFailure**

### CODE REVIEW

**Comment by ServerFailure** [comment]
This is for the haven_throne ferry only.

The previous/current logic will NOT attempt to get on the ferry if it's already in the room, which will cause you to wait an extra 5-10 minutes.  This updated logic will attempt to get on the ferry first, and if it fails, then it waits for a ferry to arrive.

**Comment by rpherbig** [comment]
@Sarvatt do you have time to look this over and/or test it?

**Comment by ServerFailure** [comment]
```
[Salt Yard, Barge Dock]
The end of the dock is reinforced with heavy timbers and rusting iron plates, no doubt to compensate for the extreme weight of the high piles of salt sacks.  Strategically hidden between the stacks are crates and leather satchels, their shipping labels designating their contents as decidely non-salty in origin.  None of the items appear to be black-market goods, so why such lengths were taken to disguise their transport is not clear.
Obvious paths: north.
Room Number: 452
>
--- Lich: bescort active.
--- Lich: equipmanager active.
--- Lich: equipmanager has exited.
--- Lich: skill-recorder active.
>
[bescort]>wealth lirums
  6 silver, 4 bronze, and 8 copper Lirums (648 copper Lirums).
>
[bescort]>hide
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 6 sec.
>
[bescort: Waiting for a barge to show up... ]
>
You are still rather wet, but drying off nicely.
>
The cushioning currents of wind about you rapidly disperse.
>
You can see a barge nearing the dock.
>
A barge pulls into the dock.
>
[bescort]>wealth lirums
  6 silver, 4 bronze, and 8 copper Lirums (648 copper Lirums).
>
[bescort]>go glory
You come out of hiding.
 
One of the barge's crew members stops you and requests a transportation fee of 120 Lirums as you board the craft.  You hand him your Lirums and climb aboard.
 
<streamWindow id='main' title='Story' subtitle=" - ["Imperial Glory"]" location='center' target='drop'/>
--- error: server_thread: malformed XML: missing tag start
Line: 1
Position: 106
Last 80 unconsumed characters:
<streamWindow id='main' title='Story' subtitle=" - ["Imperial Glory"]" location='
<streamWindow id='room' title='Room' subtitle=" - ["Imperial Glory"]" location='center' target='drop' ifClosed='' resident='true'/>
--- error: server_thread: malformed XML: missing tag start
Line: 1
Position: 133
Last 80 unconsumed characters:
<streamWindow id='room' title='Room' subtitle=" - ["Imperial Glory"]" location='c
["Imperial Glory"]
A row of water-stained benches occupies the deck of the Imperial Glory, where wealthy passengers can sit at ease and view the beautiful landscape, rolling forests and a few sandy beaches, of southern Therengia.  Ropes used to tie off the barge when in harbor neatly hang from metal hooks.  A tall railing along the side of the barge helps prevent the careless traveler from falling overboard into the murky waters, and a door leads within a cabin.  You also see the salt yard dock.
Obvious paths: none.
[bescort]>hide
Room Number: 14419
>
You melt into the background, convinced that your attempt to hide went unobserved.
Roundtime: 6 sec.

...

Your destination finally comes into view.
>
The barge pulls into dock and its crew quickly ties the barge off.
>
[bescort]>go dock
You come out of hiding.
[Stone Docks, Covered Shore]
Barely extending from the shore, the dock is little more than a short series of solid blocks of weather-battered stone.  Thick sheets of canvas are lashed in a tent-like fashion around this port, keeping the onslaught of the skies and winds at bay while also serving to mask its presence from passing ships.  With the excessive vegetation that creates yet another disguising layer outside the canvas, it's clear that many boats could pass along the Faldesu without ever knowing this place exists.  You also see the barge Imperial Glory and a brushy break in the undergrowth.
Obvious exits: south.
Nearby in the water you see: nothing special.
Room Number: 3084
>
--- Lich: bescort has exited.
```

I turned on DEV mode while this is pending update.  But I've been using it to hunt crocs without any issues since my updates.

**Comment by Sarvatt** [comment]
Looks good to me 👍

**Pull request merged**
