### PR TITLE
[script] [truffenyi-commune-quest] make truffenyi script more feature rich

### PR DESCRIPTION
**Pull request by vtcifer**
Handle solving the altar puzzle
Slightly better vial handling 
Handle the shrine/ox puzzle

Still will not find shrine for you

### CODE REVIEW

**Comment by vtcifer** [comment]
GTG even with rubocop warnings (most are indent issue which are present for better code collapse)

**Comment by vtcifer** [comment]
GTG even with rubocop warnings (most are indent issue which are present for better code collapse)

**Comment by MahtraDR** [comment]
Can uuu ou please do the rubocop autocorrects or propose a change to the rubocop rules? I accept the indentation folding idea, but rubocop keeps me sane too.

**Comment by vtcifer** [comment]
IMO rubocop makes a good sniff test for happy flows - it catches a lot of 'oops' in those.  But for unhappy flows it should be 'someone 4-eyes this', not as the final arbiter. If the committer can articulate a good justification for the ignoring it should be OK.

Just my .02

**Comment by vtcifer** [comment]
Given how messy this PR is with the commits, just ping me on discord if you're OK with how I've handled rubocop and I'll do another branch with a cleaner commit history for merging.

**Comment by MahtraDR** [comment]
This works for me. Thanks!

**Pull request merged**
