### PR TITLE
[script][base-recipes][update]Added some recipes that were removed during one of the updates during the long review.

### PR DESCRIPTION
**Pull request by Dartellum**
@BinuDR assisted with the data.

### CODE REVIEW

**Comment by Dartellum** [comment]
Binu and I are working on a standardized format for the recipes. Binu wrote a script that pulls the information from the books and formats into a yaml file. Standardizing will come in a different PR. However, that is how the missing recipes were found.

**Comment by Dartellum** [comment]
Since we changed to the cheapest sigil, the `enchant` script required an update to reflect that as well. I forgot the `any` sigil was hard-coded in. I am thinking about changing that to "detect" the sigil instead of having a hard-coded value in the script.

**Comment by rpherbig** [comment]
Is this ready to merge?

**Comment by BinuDR** [comment]
> 
> 
> Is this ready to merge?

Yes, it's ready to go.

**Comment by Dartellum** [comment]
> > Is this ready to merge?
> 
> Yes, it's ready to go.

Yes, the recipes are good to go but may need to change a few more to false. The ones with part: - burin. Checking.

**Comment by Dartellum** [comment]
> > > Is this ready to merge?
> > 
> > 
> > Yes, it's ready to go.
> 
> Yes, the recipes are good to go but may need to change a few more to false. The ones with part: - burin. Checking.

Okay, all set now.

**Pull request merged**
