### PR TITLE
[script][combat-trainer][AttackProcess class] Removed includes, added prefixes, fixed an fput

### PR DESCRIPTION
**Pull request by Raykyn55**

### CODE REVIEW

**Comment by Chewmatca** [comment]
Hi Had been testing this for last few days no errors but just went through logs and found an unload?

`[combat-trainer]>aim

You begin to target a juvenile wyvern.
> 
[combat-trainer]>harness 20

You tap into the mana from twenty of the surrounding streams and attempt to keep it channeling in a stream around you.
Roundtime: 3 sec.
R> 
Hunter Azothy just arrived.

Hunter Azothy runs east.

[combat-trainer]>harness 25

You tap into the mana from twenty-five of the surrounding streams and add it to the generous amount already streaming around you.
Roundtime: 3 sec.
R> 
* With pathetic timing, a juvenile wyvern lunges forward and snaps its fangs at you.  You block with a small morgawr leather shield embedded with yellowed fangs.  
[You're incredibly balanced and overwhelming your opponent.]
Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
* As if fumbling muscle flab were natural, a juvenile wyvern slices wide at you.  You block with a small morgawr leather shield embedded with yellowed fangs.  
[You're incredibly balanced and overwhelming your opponent.]
Learned: Evasion(0), Shield Usage(0), Defending(+1), Light Armor(0), Chain Armor(+1), Brigandine(0), Plate Armor(+1)
[combat-trainer]>unload my bogbirch.shortbow

You stop aiming.
You unload the shortbow.
Roundtime: 1 seconds.
R> 
[combat-trainer]>stow left

You put your arrow in your seordmaor skull.
> 
[combat-trainer]>sheath my bogbirch.shortbow

You sheathe the bogbirch shortbow in your devotional case.`

**Comment by Raykyn55** [comment]
> Hi Had been testing this for last few days no errors but just went through logs and found an unload?
> 
> `[combat-trainer]>aim
> 
> You begin to target a juvenile wyvern.
> 
> > 
> 
> [combat-trainer]>harness 20
> 
> You tap into the mana from twenty of the surrounding streams and attempt to keep it channeling in a stream around you. Roundtime: 3 sec. R> Hunter Azothy just arrived.
> 
> Hunter Azothy runs east.
> 
> [combat-trainer]>harness 25
> 
> You tap into the mana from twenty-five of the surrounding streams and add it to the generous amount already streaming around you. Roundtime: 3 sec. R>
> 
> * With pathetic timing, a juvenile wyvern lunges forward and snaps its fangs at you.  You block with a small morgawr leather shield embedded with yellowed fangs.
>   [You're incredibly balanced and overwhelming your opponent.]
>   Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
> * As if fumbling muscle flab were natural, a juvenile wyvern slices wide at you.  You block with a small morgawr leather shield embedded with yellowed fangs.
>   [You're incredibly balanced and overwhelming your opponent.]
>   Learned: Evasion(0), Shield Usage(0), Defending(+1), Light Armor(0), Chain Armor(+1), Brigandine(0), Plate Armor(+1)
>   [combat-trainer]>unload my bogbirch.shortbow
> 
> You stop aiming. You unload the shortbow. Roundtime: 1 seconds. R> [combat-trainer]>stow left
> 
> You put your arrow in your seordmaor skull.
> 
> > 
> 
> [combat-trainer]>sheath my bogbirch.shortbow
> 
> You sheathe the bogbirch shortbow in your devotional case.`

Were you casting sorcery?

**Comment by Chewmatca** [comment]
Yes thats correct it was casting RW as necro.
Looked further and there were more examples of that same pattern looked like full prep then he unloads his bow.

Also i see it tries to unload if stowing, just after it fires.

[combat-trainer]>shoot

< Driving in with an overwhelming assault, you fire a labyrinthine stone at a juvenile wyvern.  A juvenile wyvern fails to dodge, only partially avoiding the impact.  
The stone lands a very heavy hit that turns the quadricep to mush and crushes the femur in a mighty strike across the left leg.
The labyrinthine stone falls to the ground!
[You're hurt, winded, incredibly balanced and overwhelming opponent.]
[Roundtime 1 sec.]
Learned: Slings(+2), Missile Mastery(+1)
* Awkwardly, a juvenile wyvern slashes its razor-sharp talons at you.  You block with a small morgawr leather shield embedded with yellowed fangs.  
[You're hurt, winded, incredibly balanced and overwhelming your opponent.]
Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
[combat-trainer]>stow my stone

You pick up the stone lying at your feet.
You put your stone in your seordmaor skull.
> 
[combat-trainer]>unload my leather.sling

But your leather sling isn't loaded!
> 
[combat-trainer]>sheath my leather.sling

You sheathe the leather sling in your devotional case.

**Comment by Raykyn55** [comment]
So first, when casting sorcery spells, combat trainer stows your right hand in case you blow your hand off, so you dont drop your weapon. Especially important with ranged weapons because you cant unload them with one hand, and cant wear or stow a loaded bow.

The extra unload is a check thats always done when stowing ranged weapons, same reason.

**Comment by Chewmatca** [comment]
Hand blowing i think is only for the most dangerous, its not that practical i found for combat to be stunned either. So either safe or somewhat safe is what I run in combat.

Can you concider these options:
A: Enable an override for sorcery spells, new datapoint to say its safe (I only run safe stuff for training, OR im in a non combat room if casting something where i can get the stun).
B: Implement a new definition point on spells that will return if the spell is going to cause hand blowing or is safe, which will take into account guild & redeemed or non redeemed necro (there is a matrix for whats safe and not), if safe dont unload to cast?
C: Just fire the ranged weapon instead of unload, that would at least make use of the firing.

I prefer A or B personally.

Objective is more efficiency, to unload after full aim is a bit of a waste.

Are these reasonable? A would be easy, B would be more complete but require maintenance, C an option maybe.

Thankyou & nice work!

**Comment by Raykyn55** [comment]
This type of edit would be done to SpellProcess class, which is outside the scope of this PR. I see how it might be done, though. I'll open an issue.

**Comment by Raykyn55** [comment]
see https://github.com/rpherbig/dr-scripts/issues/5937

**Pull request closed without merging**
