### PR TITLE
[script][pick] (re)fix for autolooters

### PR DESCRIPTION
**Pull request by Raykyn55**
Resubmitting the fix from #5862

### CODE REVIEW

**Comment by Kiriawen** [comment]
why not just add the failure message of 
```
[pick]>get coins from my wooden strongbox
What were you referring to?
```

**Comment by Raykyn55** [comment]
could, but the problem here is we're matching the first line on open as 'You open', then the NEXT one fills our contents with the line 'in the box you see'. if we make the failure message 'what were you referring to', we'll have to do that for every type of coin:
```ruby
loot = box_items.map { |item| DRC.get_noun(item) }
```
potentially:
```
get coin
>What were you
get coin
>What were you
get coin
>What were you
get coin
>What were you
```
Whereas the actual match we're looking for is the contents. The result:
```
[pick]>open my ironwood strongbox
You open the ironwood strongbox... # Here we match the first bput
# Here we match the look for DRCI.get_item_list(box_noun, 'look')
In the ironwood strongbox you see some copper coins, some bronze coins, some silver coins, some gold coins, a medium green-yellow tsavorite, and a huge cinnamon quartz.
You quickly pocket the coins.
s> 
[pick]>look in my ironwood strongbox # notice it ignores this, because it already has it's list
[pick]>get coins from my ironwood strongbox
In the ironwood strongbox you see a medium green-yellow tsavorite and a huge cinnamon quartz.
s> 
What were you referring to?
```

**Comment by Raykyn55** [comment]
What this change does is force it to wait for the second line 'in the box you see' as our opened box match, allowing autolooter to do it's thing, THEN look in the box to get what's left to fill our lootables list.

**Comment by Raykyn55** [comment]
This is an example of POST change:
```
[pick]>open my oaken crate
You open the oaken crate...

In the oaken crate you see some copper coins, some bronze coins, some gold coins, and a medium olive aquamarine.
You quickly pocket the coins.  Anything else of interest was added to the cloth lootpouch.
s>
[pick]>look in my oaken crate
There is nothing in there.
s>
[pick]>put my oaken crate in bucket
You drop a rotting oaken crate in a shiny tin bucket.
```

**Pull request merged**
