### PR TITLE
blight ogre update

### PR DESCRIPTION
**Pull request by minor-fixes-only**
Fixes a room listed under giants that actually spawned stumpy
Added a few rooms of stumpies

### CODE REVIEW

**Comment by Tarhish** [comment]
Huh, I thought this bput thing got fixed.  I don't think this failing is your mistake, but maybe try resubmitting it again?  Sometimes the testing gets hung up and delayed.

**Comment by minor-fixes-only** [comment]
This is just an update to the base-hunting database, nothing to do with bput?

**Comment by minor-fixes-only** [comment]
resubmit for glitch

**Comment by Tarhish** [comment]
Yeah, there we go.

**Pull request merged**
