### PR TITLE
validate update

### PR DESCRIPTION
**Pull request by Rhayle**
I read through the earlier comments and have gone back through this file. Everything I can find referencing an array in the settings is using settings.base['key']. Unfortunately I'm at work and unable to test this at the moment. Can you verify this is correct or incorrect?

### CODE REVIEW

**Comment by rpherbig** [comment]
I tried the function here and got this:
```
2018-01-12 15:53:29 -0500:--- Lich: validate active.
2018-01-12 15:53:29 -0500:  Checking 55 different potential errors
2018-01-12 15:53:30 -0500:--- Lich: error: no implicit conversion of String into Integer
2018-01-12 15:53:30 -0500:	validate:500:in `[]'
2018-01-12 15:53:30 -0500:	validate:500:in `assert_that_moons_is_deprecated'
2018-01-12 15:53:30 -0500:--- Lich: validate has exited.
```

Since the setting is an Array, you really want to use [.include?(...)](https://ruby-doc.org/core-2.2.0/Array.html#method-i-include-3F): `settings.astrology_training.include?('moons')`

**Comment by rpherbig** [comment]
In this PR, would you mind adding a check (either in this validator or in a separate and new one) that `astrology_training` only contains allowed values?

**Comment by Rhayle** [comment]
I'll see what I can do. I have been copying from other pieces and parts to get this to work, so forgive me if I am a bit slow on this. I dont know ruby, but this will be a good exercise. also no clue what a PR is.

**Comment by Rhayle** [comment]
also, apologize for so many commits. im editing everything directly in the github web editor.

**Comment by jandersson** [comment]
PR = Pull Request. This is a PR :)

**Pull request closed without merging**
