### PR TITLE
Add travis-ci config

### PR DESCRIPTION
**Pull request by jandersson**
This is a simple config file that would let us use travis-ci for this repository. With that we can run tests against all pull requests, potentially run rubocop on them. I think this might help mitigate future breakages. I was able to run this successfully on my fork.

### CODE REVIEW

**Comment by rcuhljr** [comment]
We looked into this a few years ago, at the time it didn't work without giving travis-ci unreasonable permissions, but @rpherbig did the investigation.

**Comment by rcuhljr** [comment]
https://github.com/rpherbig/dr-scripts/issues/282

**Comment by jandersson** [comment]
I see - well at the least I can keep running it on my fork to mitigate any mistakes i might make :P

**Comment by rpherbig** [comment]
You have to give travisCI access to _every_ repo you have access to. I.e. if I'm in a group for both my personal repos (`rpherbig/*`) and work repos (`sep/*`), travis gets them all.

**Comment by jandersson** [comment]
Oh right, that is still a thing

**Pull request closed without merging**
