### PR TITLE
Update skill-recorder.lic

### PR DESCRIPTION
**Pull request by aruthas**
skill_checker was updated so I could use the thief_passages.  I was fixing shard and this seemed the easiest way to fix it for all thieves

### CODE REVIEW

**Comment by Sarvatt** [comment]
how about just putting all the passages assignments in the same conditional as crossing_leth instead of checking 4 more variables every 2 seconds?

**Comment by aruthas** [comment]
Only reason I did it that way, is because you dont need athletics to use these other passages

**Comment by Sarvatt** [comment]
well they both could be condensed into one if DRStats.guild == 'Thief' && DRStats.circle > 5 at any rate

**Comment by Sarvatt** [comment]
looks good to me and this is needed to fix a bunch of problems with the map in shard that he already has staged @rpherbig

**Comment by aruthas** [comment]
Did I do something wrong?  It says some of the checks havent been completed

**Pull request merged**
