### PR TITLE
Should fix the thief hasten bug where you pick a trapped box.

### PR DESCRIPTION
**Pull request by jayRyan24**

### CODE REVIEW

**Comment by jayRyan24** [comment]
```[pick]>disarm my iron chest identify
>
Right above the lock inside the keyhole, you see a tiny metal tube just poking out of a small wad of brown clay.
This trap is a laughable matter -- you could do it blindfolded! (2/17)
Roundtime: 1 sec.
>
[pick]>disarm my iron chest careful
You carefully work at disarming the chest.
With ever so much agility, you stick your fingernail into the tip of the clay and gently slide the tiny tube out of it and toss it aside.
Roundtime: 7 sec.
>
[pick]>glance my iron chest
It looks like there are no traps left on the chest.
 
It looks like there is 1 lock left on the chest.
Looking more closely you see...
Although difficult to spot at first, a thin hole along the bottom of the lock appears to be the key receptacle.
>
[pick]>pick my iron chest ident
Somebody has already inspected the current lock on this chest...
 
This lock is a laughable matter -- you could do it blindfolded! (2/17)
>
[pick]>pick my iron chest quick
With a soft click, you remove your lockpick and open and remove the lock.
Roundtime: 1 sec.
```

**Review by KatoakDR — COMMENTED** [review]
Thanks for tackling this, I know it’s been disrupting thieves for a while!

I posted a few comments, nothing major, take ‘em or leave ‘em.  👍

**Comment by rpherbig** [comment]
No further comments

**Comment by jayRyan24** [comment]
```
[newpick]>get my casket from my lotus.bag
You get a pitted steel casket from inside your lotusweave bag.
[newpick]>disarm my casket identify
Right above the lock inside the keyhole, you see a tiny metal tube just poking out of a small wad of brown clay.
This trap is a laughable matter -- you could do it blindfolded! (2/17)
Roundtime: 1 sec.
[newpick]>disarm my casket quick
...wait 1 seconds.
[newpick]>disarm my casket quick
You quickly work at disarming the casket.
With ever so much agility, you stick your fingernail into the tip of the clay and gently slide the tiny tube out of it and toss it aside.
You believe that the casket is not yet fully disarmed.
Roundtime: 1 sec.
[newpick]>disarm my casket identify
Squinting slightly to see better, you notice the casket's keyhole is packed tightly with a powder around the insides of the lock.
This trap is a laughable matter -- you could do it blindfolded! (2/17)
[newpick]>disarm my casket quick
Roundtime: 1 sec.
...wait 1 seconds.
The twisted steel buckle of your thighband pulses with a soft light for a moment, and you feel more focused.
The twisted steel buckle of your thighband pulses with a soft light for a moment, and you feel more focused.
The dwalgim on your crown pulses with a soft light for a moment, and you suddenly feel more focused.
[newpick]>glance my casket
It looks like there is 1 trap left on the casket.
Looking more closely you see...
Although similar to the boomer, the amount of powder packed around the lock means this is the shrapnel trap.
It looks like there is 1 lock left on the casket.
Looking more closely you see...
The lock's structure is relatively basic, standard in every way without any unusual characteristics.
| Hit the Thief Hasten bug, disarming again!
[newpick]>disarm my casket identify
Somebody has already located and identified the current trap on the steel casket...
Squinting slightly to see better, you notice the casket's keyhole is packed tightly with a powder around the insides of the lock.
This trap is a laughable matter -- you could do it blindfolded! (2/17)
[newpick]>disarm my casket quick
You quickly work at disarming the casket.
You pry a small hole in the side of the casket and use a strong sustained breath to blow the powder away from the lock and further to the side.  With a slight shake, it falls to the ground harmlessly.
Roundtime: 1 sec.
[newpick]>glance my casket
It looks like there are no traps left on the casket.
It looks like there is 1 lock left on the casket.
Looking more closely you see...
The lock's structure is relatively basic, standard in every way without any unusual characteristics.
[newpick]>pick my casket ident
Somebody has already inspected the current lock on this casket...
This lock is a laughable matter -- you could do it blindfolded! (2/17)
[newpick]>pick my casket quick
You deftly remove a lockpick from the lockpick ring and begin to work at quickly picking open the casket.
With a soft click, you remove your lockpick and open and remove the lock.
You return your lockpick to the lockpick ring.
Roundtime: 1 sec.
[newpick]>open my casket
You open the steel casket...
In the steel casket you see a huge mint green bloodstone and a large grey zircon.
[newpick]>fill my black pouch with my casket
You open your black gem pouch and quickly fill it with 2 gems from your steel casket, closing it quickly.
[newpick]>look in my casket
There is nothing in there.
[newpick]>dismantle my casket thump
With a smirk of supreme confidence, you rap the steel casket once with a knuckle.  The casket collapses and its pieces fall to the ground in what can only be described as a surreally ordered fashion.  You could almost reassemble the neatly laid out pieces, needing no plans for its construction.  Order being something of an anathema to you, you kick the pieces aside.
Roundtime: 3 seconds.
```

**Comment by jayRyan24** [comment]
Made the changes, they were minor. Should be good to go. Thanks!

**Pull request merged**
