### PR TITLE
forestry-buddy.lic: Updates to get rid of mining references.

### PR DESCRIPTION
**Pull request by Sarvatt**
change script name in the header
switch to using lumber_buddy_chop_every_room instead of mining_buddy_chop_every_room

### CODE REVIEW

**Comment by rcuhljr** [comment]
You may want to grand father in the old yaml setting with a loud warning for awhile.

**Comment by rpherbig** [comment]
Even though the setting was blatantly named wrong? I kind of suspect no one was using this script until now...

**Comment by Sarvatt** [comment]
yeah lumber_buddy_chop_every_room was in base too, i found this from someone saying it wasn't doing anything on lnet

**Comment by rcuhljr** [comment]
If the base.yaml value was named wrong, no need then. I used this script for ~6 months 2-3 times a day. It's just the harvest_every_room settings are basically a terrible choice.

**Pull request merged**
