### PR TITLE
Combat Trainer - Rutilor's Edge Support

### PR DESCRIPTION
**Pull request by drboldwin**
Added support for Rutilor's Edge spell.  Similar to ignite - releases when weapons change - lets buff spells take care of it from there with a custom cast that targets active weapon.

### CODE REVIEW

**Comment by rpherbig** [comment]
Speaking of "commit messages that make good patch notes"... :)

**Comment by drboldwin** [comment]
haha - alright alright

**Comment by drboldwin** [comment]
oh this needs an add into common-spells for it's cast message too - will do that in a moment and bundle into this.

**Comment by rpherbig** [comment]
I'm glad this approach is working, but I think for the next one (maybe Resonance?) we need to find a way to make it more scalable.

**Pull request merged**
