### PR TITLE
Tailoring - chapter 3 workorders

### PR DESCRIPTION
**Pull request by yuoree**
Turned on all chapter 3 workorders for higher level outfitting.

Still a gap between difficulty 08 (small rucksack) and 10 (rucksack). Likely need to pick a difficulty 09 or two from another chapter at some point.

### CODE REVIEW

**Comment by rpherbig** [comment]
@yuoree were (some) of these tested by running `workorders.lic`?

**Comment by jandersson** [comment]
Ive tested the rucksack (by chance i made the same change this morning)

**Comment by yuoree** [comment]
I've tested the ones I can on a couple chars, in shard. I've also done cloth armor stuff on my own version, but after talking to Sarvatt yesterday sticking to chapter 3 for now, since less parts.

**Comment by Sarvatt** [comment]
this looks good to me, it's not turning on lower level chapter 3 things so it's only addiing items for people to craft not changing behavior for people still knitting.

**Comment by Sarvatt** [comment]
chapter 2 has a few difficulty 9 items we could turn on

**Pull request merged**
