### PR TITLE
[script][clean-leather] Better arg name and descriptions

### PR DESCRIPTION
**Pull request by asechrest**
Better arg descriptions to avoid confusion.

### CODE REVIEW

**Review by KatoakDR — APPROVED** [review]
Thanks for renaming the meme term _Salt Bae_ to something I understand in my generation 😆

**Comment by MahtraDR** [comment]
Tested this script today for completeness. Works as advertised, even if I had to re-learn how to hunt manually to get the skins....

**Comment by MahtraDR** [comment]
Oh, forgot to mention, as per convo on Discord. It'd be nice for the script to do a supplies check at start. Someone who does this often may well have lotion, but as it went, my dude got the skin into his hands, went to the safe room, scraped, saw he had no lotion, went to get lotion, and went back to the safe room to continue. It'd be more streamlines to just check for lotion up front (and additionally during if you run out.)

**Comment by rpherbig** [comment]
> Thanks for renaming the meme term _Salt Bae_ to something I understand in my generation 😆

You know, I saw that and assumed it was something totally reasonable related to salt and cleaning leather and I just wasn't up on the DR crafting lingo 😢

**Comment by KatoakDR** [comment]
> > Thanks for renaming the meme term _Salt Bae_ to something I understand in my generation 😆
> 
> You know, I saw that and assumed it was something totally reasonable related to salt and cleaning leather and I just wasn't up on the DR crafting lingo 😢

I thought the same thing until I started writing up an announcement for Discord and how to use that argument then questioned what does "bae" mean? Then we found the meme/person "Salt Bae" and decided to rename it 🧂

**Pull request merged**
