### PR TITLE
dusk-labyrinth.lic: Update for the new quest that switched to monkeys.

### PR DESCRIPTION
**Pull request by Sarvatt**

### CODE REVIEW

**Comment by rpherbig** [comment]
You might consider naming the Flag something more generic like 'target-found' or 'no-animal' so in the future we only need to change the regex/string.

**Comment by rpherbig** [comment]
It's not a big deal, but there's also still one reference to rats: `rat_dir` on line 18.

**Comment by jandersson** [comment]
The entire capturing group with `rat_dir` can be removed - it was a leftover from a previous iteration on that script where it tried to follow the direction the rat went in.

**Comment by jandersson** [comment]
The pet noun could also be generalized in the regex by just matching on `\w+` instead of `monkey` or `rat`

**Pull request merged**
