### PR TITLE
Crafting magic routine script updates

### PR DESCRIPTION
**Pull request by BinuDR**
Updated 8 of the 9 scripts that use a magic routine.  I did not edit trade.lic because its magic routine had some additional things in it that looked to be specific to that script.

The other 8 are updated and I tested all but remedy.lic

### CODE REVIEW

**Comment by jandersson** [comment]
Posting the build failure to save time:
```
  1) Failure:
TestCommon#test_bput_returns_error_code_after_timeout [/home/travis/build/rpherbig/dr-scripts/test/test_bput.rb:53]:
Expected |15 - 16.23604241383618| (1.2360424138361807) to be <= 1.0.
```

I think the test could use a bit more tolerance for time, maybe 2 seconds instead of 1

**Comment by Sarvatt** [comment]
yeah push a whitespace change or something to get travis to test again, it's almost always just a slow test environment

**Comment by BinuDR** [comment]
Travis is rechecking.

**Comment by rpherbig** [comment]
😂 it's so beautiful

**Comment by BinuDR** [comment]
I'm glad you like it. It made me a bit giddy when I got it working properly. No more stupid flags named differently for each script!

**Comment by Tarhish** [comment]
This is awesome!  I'm diving back in, and I'll look at bringing trade back in line.

**Comment by BinuDR** [comment]
Sounds good!  I didn't want to mess up trader stuff, I'm glad someone who's familiar with it is looking at it instead.

**Pull request merged**
