### PR TITLE
Made attack_override accept a skill variable. 

### PR DESCRIPTION
**Pull request by jayRyan24**
for use with aiming_trainables

### CODE REVIEW

**Comment by jayRyan24** [comment]
Don't merge this yet.

**Comment by jayRyan24** [comment]
https://pastebin.com/PuQvxG5L

**Comment by rpherbig** [comment]
✔️ looks good to me, let me know when it's ready to merge

**Comment by Sarvatt** [comment]
probably unrelated, but any idea why you tried arranging and skinning again after aiming in that log?

**Comment by jayRyan24** [comment]
There's that corpse bug where they stick around after doing shit. It's a SIMU issue, popped up a few weeks ago.

**Comment by jayRyan24** [comment]
I'm good with merging, I've tested as much as I can and it's working aOK.

**Pull request merged**
