### PR TITLE
Adds more carving recipes from apprentice book

### PR DESCRIPTION
**Pull request by Hazado**

### CODE REVIEW

**Comment by Sarvatt** [comment]
are you absolutely sure the ones you set to workorders: true work in workorders?

**Comment by Sarvatt** [comment]
usually the items that need parts that haven't been tested before are broken at the start

**Comment by Hazado** [comment]
actually, base-crafting.yaml needs updating to correct the volume size of alabaster

**Comment by Hazado** [comment]
I didn't add items that need parts. The ones I added and have set to workorders: true are ones that use volume 3 stone and down.

**Comment by Sarvatt** [comment]
medallions don't need parts? the wiki doesnt list the ingredients but for other crafts neck things do is why i was asking

**Comment by Hazado** [comment]
Nope

`        -=   Chapter 4, Page 11: Instructions for crafting a stone medallion    =-

  A stone medallion is a craftable item in the Engineering society under the Carving crafting discipline.  This is considered to be a simple piece to make, though knowledge of the Decorative Stone Design technique will be beneficial to the crafter.

  This item is listed as a "finished stone body jewelry" ingredient type and is created using a chisel set.  A crafter may also find it helpful to have a rasp, a riffler set and a jar of polish on hand.

 A list of ingredients is provided:

   (1) raw stone material (stone)`

**Comment by Sarvatt** [comment]
oh cool, thanks for double checking!

**Pull request merged**
