### PR TITLE
Create Dyler-setup.yaml

### PR DESCRIPTION
**Pull request by DRWafflesworth**

### CODE REVIEW

**Comment by rpherbig** [comment]
The build failed for two reasons:
1) `training_list` is not in `base.yaml` - I'll go fix this right now
2) `stabbity` is not a setting we use. ❓ is this part of a custom script of yours?

**Comment by DRWafflesworth** [comment]
Stabbity was created by Simiy earlier this year, and it is downloaded with the base dependency package. It's a thief-only script that kills every mob in the room as fast as possible.

**Comment by rpherbig** [comment]
Ok, I think I've fixed `base.yaml`. Can you merge `master` into your branch?

**Comment by DRWafflesworth** [comment]
I think I just did that.

**Comment by rpherbig** [comment]
I don't see a merge commit. Did you push it?

**Comment by rpherbig** [comment]
Your other PR (#3779) was a commit on to `master` in your fork. What you want is a merge commit into your branch on your fork, which will automatically get picked up by the GitHub pull request.

**Comment by DRWafflesworth** [comment]
Sorry, this is new and I'm trying to learn it through google

**Pull request closed without merging**
