### PR TITLE
drinfomon.lic - exp all and info squelched

### PR DESCRIPTION
**Pull request by Hazado**
squelches exp all and info when drinfomon sends the commands

### CODE REVIEW

**Comment by Sarvatt** [comment]
any reason not to make this default?

**Comment by Sarvatt** [comment]
i'd be good with this being the default and only showing it if a debug option is set

**Comment by Hazado** [comment]
I can setup some debug options to show, but its not really useful information as you can just do the commands again manually and get the info.
This just allows less initial screen scroll when logging in.

**Comment by rpherbig** [comment]
@Sarvatt can you test this PR?

**Comment by Hazado** [comment]
Ive been using this for a few days and haven’t had any issues. Anyone else test this?

**Comment by Sarvatt** [comment]
it’s working fine for me also.

**Comment by Hazado** [comment]
Added option to show exp all and info

**Pull request merged**
