### PR TITLE
Changed two remedy workorders from false to true. I made both this mo…

### PR DESCRIPTION
**Pull request by Dartellum**
…rning. I do not recall why I made them false.

### CODE REVIEW

**Comment by rpherbig** [comment]
According to #1933, these two were removed because:
> I removed genich from workorders since Shard has it as grenich. I bugged it and posted in Lore folder. 

Has this bug been fixed?

**Comment by Dartellum** [comment]
Good catch. Sadly, it is not corrected in Shard. I wonder if I want to
program around this since more recipes are needed so I do not loop through
s many times looking for one.

Regards,
Dr. Walter Wesley "Wes" Snyder V
484-300-4833 (h)
484-431-3355 (m)

**Comment by Dartellum** [comment]
Actually, I just combined them and they turn into genich from Shard.
You get some dried grenich from inside your embroidered backpack.

                         |
>combine

                        |
You combine the stacks of herbs together
You glance down to see some dried genich in your left hand.

Regards,
Dr. Walter Wesley "Wes" Snyder V
484-300-4833 (h)
484-431-3355 (m)

On Tue, Jan 23, 2018 at 8:15 AM, Dr. Wes Snyder V <dr.wes.snyder.v@gmail.com

**Comment by rpherbig** [comment]
If you're not sure why a line of code is the way it is, there is a good tool to help you investigate: https://git-scm.com/docs/git-blame. In short, `git blame` will tell you the last commit that changed each line. In some files that are changed a lot, that won't help. In files like `base-crafting` that don't change much, it's very effective.

As for grenich vs genich, did you run a workorder in Shard or just test combining the herbs by hand?

**Comment by Dartellum** [comment]
Test combined by hand. My Remedies person is F2P. Dartellum does not have
the tools or skill to use.

Regards,
Dr. Walter Wesley "Wes" Snyder V
484-300-4833 (h)
484-431-3355 (m)

**Pull request closed without merging**
