### PR TITLE
stop rubbing strangers whose names start with my during crafting

### PR DESCRIPTION
**Pull request by 13and3**

### CODE REVIEW

**Comment by Sarvatt** [comment]
my always comes first in the DR parser though, are you sure you didn't just end up in a room without a My person when you tried scrape instead of rub?

**Comment by 13and3** [comment]
It does not always come first, unfortunately, @Sarvatt 


[shape]>rub my amulet with my rasp

You rub Mystylaine.
> 
> scrape am with my rasp

You delicately shape fine detail into the amulet with your rasp.  The knot appears mostly removed with only minimal damage to the limb.
Roundtime: 17 sec.

**Comment by Sarvatt** [comment]
try scrape my am with my rasp

**Comment by Sarvatt** [comment]
(what you changed here)

**Comment by 13and3** [comment]
Every craft verb except rub works fine, and scrape seems to be a replacement for rub.

**Comment by 13and3** [comment]
[sew]>scrape my tunic with my slickstone

You gently lay down your tunic and then smoothly press them out with a polished soapstone slickstone.  Stopping once to flip it over, you slowly work out all creases and wrinkles in the fabric.
Roundtime: 8 sec.
R> 
Mystylaine begins to carefully examine a pair of glistening flame opal chandelier earrings.

**Comment by Sarvatt** [comment]
thanks, +1 from me for the change then.

**Comment by 13and3** [comment]
@Sarvatt Ok.  I don't know this project's merge/approval process.

**Comment by rpherbig** [comment]
It looks good and you seem to have tested it. 👍

**Pull request merged**
