### PR TITLE
Expansion of Smoke script.

### PR DESCRIPTION
**Pull request by jayRyan24**
Added a setting for smoke, renamed to smoker, added ability for flint/blade lighting, added the ability to just smoke a cigar without an image.

### CODE REVIEW

**Comment by jayRyan24** [comment]
https://pastebin.com/54iKbqhh

**Comment by Sarvatt** [comment]
love it, lol

**Comment by jayRyan24** [comment]
I like smoking while sitting around and talking and stuff.

**Comment by Sarvatt** [comment]
i am not a fan of subkeys instead of explicit options though that is the new du jour lately, its hard to document in a way people can see and there are many checks in ruby not obvious that you need to check for .empty? instead of nil which comes up a lot. i guess we could add example usages in comments in base-empty for that. dont mind me, i’m not around just cracking up someone is updating smoke.lic that i laughed my ass off making :)

**Pull request merged**
