### PR TITLE
[scripts] [ranger-companion] Fixing regression from method change

### PR DESCRIPTION
**Pull request by MahtraDR**
I broke this when I implemented the new pause/unpause methods a bit carelessly... Hopefully this version works again.

Results https://github.com/rpherbig/dr-scripts/issues/6077

Leaving as draft till it's tested.

### CODE REVIEW

**Comment by asechrest** [comment]
@MahtraDR Do you have a user testing this? I know you were working with someone who reported the issue.

**Comment by MahtraDR** [comment]
> @MahtraDR Do you have a user testing this? I know you were working with someone who reported the issue.

Waiting on https://github.com/rpherbig/dr-scripts/issues/6077#issuecomment-1226916924 to reply.

**Comment by SaphiaFae** [comment]
Hi Mahtra, Sorry for my slow responses, I'm in Australia so running on an opposite timezone. I put this version of my script into my custom folder and it still has issues pausing scripts right at the start and this time it hangs up trying to pause when feeding. Copy n paste log:

>;rc2
--- Lich: rc2 active.
--- Lich: sc2 paused.
[rc2: Pausing ["sc2"] to run rc2]
[rc2]>whistle for companion
You whistle loudly for your companion.
[Roundtime: 15 seconds]
A baby wolf scrambles in.
>
 * Rock Mage Yilva Yorba joins the adventure.
>
 * Malykai Daemonhart joins the adventure.
>
A baby wolf begins to whimper.
>
[rc2: Cannot pause, trying again in 2 seconds.]
 * Nature's Hand Katarella Steelbender joins the adventure.
>
[rc2: Cannot pause, trying again in 2 seconds.]
[rc2: Cannot pause, trying again in 2 seconds.]
>
[rc2: Cannot pause, trying again in 2 seconds.]
[rc2: Cannot pause, trying again in 2 seconds.]
[rc2: Cannot pause, trying again in 2 seconds.]
>
[rc2: Cannot pause, trying again in 2 seconds.]
[rc2: Cannot pause, trying again in 2 seconds.]
[rc2: Cannot pause, trying again in 2 seconds.]
>
[rc2: Cannot pause, trying again in 2 seconds.]
>;k rc2
[rc2]>signal companion to sleep
You signal to your baby wolf.

The baby wolf wanders off to find a quiet place to sleep.
>
[rc2]>signal companion to hunt
Your companion is not here.
>
--- Lich: rc2 has exited.

**Comment by MahtraDR** [comment]
I'm in New Zealand myself. Would you be able to come on the lich discord and we can try and work through this there?

The way the new pausing method works is by making pausing an exclusive thing. If this script couldn't pause, it's because some other script was holding the exclusive pause at that time. I might have to just get a wolf myself...

**Comment by MahtraDR** [comment]
Oh! Don't rename it. We need it to have the same name because otherwise it'll conflict with the other ranger-companion script.

**Pull request merged**
