### PR TITLE
[script] [spellmonitor] track known barbarian and thief abilities

### PR DESCRIPTION
**Pull request by KatoakDR**
### Background
* GM Javac rolled out `ability` command for Thieves and Barbarians that list their known abilities.
* We can parse this data like we do for magic user's spells to populate `DRSpells.known_spells` and `DRSpells.known_feats` as a way to check if these NMU characters know certain abilities.

### Changes
* Add new procs to parse the ability output for Thieves and Barbarians
* Introduced `$SPELLMONITOR_VERSION` to track this core script like we do with `drinfomon` and `dependency`

### Tests
_Thieves_
```
>ability
From the Subtlety tree, you know the following khri: Darken (Aug), Dampen (Util/Ward), Strike (Aug), Silence (Util), Shadowstep (Util), Harrier (Aug)
From the Finesse tree, you know the following khri: Hasten (Util), Safe (Aug), Avoidance (Aug), Plunder (Aug), Flight (Aug/Ward), Elusion (Aug), Slight (Util)
From the Potence tree, you know the following khri: Focus (Aug), Prowess (Debil), Sight (Aug), Calm (Util), Steady (Aug), Eliminate (Debil), Serenity (Ward), Sagacity (Ward), Terrify (Debil)
You have 7 available slots.

>,e echo DRSpells.known_spells ; echo DRSpells.known_feats
--- Lich: exec1 active.

[exec1: {"Darken"=>true, "Dampen"=>true, "Strike"=>true, "Silence"=>true, "Shadowstep"=>true, "Harrier"=>true, "Hasten"=>true, "Safe"=>true, "Avoidance"=>true, "Plunder"=>true, "Flight"=>true, "Elusion"=>true, "Slight"=>true, "Focus"=>true, "Prowess"=>true, "Sight"=>true, "Calm"=>true, "Steady"=>true, "Eliminate"=>true, "Serenity"=>true, "Sagacity"=>true, "Terrify"=>true}]

[exec1: {}]

--- Lich: exec1 has exited.
```

_Barbarians_
```
>ability
You know the Berserks: Avalanche, Drought.
You know the Forms: Monkey.
You know the Roars: Anger the Earth.
You know the Meditations: Flame, Power, Contemplation.
You know the Masteries: Juggernaut, Duelist.
You recall that you have 0 training sessions remaining with the Guild.

>,e echo DRSpells.known_spells ; echo DRSpells.known_feats
--- Lich: exec1 active.

[exec1: {"Avalanche"=>true, "Drought"=>true, "Monkey"=>true, "Anger the Earth"=>true, "Flame"=>true, "Power"=>true, "Contemplation"=>true}]

[exec1: {"Juggernaut"=>true, "Duelist"=>true}]

--- Lich: exec1 has exited.
```

### CODE REVIEW

**Comment by MahtraDR** [comment]
I am not sure I like the `feats` terminology here. There are spell feats in game, and they aren't these...

**Comment by douglascayers** [comment]
> I am not sure I like the `feats` terminology here. There are spell feats in game, and they aren't these...

You're right that in game they're called "masteries" for Barbarians and "feats" for magic users. 

Functionality wise, Barbarian masteries are the equivalent of magical feats. They both cost 1 spell/ability slot, provide a passive benefit (e.g. reduce mana/inner fire cost, increase effective ranks of a skill, etc), and are not taught by the guild leader.

**Comment by KatoakDR** [comment]
> I am not sure I like the `feats` terminology here. There are spell feats in game, and they aren't these...

You're right that in game they're called "masteries" for Barbarians and "feats" for magic users. 

Functionality wise, Barbarian masteries are the equivalent of magical feats. They both cost 1 spell/ability slot, provide a passive benefit (e.g. reduce mana/inner fire cost, increase effective ranks of a skill, etc), and are not taught by the guild leader.

**Review by rpherbig — APPROVED** [review]

**Comment by KatoakDR** [comment]
> I am not sure I like the `feats` terminology here. There are spell feats in game, and they aren't these...

I also just remembered you don't have a barbarian to test with so you may not have been aware of Javac's recent rewrite of masteries to be equivalent of feats. Here's the new masteries wiki page: https://elanthipedia.play.net/Category:Barbarian_masteries

**Comment by MahtraDR** [comment]
Breaks nothing, adds info. Tests well for me. Merging.

**Pull request merged**
