### PR TITLE
[script][common-items] Add lift? method

### PR DESCRIPTION
**Pull request by Raykyn55**
Placed alongside the lower method, this simply lifts the first item at your feet and returns the interactable adj/noun pair. If there is nothing at your feet, or if you can't pick it up, returns false.

### CODE REVIEW

**Comment by asechrest** [comment]
Thoughts on broadening this to be a fully-functioning predicate method for the `lift` verb?

https://elanthipedia.play.net/Lift_command

**Comment by Raykyn55** [comment]
found this hanging out in the xml stream:
```
<popStream/><prompt time="1674764755">&gt;</prompt>

All of your items lying at your feet:



    <d cmd='get #45090426'>an owl-feather quill with a slender diacan tip</d>

<prompt time="1674764756">&gt;</prompt>
```
So added a little to drinfomon to pick that up and make a hash in uservars, keys being item ids, values being the full name of the item. That way we can pick up specific items by the id, instead of trying to figure out what the name is around all the fluffy text.

Additionally, created a couple other methods for case-specific handling of the feet slot. Whether we know what we want, or where we want to put whatever it is, or what it is and where we want it, or we just want to stow whatever is there, theres a method for that. If we just want a list, running check_feet will tell us if there's anything there, and simultaneously populate the UserVar.items_at_feet for interaction.

**Comment by Raykyn55** [comment]
```
>get oil
You get a big flask of oil painted with malachite stripes from inside your enshrouding clouds.
>lower ground
You lower the oil and place it on the ground at your feet.
>get brush
You get an iron wire brush from inside your enshrouding clouds.
>lower ground
You lower the brush and place it on the ground at your feet.
>;e echo DRCI.clean_feet
--- Lich: exec1 active.
[exec1]>lift
You pick up the brush lying at your feet.
>
[exec1]>stow my wire brush
>
You put your brush in your featherlette pack.
>
[exec1]>lift
You pick up the oil lying at your feet.
>
[exec1]>stow my oil
You put your oil in your featherlette pack.
>
[exec1]>lift
There are no items lying at your feet.

Do you even?  Check LIFT HELP for syntax!
>
[exec1: ]
--- Lich: exec1 has exited.
```
```
>get oil
You get a big flask of oil painted with malachite stripes from inside your featherlette pack.
>lower ground
You lower the oil and place it on the ground at your feet.
>get brush
You get an iron wire brush from inside your featherlette pack.
>lower ground
>
You lower the brush and place it on the ground at your feet.
>;e echo DRCI.clean_feet('clouds')
--- Lich: exec1 active.
[exec1]>lift
You pick up the brush lying at your feet.
>
[exec1]>put my wire brush in my clouds
You put your brush in your enshrouding clouds.
>
[exec1]>lift
You pick up the oil lying at your feet.
>
[exec1]>put my oil in my clouds
You put your oil in your enshrouding clouds.
>
[exec1]>lift
There are no items lying at your feet.

Do you even?  Check LIFT HELP for syntax!
>
[exec1: ]
--- Lich: exec1 has exited.
```
```
>get brush
You get an iron wire brush from inside your featherlette pack.
>lower ground
>
You lower the brush and place it on the ground at your feet.
>
The wind whistles through a small hollow midway up the trunk of the tree.

>;e echo DRCI.lift_and_stow("wire brush", "clouds")
--- Lich: exec1 active.
[exec1]>lift list
All of your items lying at your feet:

    an iron wire brush
>
[exec1]>get #67507284
You pick up the brush lying at your feet.
>
[exec1]>put my wire brush in my clouds
You put your brush in your enshrouding clouds.
>
[exec1: true]
--- Lich: exec1 has exited.
```
```
>get brush
>
You get an iron wire brush from inside your enshrouding clouds.
>lower ground
You lower the brush and place it on the ground at your feet.
>get oil
You get a big flask of oil painted with malachite stripes from inside your enshrouding clouds.
>lower ground
You lower the oil and place it on the ground at your feet.
>;e echo DRCI.lift_and_stow("wire brush", "clouds")
--- Lich: exec1 active.
[exec1]>lift list
All of your items lying at your feet:

    a big flask of oil painted with malachite stripes
    an iron wire brush
>
[exec1]>get #67507284
You pick up the brush lying at your feet.
>
[exec1]>put my wire brush in my clouds
You put your brush in your enshrouding clouds.
>
[exec1: true]
--- Lich: exec1 has exited.
```

**Comment by Raykyn55** [comment]
I think this is the most sensible arrangement. Different scripts will have different needs regarding items at your feet. Some will want to just pick up everything (burgle would use clean_feet), others will want to lift items specifically(enchant for founts will use lift and stow with specific items/bags), and scripts like wand-watcher will want to just lift the thing it lowered(lift_specific).

**Comment by asechrest** [comment]
I was honestly thinking a simple predicate method that allowed to specify an item, or not, and specify lift's stow function, or not. Sort of like this:

```ruby
  @@lift_success_patterns = [
    /^You pick up/
  ]

  @@lift_stow_success_patterns = [
    /^You put your/
  ]

  @@lift_failure_patterns = [
    *@@stow_item_failure_patterns,
    *@@container_is_closed_patterns,
    /^There are no items lying at your feet/,
    /^What did you want to try and lift/,
    /can't quite lift it/,
    /^You are not strong enough to pick that up/
  ]

  def lift?(item = nil, stow = false)
    success_patterns = stow ? @@lift_stow_success_patterns : @@lift_success_patterns
    lift_phrase = stow ? "lift stow #{item}" : "lift #{item}"

    lifted = DRC.bput(lift_phrase, *success_patterns, *@@lift_failure_patterns)
    case lifted
    when *success_patterns
      true
    else
      false
    end
  end
```

**Comment by Raykyn55** [comment]
> I was honestly thinking a simple predicate method that allowed to specify an item, or not, and specify lift's stow function, or not. Sort of like this:

One possible issue is you don't deal with stow problems. You could receive true from that method and still be holding the item.  Also, things like tools might be tied to something, or be placed in a special bag (other than our default stow location). Thrown/ranged weapons that don't fit in a bag, or the bag might be closed for whatever reason.

It's also nice to know what we picked up, in case we have something in our other hand. I think lift as a verb is a special case, in that it picks up the first thing at our feet. It's like if there was a generic 'get' verb, that just grabbed the first thing. I think we'd want to know what it is.

**Comment by asechrest** [comment]
> One possible issue is you don't deal with stow problems. You could receive true from that method and still be holding the item. Also, things like tools might be tied to something, or be placed in a special bag (other than our default stow location). Thrown/ranged weapons that don't fit in a bag, or the bag might be closed for whatever reason.

I agree, you don't deal with stow problems, but my feeling is that this is not the place to do so. The main advantage, to me, of `lift stow`, is that it gets and stows in a single swoop. It's no-nonsense. We can allow the user to decide whether they want to take advantage of that, along with the disadvantages, or just `lift` or `lift <item>` and handle the stowing separately, since we have existing methods already built out for standalone `stow` and `put_away_item`, etc.

> It's also nice to know what we picked up, in case we have something in our other hand. I think lift as a verb is a special case, in that it picks up the first thing at our feet. It's like if there was a generic 'get' verb, that just grabbed the first thing. I think we'd want to know what it is.

I remember your original commit seemed to return the item we lifted (truthy), or false. I think I'm ok with that, too, though it can be difficult to process and separate the adjective and noun of items even when we know what the item is. IIRC we have methods to lean on for that, though.

I'll tag @MahtraDR for additional thoughts.

**Comment by Raykyn55** [comment]
> > One possible issue is you don't deal with stow problems. You could receive true from that method and still be holding the item. Also, things like tools might be tied to something, or be placed in a special bag (other than our default stow location). Thrown/ranged weapons that don't fit in a bag, or the bag might be closed for whatever reason.
> 
> I agree, you don't deal with stow problems, but my feeling is that this is not the place to do so. The main advantage, to me, of `lift stow`, is that it gets and stows in a single swoop. It's no-nonsense. We can allow the user to decide whether they want to take advantage of that, along with the disadvantages, or just `lift` or `lift <item>` and handle the stowing separately, since we have existing methods already built out for standalone `stow` and `put_away_item`, etc.

```ruby
def lift?(item = nil, stow = nil)
  /^(You pick up|You put)/ =~ fput("lift #{stow} #{item}")
end
```

If simple is the goal.

**Comment by Raykyn55** [comment]
change to lift_specific;
```ruby
    return false unless item_id = UserVars.items_at_feet.find { |id,desc| item.split.all? { |names| desc.include?(names) } }.first
```
enchant code for pickups:
```ruby
    DRCI.lift_and_stow(@fount, @bag) # grab and stash our fount
    DRCI.lift? # pick up the completed item
```
@fount = "fragile fount"
Actual name: "rough fragile mana fount"

log in use:
```
[enchant]>wave imbuement rod at totem on silversteel brazier
The spell is channeled through the fount hanging above, and down into the totem.  After focusing the streams into ordered groups you then direct them into exacting positions.
Roundtime: 14 sec.
The spell's energies settle upon the totem and seal off the pattern.  With the enchanting process completed, you believe it is safe to collect your things once more.
You collect the fount and place it at your feet.
You collect the totem and place it at your feet.
>
[enchant]>tie my imbuement rod to my forger's belt
...wait 1 seconds.
>
[enchant]>tie my imbuement rod to my forger's belt
You attach a translucent imbuement rod resembling a shard of ice to a strap on your forger's belt.
>
[enchant]>tie my silversteel brazier to my forger's belt
You attach a small silversteel brazier scattered with glittering starstones to a strap on your forger's belt.
>
[enchant]>lift list
All of your items lying at your feet:

    a plain bone totem
    a fragile rough mana fount
>
[enchant]>get #120781382
You pick up the fount lying at your feet.
>
[enchant]>put my fragile fount in my enshrouding clouds
You put your fount in your enshrouding clouds.
>
[enchant]>lift
You pick up the totem lying at your feet.
>
--- Lich: enchant has exited.
```

**Comment by Raykyn55** [comment]
Pared this down similar to https://github.com/rpherbig/dr-scripts/pull/6312#issuecomment-1416917395

method can be run as follows:

No argument to simply lift the first item at your feet:
```ruby
DRCI.lift?
```
item argument to lift a specific item from your feet and return true/false:
```ruby
DRCI.lift?('item')
```
item argument and stow as true to lift a specific item and stow it generally:
```
ruby
DRCI.lift?('item', true)
```
item argument and stow as a container string to lift a specific item and stow it specifically:
```ruby
DRCI.lift?('item', 'bag')
```
Only thing you can't do is lift generally and stow specifically.

**Comment by Raykyn55** [comment]
Actually, suppose you could run it:
```ruby
DRCI.lift?(nil, true)
```
for general item general stow

or
```ruby
DRCI.lift?(nil, 'bag')
```
for general item specific stow, respectively.

**Comment by Raykyn55** [comment]
Testing on this, and the bottom line is this. If we want to stow specifically, we need to know what we're picking up. 

> Actually, suppose you could run it:
> 
> ```ruby
> DRCI.lift?(nil, true)
> ```
> 
> for general item general stow
> 
> or
> 
> ```ruby
> DRCI.lift?(nil, 'bag')
> ```
> 
> for general item specific stow, respectively.
> 
> Or. . .
> 
> ```ruby
> DRCI.lift?('stow')
> ```
> 
> for general/general.

The last version works, but the previous two will not. best to do something like:
```ruby
DRCC.stow_crafting_item(DRC.right_hand, @bag, @belt) if DRCI.lift?
```
for generic item stowing specifically.

**Pull request closed without merging**
