### PR TITLE
Adding custom folder to .gitignore

### PR DESCRIPTION
**Pull request by m-burroughs**
### User Story
- **_As a ..._** Dragonrealms player who wants to write custom scripts.
- **_I need ..._** an easy way to work on my scripts without worrying about accidentally committing them.
- **_So that I can ..._** make awesome scripts, safely.

### Description
1. It is probably the case that custom scripts should never be added to the code base, so I have added the appropriate filtering to the `.gitignore` file for the project.

### CODE REVIEW

**Comment by MahtraDR** [comment]
Lich creates the custom dir itself. We don't need to be creating or maintaining it here too. 

Happy to add to gitignore but I rather we not keep custom here too.

**Comment by MahtraDR** [comment]
Expanding a bit. 
In lich4/dr-lich the custom dir  was added here: https://github.com/dragon-realms/dr-lich/pull/64

In lich5, it was added here: https://github.com/elanthia-online/lich-5/pull/130

**Comment by asechrest** [comment]
The /custom folder was created primarily to allow folks to customize _current_ repo scripts and utilize them without them being overwritten each game session when the scripts are pulled down from the repo. The /custom folder isn't maintained here, but Lich now looks to for scripts in a hierarchy _beginning_ with the /custom folder.

Previously, if you want to make a tweak to `combat-trainer` for your own use, and you didn't want Lich to overwrite `combat-trainer.lic` each time you connected to the game, you had to go on dev mode. Now, you simply place a copy in your /custom folder, tweak it, and Lich will use that file instead of the one in /scripts.

To your point above, I see three scenarios here:

1. You want to create new, custom scripts for your _own_ use, and not contribute to the repository.
2. You want to create new, custom scripts that you contribute to the repository.
3. You want to edit existing repo scripts and customize them for your own use and not contribute to the repository.

Here is the procedure I use for each:

1. If you wan to create new, custom scripts for your own use, create them with their own unique name and place them in your /scripts folder.
2. If you want to create new, custom scripts that you contribute to the repository, create in your /scripts folder and PR to the repo as appropriate.
3. If you want to edit existing repo scripts for your own use, place a copy in your /custom folder and edit it there, and Lich will use that version vs. the same-named version in /scripts.

**Comment by m-burroughs** [comment]
> Here is the procedure I use for each:
> 
> 1. If you wan to create new, custom scripts for your own use, create them with their own unique name and place them in your /scripts folder.
> 2. If you want to create new, custom scripts that you contribute to the repository, create in your /scripts folder and PR to the repo as appropriate.
> 3. If you want to edit existing repo scripts for your own use, place a copy in your /custom folder and edit it there, and Lich will use that version vs. the same-named version in /scripts.

In response to this, on points 2 and 3 I agree.  However, for point 1, I find myself feeling far more organized by putting my own custom scripts for personal use in the `/custom` folder as well to make it easy to tell which are owned by whom.  I have no intention of ever committing them for public use, so it makes sense.

I've removed the `/custom` folder from the pull request, and simply left the `.gitignore` entry.

For the most part, this was just me getting back in to the feel of contributing to this project, as I'm enjoying DR very much again, and hope to make a few contributions.

**Comment by m-burroughs** [comment]
Pull request title and description have been updated to reflect new intent.

**Comment by asechrest** [comment]
> For the most part, this was just me getting back in to the feel of contributing to this project, as I'm enjoying DR very much again, and hope to make a few contributions.

Thanks. Looking forward to see another contributor!

**Pull request merged**
