### PR TITLE
[script][tarantula] New pause strat

### PR DESCRIPTION
**Pull request by Raykyn55**
This is a more deliberate pause that sits outside the use routines. Testing positively.

### CODE REVIEW

**Comment by dantiadr** [comment]
Have been testing this updated version for about 16 hours with no incident! Appears to have fixed the tarantula-related unpausing issue that was preventing other scripts from resuming after tarantula fired.

**Comment by Raykyn55** [comment]
Testing yielded the following issue:

```
--- Lich: empathylink paused.

--- Lich: almanac paused.

--- Lich: sanowret-crystal paused.

--- Lich: play paused.

--- Lich: t2 paused.

--- Lich: hunting-buddy paused.

--- Lich: combat-trainer paused.

Pausing ["empathylink", "almanac", "sanowret-crystal", "play", "t2", "hunting-buddy", "combat-trainer"] to run tarantula

[tarantula]>turn my tarantula to Augmentation
> 
You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
However, your changes fail to lock into place.
[You need to vary which skillset you select with every use.  Magic was your last used skillset.]
> 
A lava drake rears back and opens its fiery maw, unleashing a gout of scorching air and dust directly into your eyes!
As the cloud of dirt sails towards you, you manage to sidestep out of the way!
The dirt cloud sails on further, dissipating into tiny brown specks which glide back down to the ground.
> 
The lava drake begins to advance on you!
The lava drake is still a distance away from you and is closing steadily.
> 
[tarantula]>study tarantula

As you examine the biomechanical tarantula, intuitive knowledge of its function and mechanics spring into your short-term memory.  You are unable to capture the great majority of the information, but are able to concentrate on the broad strokes.
The biomechanical tarantula is imbued with an unknown psychic power that is concentrated in its venom and can be adjusted by TURNing the various dials and levers along its mechanical abdomen.  RUBing the spider will aggitate it to strike, injecting yourself with its psychic venom.  The exact nature of the venom and its physiological effects are vastly too complex for this transfer of knowledge to encompass, but it will do something to your mind to consume a portion of your memories and transform it into artifical memories that can be applied more broadly to like-skills.
In addition to this, you can tell that the tarantula can indulge in metallophagia.  If SHAKEn with forging metal in the other hand, the tarantula will consume it and somehow change its mechanical components to mirror its meal.
The tarantula is currently set to consume Life Magic experience and when last used gave unbidden knowledge of Magic techniques.
Roundtime: 5 sec.
[The biomechanical tarantula is bonded to you without charges.]
> 
Pausing [] to run tarantula

> 
Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)

A tiny shadowling just flew in, cackling madly over the copper coin it carries in its paws.

> 
You feel fully prepared to cast your spell.
> 
Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)

> 
Pulsed: Skinning(-1)

[tarantula]>turn my tarantula to Light Armor

You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
With a *click*, your changes snap into place.  The biomechanical tarantula will now consume Light Armor knowledge.
> 
[tarantula]>rub my tarantula

The tarantula comes alive in your hand!  It skitters to the top of your spine, moving with far more agility than its metallic heaviness should allow.  A sharp stab of pain erupts at the base of your neck as it injects venom into your nervous system!
It is mere moments afterward that you feel an itching, tingling, and crawling sensation all across the inside of your skull.  In a mind-wracking flurry of sensation, you find yourself forgetting your recent progress on light armor, but somehow unbidden knowledge into other Armors tasks are mapped into your psyche.
> 
Pulsed: Light Armor(-34)

> 
Unpausing [], tarantula has finished.
```
Looks like when it went back through to turn after changing skill, it redefined the list as blank. Most recent commit should sort that, back into testing we go.

**Comment by Dartellum** [comment]
I'll test as well.

**Comment by Raykyn55** [comment]
Update to localize, expand variable names to forestall overlaps.
Moved to safe_pause_list
requires https://github.com/rpherbig/dr-scripts/pull/6043

**Comment by Dartellum** [comment]
> Update to localize, expand variable names to forestall overlaps. Moved to safe_pause_list requires #6043

Testing with new features.

**Comment by Dartellum** [comment]
> Testing yielded the following issue:
> 
> ```
> --- Lich: empathylink paused.
> 
> --- Lich: almanac paused.
> 
> --- Lich: sanowret-crystal paused.
> 
> --- Lich: play paused.
> 
> --- Lich: t2 paused.
> 
> --- Lich: hunting-buddy paused.
> 
> --- Lich: combat-trainer paused.
> 
> Pausing ["empathylink", "almanac", "sanowret-crystal", "play", "t2", "hunting-buddy", "combat-trainer"] to run tarantula
> 
> [tarantula]>turn my tarantula to Augmentation
> > 
> You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
> However, your changes fail to lock into place.
> [You need to vary which skillset you select with every use.  Magic was your last used skillset.]
> > 
> A lava drake rears back and opens its fiery maw, unleashing a gout of scorching air and dust directly into your eyes!
> As the cloud of dirt sails towards you, you manage to sidestep out of the way!
> The dirt cloud sails on further, dissipating into tiny brown specks which glide back down to the ground.
> > 
> The lava drake begins to advance on you!
> The lava drake is still a distance away from you and is closing steadily.
> > 
> [tarantula]>study tarantula
> 
> As you examine the biomechanical tarantula, intuitive knowledge of its function and mechanics spring into your short-term memory.  You are unable to capture the great majority of the information, but are able to concentrate on the broad strokes.
> The biomechanical tarantula is imbued with an unknown psychic power that is concentrated in its venom and can be adjusted by TURNing the various dials and levers along its mechanical abdomen.  RUBing the spider will aggitate it to strike, injecting yourself with its psychic venom.  The exact nature of the venom and its physiological effects are vastly too complex for this transfer of knowledge to encompass, but it will do something to your mind to consume a portion of your memories and transform it into artifical memories that can be applied more broadly to like-skills.
> In addition to this, you can tell that the tarantula can indulge in metallophagia.  If SHAKEn with forging metal in the other hand, the tarantula will consume it and somehow change its mechanical components to mirror its meal.
> The tarantula is currently set to consume Life Magic experience and when last used gave unbidden knowledge of Magic techniques.
> Roundtime: 5 sec.
> [The biomechanical tarantula is bonded to you without charges.]
> > 
> Pausing [] to run tarantula
> 
> > 
> Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
> 
> A tiny shadowling just flew in, cackling madly over the copper coin it carries in its paws.
> 
> > 
> You feel fully prepared to cast your spell.
> > 
> Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
> 
> > 
> Pulsed: Skinning(-1)
> 
> [tarantula]>turn my tarantula to Light Armor
> 
> You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
> With a *click*, your changes snap into place.  The biomechanical tarantula will now consume Light Armor knowledge.
> > 
> [tarantula]>rub my tarantula
> 
> The tarantula comes alive in your hand!  It skitters to the top of your spine, moving with far more agility than its metallic heaviness should allow.  A sharp stab of pain erupts at the base of your neck as it injects venom into your nervous system!
> It is mere moments afterward that you feel an itching, tingling, and crawling sensation all across the inside of your skull.  In a mind-wracking flurry of sensation, you find yourself forgetting your recent progress on light armor, but somehow unbidden knowledge into other Armors tasks are mapped into your psyche.
> > 
> Pulsed: Light Armor(-34)
> 
> > 
> Unpausing [], tarantula has finished.
> ```
> 
> Looks like when it went back through to turn after changing skill, it redefined the list as blank. Most recent commit should sort that, back into testing we go.

I am still getting this. Perhaps just change to new pause and not localize the variables?

**Comment by Raykyn55** [comment]
> > Testing yielded the following issue:
> > ```
> > --- Lich: empathylink paused.
> > 
> > --- Lich: almanac paused.
> > 
> > --- Lich: sanowret-crystal paused.
> > 
> > --- Lich: play paused.
> > 
> > --- Lich: t2 paused.
> > 
> > --- Lich: hunting-buddy paused.
> > 
> > --- Lich: combat-trainer paused.
> > 
> > Pausing ["empathylink", "almanac", "sanowret-crystal", "play", "t2", "hunting-buddy", "combat-trainer"] to run tarantula
> > 
> > [tarantula]>turn my tarantula to Augmentation
> > > 
> > You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
> > However, your changes fail to lock into place.
> > [You need to vary which skillset you select with every use.  Magic was your last used skillset.]
> > > 
> > A lava drake rears back and opens its fiery maw, unleashing a gout of scorching air and dust directly into your eyes!
> > As the cloud of dirt sails towards you, you manage to sidestep out of the way!
> > The dirt cloud sails on further, dissipating into tiny brown specks which glide back down to the ground.
> > > 
> > The lava drake begins to advance on you!
> > The lava drake is still a distance away from you and is closing steadily.
> > > 
> > [tarantula]>study tarantula
> > 
> > As you examine the biomechanical tarantula, intuitive knowledge of its function and mechanics spring into your short-term memory.  You are unable to capture the great majority of the information, but are able to concentrate on the broad strokes.
> > The biomechanical tarantula is imbued with an unknown psychic power that is concentrated in its venom and can be adjusted by TURNing the various dials and levers along its mechanical abdomen.  RUBing the spider will aggitate it to strike, injecting yourself with its psychic venom.  The exact nature of the venom and its physiological effects are vastly too complex for this transfer of knowledge to encompass, but it will do something to your mind to consume a portion of your memories and transform it into artifical memories that can be applied more broadly to like-skills.
> > In addition to this, you can tell that the tarantula can indulge in metallophagia.  If SHAKEn with forging metal in the other hand, the tarantula will consume it and somehow change its mechanical components to mirror its meal.
> > The tarantula is currently set to consume Life Magic experience and when last used gave unbidden knowledge of Magic techniques.
> > Roundtime: 5 sec.
> > [The biomechanical tarantula is bonded to you without charges.]
> > > 
> > Pausing [] to run tarantula
> > 
> > > 
> > Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
> > 
> > A tiny shadowling just flew in, cackling madly over the copper coin it carries in its paws.
> > 
> > > 
> > You feel fully prepared to cast your spell.
> > > 
> > Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
> > 
> > > 
> > Pulsed: Skinning(-1)
> > 
> > [tarantula]>turn my tarantula to Light Armor
> > 
> > You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
> > With a *click*, your changes snap into place.  The biomechanical tarantula will now consume Light Armor knowledge.
> > > 
> > [tarantula]>rub my tarantula
> > 
> > The tarantula comes alive in your hand!  It skitters to the top of your spine, moving with far more agility than its metallic heaviness should allow.  A sharp stab of pain erupts at the base of your neck as it injects venom into your nervous system!
> > It is mere moments afterward that you feel an itching, tingling, and crawling sensation all across the inside of your skull.  In a mind-wracking flurry of sensation, you find yourself forgetting your recent progress on light armor, but somehow unbidden knowledge into other Armors tasks are mapped into your psyche.
> > > 
> > Pulsed: Light Armor(-34)
> > 
> > > 
> > Unpausing [], tarantula has finished.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Looks like when it went back through to turn after changing skill, it redefined the list as blank. Most recent commit should sort that, back into testing we go.
> 
> I am still getting this. Perhaps just change to new pause and not localize the variables?

Wondering if you have the most recent version. This has the new pause. The variable for pause list is a class variable, so once set, shouldnt be unset until it escapes back to the loop, which means it should only ever pause the once until then. Honestly, if you have the version up now, i'm prob just going to bow out on this script. I cant test it, and no matter how its written it seems to yield the same error.

**Comment by Dartellum** [comment]
> > > Testing yielded the following issue:
> > > ```
> > > --- Lich: empathylink paused.
> > > 
> > > --- Lich: almanac paused.
> > > 
> > > --- Lich: sanowret-crystal paused.
> > > 
> > > --- Lich: play paused.
> > > 
> > > --- Lich: t2 paused.
> > > 
> > > --- Lich: hunting-buddy paused.
> > > 
> > > --- Lich: combat-trainer paused.
> > > 
> > > Pausing ["empathylink", "almanac", "sanowret-crystal", "play", "t2", "hunting-buddy", "combat-trainer"] to run tarantula
> > > 
> > > [tarantula]>turn my tarantula to Augmentation
> > > > 
> > > You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
> > > However, your changes fail to lock into place.
> > > [You need to vary which skillset you select with every use.  Magic was your last used skillset.]
> > > > 
> > > A lava drake rears back and opens its fiery maw, unleashing a gout of scorching air and dust directly into your eyes!
> > > As the cloud of dirt sails towards you, you manage to sidestep out of the way!
> > > The dirt cloud sails on further, dissipating into tiny brown specks which glide back down to the ground.
> > > > 
> > > The lava drake begins to advance on you!
> > > The lava drake is still a distance away from you and is closing steadily.
> > > > 
> > > [tarantula]>study tarantula
> > > 
> > > As you examine the biomechanical tarantula, intuitive knowledge of its function and mechanics spring into your short-term memory.  You are unable to capture the great majority of the information, but are able to concentrate on the broad strokes.
> > > The biomechanical tarantula is imbued with an unknown psychic power that is concentrated in its venom and can be adjusted by TURNing the various dials and levers along its mechanical abdomen.  RUBing the spider will aggitate it to strike, injecting yourself with its psychic venom.  The exact nature of the venom and its physiological effects are vastly too complex for this transfer of knowledge to encompass, but it will do something to your mind to consume a portion of your memories and transform it into artifical memories that can be applied more broadly to like-skills.
> > > In addition to this, you can tell that the tarantula can indulge in metallophagia.  If SHAKEn with forging metal in the other hand, the tarantula will consume it and somehow change its mechanical components to mirror its meal.
> > > The tarantula is currently set to consume Life Magic experience and when last used gave unbidden knowledge of Magic techniques.
> > > Roundtime: 5 sec.
> > > [The biomechanical tarantula is bonded to you without charges.]
> > > > 
> > > Pausing [] to run tarantula
> > > 
> > > > 
> > > Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
> > > 
> > > A tiny shadowling just flew in, cackling madly over the copper coin it carries in its paws.
> > > 
> > > > 
> > > You feel fully prepared to cast your spell.
> > > > 
> > > Learned: Evasion(0), Shield Usage(0), Defending(0), Light Armor(0), Chain Armor(0), Brigandine(0), Plate Armor(0)
> > > 
> > > > 
> > > Pulsed: Skinning(-1)
> > > 
> > > [tarantula]>turn my tarantula to Light Armor
> > > 
> > > You fiddle with the tiny levers and dials of the tarantula's mechanical abdomen.  The process is complex, but you feel an intuitive grasp of the mechanism from the moment you touch it.
> > > With a *click*, your changes snap into place.  The biomechanical tarantula will now consume Light Armor knowledge.
> > > > 
> > > [tarantula]>rub my tarantula
> > > 
> > > The tarantula comes alive in your hand!  It skitters to the top of your spine, moving with far more agility than its metallic heaviness should allow.  A sharp stab of pain erupts at the base of your neck as it injects venom into your nervous system!
> > > It is mere moments afterward that you feel an itching, tingling, and crawling sensation all across the inside of your skull.  In a mind-wracking flurry of sensation, you find yourself forgetting your recent progress on light armor, but somehow unbidden knowledge into other Armors tasks are mapped into your psyche.
> > > > 
> > > Pulsed: Light Armor(-34)
> > > 
> > > > 
> > > Unpausing [], tarantula has finished.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Looks like when it went back through to turn after changing skill, it redefined the list as blank. Most recent commit should sort that, back into testing we go.
> > 
> > 
> > I am still getting this. Perhaps just change to new pause and not localize the variables?
> 
> Wondering if you have the most recent version. This has the new pause. The variable for pause list is a class variable, so once set, shouldnt be unset until it escapes back to the loop, which means it should only ever pause the once until then. Honestly, if you have the version up now, i'm prob just going to bow out on this script. I cant test it, and no matter how its written it seems to yield the same error.

I'll grab the latest and test.

**Pull request closed without merging**
