### PR TITLE
[script][workorders] Cost calculations for workorders

### PR DESCRIPTION
**Pull request by Raykyn55**
requires https://github.com/rpherbig/dr-scripts/pull/6084

Uses cost calculator or @cash_on_hand, whichever is greater, for a single cash grab before starting our workorders.

### CODE REVIEW

**Comment by Dartellum** [comment]
When my PRs are merged, `enchant_stock1_name` through `enchant_stock4_name` will get added. That way all we have the name of the sigil to do other things with.

**Comment by Raykyn55** [comment]
> When my PRs are merged, `enchant_stock1_name` through `enchant_stock4_name` will get added. That way all we have the name of the sigil to do other things with.

I thought i'd seen that in one of them, but I looked through and didn't see any changes to recipes, so I figured I'd put this in and can add those when they appear. mention this PR when you put them in?

**Comment by Dartellum** [comment]
> > When my PRs are merged, `enchant_stock1_name` through `enchant_stock4_name` will get added. That way all we have the name of the sigil to do other things with.
> 
> I thought i'd seen that in one of them, but I looked through and didn't see any changes to recipes, so I figured I'd put this in and can add those when they appear. mention this PR when you put them in?

Mentioned! :smile:

**Comment by Raykyn55** [comment]
requires https://github.com/rpherbig/dr-scripts/pull/6072

**Pull request closed without merging**
