### PR TITLE
Add optional tries parameter to forage?

### PR DESCRIPTION
**Pull request by robbintt**
Add tries and return false if tries are exhausted.

### CODE REVIEW

**Comment by Tarhish** [comment]
Looking back at this method, I think it's actually better if the default would be failing false after a set number of tries.  It does have escapes set for if the area isn't forageable, but if you try to forage for, say, grass in a room with no grass then it'll never escape. I can't see anything in the code base that uses forage? that wouldn't be improved by the ability to abort after, say, twenty attempts instead of going on infinitely looking for an item in a place that it isn't seeded.

My personal vote would be that this method just defaults to something like ten or twenty attempts, then returns false if it runs out the clock.  If that's the case then both of these changes would become simpler too.

**Comment by rpherbig** [comment]
I like that idea @Tarhish . What do you think, @robbintt ?

**Comment by robbintt** [comment]
Nice data.  I've updated it, but I haven't used a ternary in ruby before. I assume it works this way? I can test it out.

**Comment by rpherbig** [comment]
Looks good to me. Thanks again @robbintt and @Tarhish ! 🎉

**Pull request merged**
