### PR TITLE
[script][forge] Rewrite

### PR DESCRIPTION
**Pull request by Raykyn55**
The good:
- Everything works. Enhancements, Temper, RESUME, but especially armor crafting.
- Backwards compatibility. Any script that used forge previously, uses this script with the same arguments to the same effect.
- Supports adjustable tongs on the new method more intelligently
- debugging argument with a good bit of information to see what's actually going on. Also monitors debug_mode.
- tools handling is a little cleaner, more in line with how shape handles them. There are some differences by necessity, but in large part, tool changes are done with the right hand, and items are held in your left. 

The bad:
- It's more complicated. A lot of the methods in forge have been subsumed into work or prep method. Not as easy to follow the logic.
- Likely instance variables that could be local, especially since settings is passed. Fresh eyes would be helpful.

The ugly:
- work method is big, easy to get lost in. If something is broken there, no aspect of this script will work properly. Before, even if say hone didn't work, temper would. If armor didn't work, weaponsmithing would. In this, either they all work, or none do.

### CODE REVIEW

**Comment by MahtraDR** [comment]
I've got this going on mine. Will revert.

**Comment by Raykyn55** [comment]
Plural spikes and you get need, not needs. works fine without those two words.

**Review by MahtraDR — APPROVED** [review]
This tests well for me.

**Comment by MahtraDR** [comment]
Encountered an issue last night where it wasn't pulling oil from crafting container, and used up all my holy oil instead. We're working through these.

**Comment by Raykyn55** [comment]
Change 'of oil' to 'oil' to match crafting container settings. If you're holding more than one type of oil, you'll want to have 'oil' listed under that crafting_items_in_container.

**Comment by MahtraDR** [comment]
> Change 'of oil' to 'oil' to match crafting container settings. If you're holding more than one type of oil, you'll want to have 'oil' listed under that crafting_items_in_container.

Yep yep, this is the expected behaviour. :)

**Comment by Raykyn55** [comment]
> > Change 'of oil' to 'oil' to match crafting container settings. If you're holding more than one type of oil, you'll want to have 'oil' listed under that crafting_items_in_container.
> 
> Yep yep, this is the expected behaviour. :)

With that in mind, changed how smith handles this as well, so it doesn't go and dump your holy oil.

**Comment by BinuDR** [comment]
> > > Change 'of oil' to 'oil' to match crafting container settings. If you're holding more than one type of oil, you'll want to have 'oil' listed under that crafting_items_in_container.
> > 
> > 
> > Yep yep, this is the expected behaviour. :)
> 
> With that in mind, changed how smith handles this as well, so it doesn't go and dump your holy oil.

The way I had this setup before was that it would `look oil` in your crafting container, and if it wasn't the correct type it would go along the ordinals till it found the right one and get it out.  When done with it, be sure to put it back into the crafting container.

This is what it should look like:
```R>l oil
A thick and syrupy substance that easily coats and lubricates metal.```

Holy oil looks like this:
```>l holy oil
You see nothing unusual.```

**Comment by BinuDR** [comment]
Actually, this was in the smith script, not forge.  Here's the code:

```  def check_oil(discipline)
    $ORDINALS.each do |ord|
      case bput("look my #{ord} oil in #{@container}", /thick and syrupy substance that easily coats and lubricates metal/, /You see nothing unusual/, /I could not find what you were referring to/, /There appears to be something written/, /(coal|lamp|fish) oil/, /The oil bottle is full/)
      when /thick and syrupy substance that easily coats and lubricates metal/
        return if ord == 'first'
        bput("get my #{ord} oil in #{@container}", /You get/)
        bput("put oil in my #{@container}", 'You put')
        return
      when /I could not find what you were referring to/
        break
      end
    end```

**Comment by MahtraDR** [comment]
Current version works well on my cleric. Errors of yesterday are gone. Check Binu's suggestion too?

**Comment by Raykyn55** [comment]
@BinuDR For the purposes of this PR, I think the current method accords with smith in either configuration. For smith, I'm going to comment on that PR (https://github.com/rpherbig/dr-scripts/pull/5864)

**Comment by MahtraDR** [comment]
Ran multiple iterations, didn't have a problem. Merging. We fix issues whenif we find them...

**Pull request merged**
