### PR TITLE
workorders.lic: Allow setting outfitting_tools: in your yaml so they …

### LINKED ISSUE #2821: Workorders should support repairing outfitting tools that aren't beltworn
I noticed that `;workorders tailoring repair` will only repair knitting tools or anything under `outfitting_belt`...
We should add in a setting for `outfitting_tools` so these can be repaired:

```yaml
outfitting_tools:   
- knitting needles  
- sewing needles    
- awl               
- scissors          
- stamp             
- hide scraper      
- slickstone        
- yardstick         
```

### PR DESCRIPTION
**Pull request by Sarvatt**
…get repaired

Fixes #2821

### CODE REVIEW

**Comment by jandersson** [comment]
<3

**Comment by Sarvatt** [comment]
figured this would break the least amount of people, suddenly adding default outfitting_tools: would break everyone relying on current behavior.

**Comment by rpherbig** [comment]
❓ Does this need an entry in `base-empty.yaml`?

**Comment by jandersson** [comment]
Adding it to base-empty means the || will always return the empty array

You could do something like `tools = (settings.outfitting_tools + settings.knitting_tools).uniq`

**Comment by Sarvatt** [comment]
Would you prefer populating the default tools for sewing or @jandersson's way?

**Pull request merged**
