### PR TITLE
Add held items to athletics

### PR DESCRIPTION
**Pull request by jayRyan24**
I did not use the equipment manage because I don't always want to list the item I'm using in equipment, my bolts and arrows, for example.

```
held_athletics_items:
  - bolts
  - arrows
```

```
held_athletics_items:
  - club
  - sword
```

### CODE REVIEW

**Comment by jayRyan24** [comment]
image

**Comment by rpherbig** [comment]
What happens if something is in your hands when the script starts?

**Comment by jayRyan24** [comment]
Then another script has really screwed up? I can just call `stow_hands`, but it seems like if that's going to be an issue, then you've already messed up somewhere else?

**Comment by rpherbig** [comment]
I guess that problem would have existed before these changes, too.

**Pull request merged**
