### PR TITLE
[scripts][dependency] Add messaging for forced script downloads

### PR DESCRIPTION
**Pull request by MahtraDR**
Adds messaging when scripts are force-checked, and adds the option to force-check all scripts.

Resolves https://github.com/rpherbig/dr-scripts/issues/6970

### CODE REVIEW

**Comment by Kiriawen** [comment]
usage would be `;eq force_refresh_scripts` ?

**Comment by MahtraDR** [comment]
> usage would be `;eq force_refresh_scripts` ?

There are two commands.

One - Force-gets all scripts (I am not sure we actually want this, we may only want it to CHECK all scripts, and get the ones that are out of date?)
```
;eq force_refresh_scripts
```
Two - force-gets one script
```
;eq get_script('script-name')
```

Note this should resolve https://github.com/rpherbig/dr-scripts/issues/6970 however we end up tuning it.

**Comment by Kiriawen** [comment]
yeah having it check for updates would be better than redownloading everything.  Save on bandwidth at least

**Comment by Kiriawen** [comment]
though having both a way to force a redownload of everything and a way to just check for updated files wouldn't be a bad idea either.

**Comment by MahtraDR** [comment]
> though having both a way to force a redownload of everything and a way to just check for updated files wouldn't be a bad idea either.

The way it works now, it'll check every file and redownload if they're out of date or don't exist. Is that good enough here?

**Comment by Kiriawen** [comment]
yep, that works.  That's what I was expecting.

**Pull request merged**
