### PR TITLE
[script] [equipmanager] Avoid infinite loop when fail to swap weapon to skill

### PR DESCRIPTION
**Pull request by KatoakDR**
### Background
* My character got stuck in an infinite loop in `combat-trainer` while it waited for my riste to be swapped to a particular skill but couldn't because my right hand was too injured.
* Although `hunting-buddy` watchdog mechanics were trying to exit the script due to my low health, it was hung waiting on `combat-trainer` to exit cleanly which was hung on `equipmanager` never able to swap riste to skill and stayed in an infinite loop.
* The swap to skill logic needs better boundaries to avoid infinite loops.

### Changes
* Avoid infinite loop if unable to swap weapon to skill (e.g. skill not supported or too injured or nothing in hand, etc).
* Fix bug where trying to swap to skill 'two-handed blunt' misinterpreted as 'two-handed edge'.
* Emphasize error if try to swap weapon to an unsupported skill.
* Skill to swap to can be expressed as the weapon type (e.g. light edged) or weapon skill (e.g. small edged)
* Remove import of `events` module since no more dependency on it.

## Tests
<details>
<summary>click to toggle</summary>

### should stop loop if can't swap to weapon type
```
> ,e echo EquipmentManager.new.swap_to_skill('riste', 'small blunt')

--- Lich: exec1 active.

[exec1]>swap my riste

You switch your riste so that you can use it as a two-handed blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy edged weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a two-handed blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy edged weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a two-handed blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy edged weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a two-handed blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy edged weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a two-handed blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy edged weapon.
> 
[exec1: false]

--- Lich: exec1 has exited.
```

### should stop loop if unable to swap weapon due to injury
```
!> ,e echo EquipmentManager.new.swap_to_skill('riste', 'heavy blunt')

--- Lich: exec1 active.

[exec1]>swap my riste

Your right hand is too injured to do that.
!> 
[exec1: false]

--- Lich: exec1 has exited.
```

### should swap to weapon skill if able (heavy blunt)
```
> ,e echo EquipmentManager.new.swap_to_skill('riste', 'heavy blunt')

--- Lich: exec1 active.

[exec1]>swap my riste

You switch your riste so that you can use it as a two-handed blunt weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a heavy blunt weapon.
> 
[exec1: true]

--- Lich: exec1 has exited.
```

### should swap to weapon skill if able (two-handed blunt)
```
,e echo EquipmentManager.new.swap_to_skill('riste', 'two-handed blunt')
--- Lich: exec1 active.

[exec1]>swap my riste

You switch your riste so that you can use it as a heavy edged weapon.
> 
[exec1]>swap my riste

You switch your riste so that you can use it as a two-handed blunt weapon.
> 
[exec1: true]

--- Lich: exec1 has exited.
```

### should open fan to use as small edged
```
> ,e echo EquipmentManager.new.swap_to_skill('fan', 'small edged')

--- Lich: exec1 active.

[exec1]>open my fan

With a practiced flick of your wrist, you snap open your avia fan to expose the sharpened edges at the end of the blades.
You switch your fan so that you can use it as a medium edged weapon.
> 
[exec1: true]

--- Lich: exec1 has exited.
```

### should close fan to use as blunt
```
> ,e echo EquipmentManager.new.swap_to_skill('fan', 'small blunt')

--- Lich: exec1 active.

[exec1]>close my fan

With a practiced flick of your wrist, you snap your avia fan closed, savoring the weight of the weapon in your fist.
You switch your fan so that you can use it as a medium blunt weapon.
> 
[exec1: true]

--- Lich: exec1 has exited.
```

### should warn and exit if try to swap to unsupported skill
```
,e echo EquipmentManager.new.swap_to_skill('riste', 'baseball')
--- Lich: exec1 active.

| Unsupported weapon swap: riste to baseball. Please report this to https://github.com/rpherbig/dr-scripts/issues

[exec1: false]

--- Lich: exec1 has exited.
```

### should swap throwing spike to weapon skill
```
[combat-trainer]>wield my throwing.spike

You draw out your throwing spike from the encompassing shadows, gripping it firmly in your left hand.
> 
[combat-trainer]>swap my spike

You switch your spike so that you can use it as a light thrown and light edged weapon.
> 
[combat-trainer]>feint left
```

### should stop loop if can't swap to weapon type due to paralysis
```
> ,e echo EquipmentManager.new.swap_to_skill('riste', 'he')

--- Lich: exec1 active.

[exec1]>swap my riste

Will alone cannot conquer the paralysis that has wracked your body.
> 
[exec1: false]

--- Lich: exec1 has exited.
```
</details>

### CODE REVIEW

**Comment by KatoakDR** [comment]
Recruiting testers, https://discord.com/channels/745675889622384681/745675890242879671/833395663974826007

**Comment by wstampley** [comment]
Is it safe to remove the dependency on events now? I don't see any more Flags referenced.

**Comment by KatoakDR** [comment]
> Is it safe to remove the dependency on events now? I don't see any more Flags referenced.

Good catch, I believe so, I'll take it out

**Comment by rpherbig** [comment]
Code changes look good ✔️ 

Let me know how the testing goes

**Comment by KatoakDR** [comment]
No testers responded to first request. Made second request, https://discord.com/channels/745675889622384681/745675890242879671/834996994669674528

Will give it a few days and if no one offers to do more testing than what I've offered then I say we move forward

**Comment by KatoakDR** [comment]
(logging comment as reminder to self to look into this)

Reported by [Xif](https://discord.com/channels/745675889622384681/745675890242879671/835211005238706217) in the Lich discord:

> Xif: same issue occurs w/ paralysis as well

To reproduce:

> Xif: can simulate by backfiring repeatedly until full paralysis then trying to swap

**Comment by KatoakDR** [comment]
@rpherbig This is ready for your review/merge, thanks. I just finished testing the paralysis bit per https://github.com/rpherbig/dr-scripts/pull/4903#issuecomment-825952313

**Pull request merged**
