### PR TITLE
Improve status monitor flexibility, setup framework for distance analysis

### PR DESCRIPTION
**Pull request by rcuhljr**
A simple change to trigger status monitor on high frequency arrival of unseen messages, even if they are not identical. Also set up for future change to use levenshtein(sp) distance to determine similarity of messages to make a more robust uniqueness filter. Also move settings to base.yaml for custom per player settings.

### CODE REVIEW

**Comment by rcuhljr** [comment]
Thanks I'll push a new version, I should really add in tests if I'm going to write stuff blind.

**Comment by Tarhish** [comment]
Awesome, that worked out.  So I think this is doing generally what you intended for it to do -- Appraising gear does a lot of semi-repeated messages that eventually trip the monitor.

```
[appraisal]>appraise gold.ring quick
The gold ring is obviously a specially made item.
You are certain that the ring's very nicely polished white gold is worth about 5,529 Dokoras, 7,662 Kronars, or 6,130 Lirums.
You guess that the ring's nicely facetted amethyst is probably worth around a few thousand Dokoras, a few thousand Kronars, or a few thousand Lirums.
It appears that the gold ring can be worn around the finger.
You are confident that the gold ring probably weighs a few tens of stones.
You are certain that the gold ring is worth exactly 29,766 Dokoras, 41,250 Kronars, or 33,000 Lirums.
You have no clear idea about who crafted the gold ring.
Roundtime: 5 seconds.
>
[appraisal]>stow my gold.ring
>
You put your ring in your leather haversack.
>
[appraisal]>remove my topaz.bracelet
Remove what?
>
[appraisal]>get my topaz.bracelet
You get a white topaz bracelet with a copper welkin clasp from inside your leather haversack.
>
[appraisal]>appraise topaz.bracelet quick
The topaz bracelet is obviously a specially made item.
You think it is likely that the bracelet's simply crafted copper is worth about 27 Dokoras, 37 Kronars, or 30 Lirums.
You believe that the bracelet's simply carved silver is worth exactly 505 Dokoras, 700 Kronars, or 560 Lirums.
You wonder if the bracelet's ineptly facetted topaz is worth about 4,654 Dokoras, 6,450 Kronars, or 5,160 Lirums.
It appears that the topaz bracelet can be worn on the wrist.
You believe that the topaz bracelet might weigh a few tens of stones.
You are certain that the topaz bracelet is worth exactly 9,020 Dokoras, 12,500 Kronars, or 10,000 Lirums.
Roundtime: 5 seconds.
>
[appraisal]>stow my topaz.bracelet
>
You put your bracelet in your leather haversack.
>
[appraisal]>remove my brigandine.balaclava
You take a covellite-alloy brigandine balaclava off your head.
>
[appraisal]>appraise brigandine.balaclava quick
The brigandine balaclava is brigandine armor.

The balaclava looks like it offers protection for the following areas:

    head
    neck
    right eye
    left eye

You feel certain that a covellite-alloy brigandine balaclava appears to impose light (3/15) maneuvering hindrance and fair (5/15) stealth hindrance, offering:
    good (5/15) protection and very high (10/18) damage absorption for puncture attacks.
    very good (6/15) protection and very high (10/18) damage absorption for slice attacks.
    very good (6/15) protection and very high (10/18) damage absorption for impact attacks.
    good (5/15) protection and very good (8/18) damage absorption for fire attacks.
    good (5/15) protection and very good (8/18) damage absorption for cold attacks.
    low (2/15) protection and low (3/18) damage absorption for electrical attacks.

If you were only wearing a covellite-alloy brigandine balaclava you could expect your maneuvering to be barely (1/14) hindered and your stealth to be lightly (4/14) hindered.

You are confident that the brigandine balaclava is of average construction (9/18), and is in pristine condition (98-100%).

The brigandine balaclava is made with metal.
The brigandine balaclava is a bit flexible.
You are certain that the brigandine balaclava weighs about 91 stones.
You are certain that the brigandine balaclava is worth exactly 8,398 Dokoras, 11,638 Kronars, or 9,311 Lirums.
Roundtime: 5 seconds.
>
Kithylan just arrived.
>
[status-monitor: ]
[status-monitor: ]
[status-monitor: ]
Kithylan runs east.
>
[status-monitor]>'Yes
You say, "Yes."
>
[status-monitor: You are confident that the gold ring probably weighs a few tens of stones.]
[appraisal]>wear my brigandine.balaclava
```

There are a lot of very similar lines repeated fairly often in there so I'm fiddling with the thresholds in base.yaml to see what feels right.  Mind clarifying what unique_line_threshold: is?

**Comment by Tarhish** [comment]
Yeah, I've been running status-monitor in the past to learn from what it sees -- I think it's absolutely amazing.   If I swap back to the old status-monitor I don't get any alerts when I do appraisals or 'exp all'.  If I swap the new changes in and do an 'exp all' I start getting alerts at the fourth line of ranks.  If I change line_frequency_threshold to 11 I start getting alerts at the 11th line of ranks.
```
Quillith:     Light Thrown:      1 00% clear          (0/34)    Heavy Thrown:     87 51% clear          (0/34)
Quillith:     Light Thrown:      1 00% clear          (0/34)    Heavy Thrown:     87 51% clear          (0/34)
Quillith:      Lunar Magic:    206 39% clear          (0/34)      Attunement:    170 60% clear          (0/34)
Quillith:      Lunar Magic:    206 39% clear          (0/34)      Attunement:    170 60% clear          (0/34)
Quillith:           Arcana:    180 34% clear          (0/34)  Targeted Magic:    119 36% clear          (0/34)
Quillith:           Arcana:    180 34% clear          (0/34)  Targeted Magic:    119 36% clear          (0/34)
Quillith:     Augmentation:    188 93% clear          (0/34)    Debilitation:     97 36% clear          (0/34)```

It does throw this stuff into seen_messages, but it will continue triggering pretty often on this stuff.

**Comment by Tarhish** [comment]
It might not need to increment the spam check counter if it's been less than a... I dunno, a second since the last time it did so?

**Comment by rcuhljr** [comment]
Good idea, although exp all output should be in the default ignore filter already, I might need to double check that.

**Comment by Sarvatt** [comment]
running rubocop and altering unrelated changes in a pr that takes this long really is a pita, note for future you :)

**Comment by rpherbig** [comment]
> running rubocop and altering unrelated changes in a pr that takes this long really is a pita, note for future you :)

I don't understand what you mean. Rubocop this morning didn't touch any of the files from this PR, right?

**Comment by Sarvatt** [comment]
this has been heavily tested over the months and its ready to merge.

**Comment by Tarhish** [comment]
I'm assuming that means you were running it?  I didn't keep testing it, to my shame.  My silence was negligence and not contentment.

**Comment by rpherbig** [comment]
@rcuhljr @Tarhish @Sarvatt This PR is nearing its first birthday. What's the status of it?

**Comment by Tarhish** [comment]
So I looked at this again and had better luck understanding it this time.  In this PR:
```
  def spam_check(line)
    @frequency_buffer << Time.now
    @frequency_buffer.delete_if{|x| (Time.now - x) > 60}
    if @frequency_buffer.size >= @line_frequency_threshold
      return spam_alert(line)
    end
```
since spam_check is called on every unseen line that passes the filter it means that as soon as it sees more than line_frequency_threshold unseen lines in a minute it will throw a spam_alert.  Since right now that's 6, it's triggering too often. If we had the distance analysis capability in then it'd be fine.

That said, this PR cleans up status-mon and lets you set the unique_line_threshold from 5 to something else if you want, so that's already an improvement.  The previous spam reporting works fine still, so I'd say it's fine to add if we bump up line_frequency_threshold to, I dunno, 25 seems to work out?

There's still the opportunity to implement the distance analysis side of this which would dramatically increase its capability.  I guess I'll look at that too.

**Comment by rcuhljr** [comment]
Actually this was made to lower the threshold, the motivation of this change was they started doing checks with fewer than 4 repeated lines to avoid this form of detection. I wouldn't raise the threshold to 25 without implementing the distance matching algorithm or you'll never detect anything.

**Comment by rcuhljr** [comment]
Er nevermind, thought we were talking about the other threshold. I still wouldn't go as high as 25, 10 is probably reasonable. That's an unidentified line every 6 seconds for a minute straight.

**Comment by rcuhljr** [comment]
Ok actually looked at the code again, 6 is probably still too high, this is new unique messages per minute, 3 or 4 seems right.

**Comment by Tarhish** [comment]
With line_frequency_threshold: 4 I'm getting ~6 spam alerts every minute over the last fifteen minutes and I'm not even in combat.  I added some of the common things to my base-filters, but there's still a lot of unique messages... admittedly a lot of it is because caravaning gives me a new random caravan every time, but I don't think it's the only system that's going to have that problem...

**Comment by Tarhish** [comment]
If we got this winnowed down to '4 unseen messages that are similar to each other in the same minute' then no problem, yeah.  But just '4 unseen messages in the same minute' seems to generate a lot of chaff.

**Comment by rcuhljr** [comment]
Perhaps caravan is particularly bad, I'm just going off my ranger messages where once I'd trained the thing unseen message spam like that was super rare.

**Comment by Tarhish** [comment]
Hmm, looking at this, a lot of these messages should have been migrated to the seen_messages by now.  I'm getting them again and again.  Could this...

```
@recent_seen = @recent_seen[1..10] if @recent_seen.length > 10
```
maybe be clipping away some of the things that need to be migrated over to seen messages?

**Comment by Tarhish** [comment]
No, sorry, recent_seen and recent_seen_lines are two different things.  I'll look more carefully.

**Comment by Tarhish** [comment]
Okay, I've always stopped and poked before letting it go on this long.  After about an hour a lot of the stuff has been migrated over and it's quieted down a fair bit.  I'll keep running it in other contexts and come up with a few things to add to base-filters.

**Comment by rpherbig** [comment]
Looks good to me. @rcuhljr ?

**Pull request merged**
