### PR TITLE
[script] [healme] Mitigate death by scars

### PR DESCRIPTION
**Pull request by KatoakDR**
_(description revised April 12th)_

### Background
* The current version of `healme` prioritizes wounds based on their wound severity only.
* Accumulation of too many wounds and/or scars to critical body parts can lead to death, despite your vitality level.
* "Scar death" occurs when a critical body part obtains a scar of max damage.
* Healing a wound will create (or increase the severity of) a scar to the same body part and location.

### Changes
* Detect if a body part has both a wound and a scar, and if their combined severities are greater than 10 (out of 13) then prioritize the scar first to mitigate scar death.
* Don't waste time casting heal over time spells (Heal/Regenerate) if you don't have any wounds. This allows you to more quickly get to casting Flush Poisons or Cure Disease if that's why you're healing yourself.
* Code style: rename `$debug_mode_hm` to `$debug_mode_healme`

### increase scar severity to mitigate scar death
```
[healme: Found an external scar on your chest, checking for a related wound that could cause scar death if healed]
[healme: Checking if exists an external wound on your chest]
[healme: Found #<DRCH::Wound:0x084a7898 @body_part=chest, @severity=6, @bleeding_rate=nil, @is_internal=false, @is_scar=false>]
[healme: Setting the scar severity to 7 to prioritize healing it before the non-scar wound]
```

### start with heal over time if have wounds
```
[healme]>health

Your body feels at full strength.
Your spirit feels full of life.
You are strangely full of extra energy.
You have a few nearly invisible scars along the head, some tiny scratches to the right arm, some tiny scars across the right arm, some minor abrasions to the left arm, a few nearly invisible scars along the left arm, some minor abrasions to the right leg, a few nearly invisible scars along the right leg, an occasional twitching in the chest area, a few nearly invisible scars along the abdomen.
You have a dangerously strong nerve poison.

> 
[healme]>release mana

You aren't harnessing any mana.
> 
[healme]>prep heal 15

With meditative movements you prepare your body for the Heal spell.
```

### skip heal over time spells if no wounds but still poisoned/diseased
```
[healme]>health

> 
Your body feels at full strength.
Your spirit feels full of life.
You are strangely full of extra energy.
You have a dangerously strong nerve poison.

> 
[healme]>release mana

You aren't harnessing any mana.
> 
[healme]>prep FP 15

With meditative movements you prepare your body for the Flush Poisons spell.
```

### CODE REVIEW

**Comment by KatoakDR** [comment]
FYI @wstampley, would like your thoughts on this healme algorithm to prioritize critical body parts as well as reducing scars. Thanks

**Comment by wstampley** [comment]
> FYI @wstampley, would like your thoughts on this healme algorithm to prioritize critical body parts as well as reducing scars. Thanks

@KatoakDR - I like the general shape of things. I honestly forgot this wasn't already in there.

### Location Weighting 

I'm not sure the positional percentages buy you anything more than a fixed severity modifier on the location (of like... 1 or .5 for 'kills you if it breaks' or 'you can lose this just fine'). I think I would look at it like... a 4 to the head vs. what to the legs would make me want to do the leg first? 4 vs. 9 probably, but not 4 v 6? and try to pick weights by that. 

This pretty much comes out to what you have.  However, there is some weirdness when you hit the boundaries in your list (i.e. the delta between left hand and right arm isn't that much (1/13), so you'd pick hand if you were the same, but probably arm if it was one or two higher?

### Particular Location Severities

I didn't think eyes were critical? The rest of this makes sense to me.

### Wounds vs. Scars

Again, I like the shape of this, but I think you might be better served by only healing scars if wound + scar at a location >= some combined severity. Otherwise you're potentially wasting cycles healing scars only to create more scars (that wouldn't have killed you) when you heal the wound there. i.e. 3 wound + 3 scar is safe to heal the wound then the scar. 11 wound + 5 scar is probably not, but a 1.3 multiplier wouldn't catch it. A location with 0 wound and 10 scar, the scar isn't going to get worse, so triaging should focus on bleeds / etc.

Now, to handle things this way, you would almost have to have a whole separate set of logic that looks for wound + scar pairs in  locations that can kill you - and deal with those scars first, instead of being able to weight them into the main list through pure math.

**Comment by KatoakDR** [comment]
> I like the general shape of things. I honestly forgot this wasn't already in there.

Thanks for the insightful feedback. Good ideas to iterate on. I, too, forgot that body party prioritization wasn't in the great refactor 😮

**Comment by wstampley** [comment]
Unrelated to your current goal for this PR, it might be nice if healme dropped regen (only if it cast regen) at the end. I could also be convinced that this isn't really healme's job, and that I just need to add release_cyclics to my t2.

**Comment by KatoakDR** [comment]
> I just need to add release_cyclics to my t2

Is it possible to have more than one cyclic spell active at a time? If not, then I agree that `healme` could stop the regenerate cyclic if it starts it.

If there could be more than one cyclic active, then we'd not want to stop the other spells.

If stopping regenerate is as simple as `release regenerate` where we can explicitly pick which spell to drop, that'd be good, too.

I don't have that cyclic spell to test with -- thoughts?

**Comment by wstampley** [comment]
> > I just need to add release_cyclics to my t2
> 
> Is it possible to have more than one cyclic spell active at a time? If not, then I agree that `healme` could stop the regenerate cyclic if it starts it.
> 
> If there could be more than one cyclic active, then we'd not want to stop the other spells.
> 
> If stopping regenerate is as simple as `release regenerate` where we can explicitly pick which spell to drop, that'd be good, too.
> 
> I don't have that cyclic spell to test with -- thoughts?

```
> prep regen 5
With tense movements you prepare your body for the Regenerate spell.
> 
You feel fully prepared to cast your spell.
> cast
You gesture.
Rutilant sparks of light encircle you, bathing you in a warm glow as your body begins to tingle with energy.
> release regen
> 
The tingling across your body diminishes as you feel the motes of energy fade away.
> prep gs 5
With tense movements you prepare your body for the Guardian Spirit spell.
> 
You feel fully attuned to the mana streams again.
> 
You feel fully prepared to cast your spell.
> cast
Your heart skips a beat as your spell sends a subtle jingling call outward from you in all directions.
> release regen
Release what?
[Check RELEASE HELP for more information.]
> 
A sedate alfar warrior calmly strides in and surveys the area.
```

**Comment by KatoakDR** [comment]
> release regen
> > 
> The tingling across your body diminishes as you feel the motes of energy fade away.
> ...
> A sedate alfar warrior calmly strides in and surveys the area.

I'm assuming that means we can just add `release regenerate` when `healme` exits --- but I'm wondering, what if the player wanted regenerate up, then ran healme, and then afterwards still wanted regenerate up? Maybe it should be a setting or just leave it to people to manage on their own?

**Comment by KatoakDR** [comment]
> I didn't think eyes were critical?

You're right, I'm just so used to associating head/neck/eyes with armor I figured they were critical too. I reviewed [the conversation](https://discord.com/channels/745675889622384681/745678251250417674/820796297115205632) I was having with Kiriawen back on March 14th and her suggested order is `head, neck, chest, abdomen, back, eyes, nerves, hands, arms, legs`.

Unless eyes _are_ critical to life or spell casting, which I don't think they are... maybe eyes should be lower in the list, perhaps after skin/nerves/hands, which are important to spell casting.

I'll update the `$DRCH_BODY_PARTS_IN_CRITICAL_ORDER` array to be:

```ruby
$DRCH_BODY_PARTS_IN_CRITICAL_ORDER = [
    # Most critical
    'head',
    'neck',
    'chest',
    'abdomen',
    'back',
    # Hinder spell casting
    'nerves',
    'skin',
    'right hand',
    'left hand',
    # Least critical
    'right eye',
    'left eye',
    'right arm',
    'left arm',
    'right leg',
    'left leg'
  ]
```

**Comment by KatoakDR** [comment]
> I'm not sure the positional percentages buy you anything more than a fixed severity modifier on the location

Good observation. I've simplified the equation to just multiply your wound severity by (15 - index in body part array).

> Again, I like the shape of this, but I think you might be better served by only healing scars if wound + scar at a location >= some combined severity. Otherwise you're potentially wasting cycles healing scars only to create more scars (that wouldn't have killed you) when you heal the wound there. i.e. 3 wound + 3 scar is safe to heal the wound then the scar. 11 wound + 5 scar is probably not, but a 1.3 multiplier wouldn't catch it. A location with 0 wound and 10 scar, the scar isn't going to get worse, so triaging should focus on bleeds / etc.
> 
> Now, to handle things this way, you would almost have to have a whole separate set of logic that looks for wound + scar pairs in locations that can kill you - and deal with those scars first, instead of being able to weight them into the main list through pure math.

I agree, thanks. I've removed the scar modifier from the equation for now in favor of the above.

As of commit https://github.com/rpherbig/dr-scripts/pull/4852/commits/63303372ebdca3ae95b62d885ed81e328b5901b8 the equation force ranks wounds/scars based on their body part x wound/scar severity. Wounds and scars are treated equally. Next pass at this will be to then group the ranked results by body part and decide which needs to be healed first: the wound or the scar for THAT body part. After that, then the entire list of wounds would be listed in triage order of how to heal and minimize scar build up.

**Comment by wstampley** [comment]
```
--- Lich: go2 has exited.

--- Lich: healme active.

[healme]>perceive health self

You close your eyes, centering your thoughts on your own life essence and drawing out the truth of your own injuries.

Roundtime: 5 sec.
R> 
[healme]>health

Your body feels at full strength.
Your spirit feels full of life.
You are strangely full of extra energy.
You have a dangerously poisoned right leg.

> 
[healme]>release mana

You aren't harnessing any mana.
> 
[healme]>prep regenerate 5

> 
With tense movements you prepare your body for the Regenerate spell.
```

Weird edge case, poison only, no wounds/bleeds, and it still puts up heal and regen. Wonder if we want a wound check before putting up the HoT spells?

**Comment by KatoakDR** [comment]
> Weird edge case, poison only, no wounds/bleeds, and it still puts up heal and regen. Wonder if we want a wound check before putting up the HoT spells?

Yep, good catch, thanks. I've submitted that change per https://github.com/rpherbig/dr-scripts/pull/4852/commits/bf057de1c77534b4f8748841c126813db3934a8d

## Tests

### start with heal over time if have wounds
```
[healme]>health

Your body feels at full strength.
Your spirit feels full of life.
You are strangely full of extra energy.
You have a few nearly invisible scars along the head, some tiny scratches to the right arm, some tiny scars across the right arm, some minor abrasions to the left arm, a few nearly invisible scars along the left arm, some minor abrasions to the right leg, a few nearly invisible scars along the right leg, an occasional twitching in the chest area, a few nearly invisible scars along the abdomen.
You have a dangerously strong nerve poison.

> 
[healme]>release mana

You aren't harnessing any mana.
> 
[healme]>prep heal 15

With meditative movements you prepare your body for the Heal spell.
```

### skip heal over time spells if no wounds but still poisoned/diseased
```
[healme]>health

> 
Your body feels at full strength.
Your spirit feels full of life.
You are strangely full of extra energy.
You have a dangerously strong nerve poison.

> 
[healme]>release mana

You aren't harnessing any mana.
> 
[healme]>prep FP 15

With meditative movements you prepare your body for the Flush Poisons spell.
```

**Comment by KatoakDR** [comment]
Converted back to draft, @wstampley and I are still working out the algorithm for prioritizing wounds/body parts

**Comment by KatoakDR** [comment]
@wstampley Per our conversations, I've updated the priority algorithm to only focus on mitigating scar death then healing by wound severity, regardless the body part. This is ready for your review, thanks.

This keeps `healme` focused on two key goals:
1. Keep you alive
2. Whenever possible, always reduce severity of the worst wound

**Comment by wstampley** [comment]
> @wstampley Per our conversations, I've updated the priority algorithm to only focus on mitigating scar death then healing by wound severity, regardless the body part. This is ready for your review, thanks.
> 
> This keeps `healme` focused on two key goals:
> 
> 1. Keep you alive
> 2. Whenever possible, always reduce severity of the worst wound

@KatoakDR  - Thanks for all the work on this. It looks great to me. I'll switch over to this version and run it for a bit and see what happens.

**Comment by KatoakDR** [comment]
> I'll switch over to this version and run it for a bit and see what happens.

@wstampley have you had a chance to test this version of healme?

**Comment by wstampley** [comment]
I used it a bit, and then I broke it by switching back to my custom common-healing that doesn't have the utility methods. I'll merge them together and test more tomorrow.

**Comment by wstampley** [comment]
I haven't had any issues with it. I don't know for sure that I've been in a situation where scar death would have killed me and it didn't.

**Comment by KatoakDR** [comment]
@wstampley Thanks for testing 👍 

@rpherbig This is ready for your review, thanks

**Pull request merged**
