### PR TITLE
fix up a rubocop warning with have_holy_water.

### PR DESCRIPTION
**Pull request by Sarvatt**
theurgy.lic:250:7: C: Rename have_holy_water? to holy_water?.

### CODE REVIEW

**Comment by rpherbig** [comment]
Are you prepared to play tech support on LNet when theurgy breaks because it was updated out of sync with common?

**Comment by Sarvatt** [comment]
holy_water? in both scripts are self contained?

**Comment by Sarvatt** [comment]
but yeah, always on tech support duty :)

**Comment by rpherbig** [comment]
Sorry, you updated `commune`, I thought it said `common`. You're fine.

**Pull request merged**
