### PR TITLE
drinfomon.lic: Make DRRooms.pcs work for heritage house cantrip users.

### PR DESCRIPTION
**Pull request by Sarvatt**
This should cover all of the ones on https://elanthipedia.play.net/Veiled_Identity now.

Crannach whose body glows with starlight

;en echo DRRoom.pcs
--- Lich: exec1 active.
[exec1: ["starlight", "Yndass"]]
--- Lich: exec1 has exited.

### CODE REVIEW

**Comment by Sarvatt** [comment]
Would `.map { |obj| obj.sub(/ who(se body|) (has|is|appears|glows) .+/, '').sub(/ \(.+\)/, '') }` be better?

**Comment by jandersson** [comment]
What you have makes sense to me.  I think it comes down to whatever you prefer

**Comment by Sarvatt** [comment]
whoops, didn't actually commit what I meant to, fixed now.

**Comment by Dartellum** [comment]
Does this work with my effect from the Gold button?

**Comment by Sarvatt** [comment]
we went over it on slack, his button already works :)

**Comment by Dartellum** [comment]
I am good with this. :+1:

**Pull request merged**
