### PR TITLE
Exchange slack token

### PR DESCRIPTION
**Pull request by jandersson**
Lichbots can store the tokens in their uservars. When a person runs status-mon and doesn't have a token in their uservars (or has a bad token), it will query the listed lichbots for the token. If the token auths, we set the token. We send a success message on first time setup

### CODE REVIEW

**Comment by jandersson** [comment]
I'll generate a new token to distribute if this gets merged

**Comment by rpherbig** [comment]
I'm having trouble getting the http gem installed. Did you do anything beyond `gem install http`?

**Comment by jandersson** [comment]
Don't think so, is net/http the same as http?

**Comment by jandersson** [comment]
No it isn't my mistake. Ill write a post method with net/http

**Comment by rpherbig** [comment]
Let me know what the new token is and I'll load it into Roobeelitch.

**Pull request merged**
