### PR TITLE
New trader profile - Quillith-setup

### PR DESCRIPTION
**Pull request by Tarhish**
Submitting my profile to the repository.  Further changes to trader stuff will be updated here too.

### CODE REVIEW

**Comment by rpherbig** [comment]
Unit test failure:
```
  1) Failure:
TestValidYaml#test_all_settings_in_base_yaml [/home/travis/build/rpherbig/dr-scripts/test/test_valid_yaml.rb:32]:
Expected all settings to be in base.yaml.
--- expected
+++ actual
@@ -1 +1 @@
-["picking_pet_boxes_on_hand", "forage_container", "store_tools", "tinkering_tools", "finesse_buff", "crafting_buffs", "starlight_buffs", "gathering_buffs", "sorcery_buffs", "buffs"]
+[]
```

Since you have some non-standard settings, could you add this character to https://github.com/rpherbig/dr-scripts/blob/master/test/test_valid_yaml.rb#L19 ?

**Comment by Tarhish** [comment]
Interesting, I had no clue this was a thing.  I'll have to look at these tests.  If it were just this I'd just remove the custom settings and submit as is, but I expect there'll be more later.

**Comment by rpherbig** [comment]
If you are planning on using this as an example for others, you may want to
add comments saying those settings are non standard, to avoid confusion

**Comment by jandersson** [comment]
Add yourself to this array to be excluded from the test. 

https://github.com/rpherbig/dr-scripts/blob/master/test/test_valid_yaml.rb#L19

**Comment by Sarvatt** [comment]
this looks good to go

**Pull request merged**
