### PR TITLE
Changed the echo's in hunting-buddy to messages.

### PR DESCRIPTION
**Pull request by jayRyan24**
This is a good place for it as these need to stand out in the clutter.

### CODE REVIEW

**Comment by jayRyan24** [comment]
Should be merged after: #3873

**Comment by jayRyan24** [comment]
image

**Comment by jayRyan24** [comment]
image

**Comment by jayRyan24** [comment]
image

**Comment by rpherbig** [comment]
✔️ Looks good to me. Remind me to merge it in a few days.

**Pull request merged**
