### PR TITLE
Fixing the safe-room force issues.

### PR DESCRIPTION
**Pull request by jayRyan24**
Adding in the previous force logic as well as the new option skip and then force that necros and empaths can use.

### CODE REVIEW

**Comment by rcuhljr** [comment]
It needs testing, but I think this is all you should need.
```
 arg_definitions = [
      [
        { name: 'skip', regex: /(s|skip)/i, optional:true, description: 'Skip running to the safe room, useful for Empaths and Necros.' },
        { name: 'force', regex: /force/i, optional: true, description: 'Run healing logic even if there are no visible wounds.' }
      ]
    ]
```

**Comment by jayRyan24** [comment]
I've done dual optional thing, and it wouldn't work.

**Comment by jayRyan24** [comment]
This might work though, I'll test this tonight. 

```
 arg_definitions = [
      [
        { name: 'skip', regex: /(s|skip)/i, optional:true, description: 'Skip running to the safe room, useful for Empaths and Necros.' },
        { name: 'force', regex: /force/i, optional: true, description: 'Run healing logic even if there are no visible wounds.' }
      ], []
    ]
```

**Comment by rcuhljr** [comment]
Are you sure you weren't trying it with flex args enabled? those might mess with it but they shouldn't. I don't see any reason all optional args won't work.

**Comment by jayRyan24** [comment]
I'll try again tonight, but I've had issues with using full optionals. I think it happened last in the paladin quest walkthrough script, don't remember the exact conditions.

**Comment by jayRyan24** [comment]
OK, so my issues before were the separated settings

```
[
  setting one optional
],
[
  setting two optional
]
```
thanks for the help.

**Pull request merged**
