### PR TITLE
add support for special inventory items that transform into weapons

### PR DESCRIPTION
**Pull request by jandersson**
#539 
Here's what I got so far. Let me know what the good, bad, and ugly is.

### CODE REVIEW

**Comment by jandersson** [comment]
Wielding example 

```
[Type INVENTORY HELP for more options]
>
[combat-trainer: removing unmatched items between these two sets]
[combat-trainer: some battered black leather gloves,a small gryphon-pelt shield sealed with protective wax,a polished steel parry stick,some black leather armor reinforced with slender iron banding,a composite bow]
[combat-trainer: black.armor,battered.gloves,composite.bow,parry.stick,small.shield]
[combat-trainer: wearing missing items between these two sets]
[combat-trainer: some battered black leather gloves,a small gryphon-pelt shield sealed with protective wax,a polished steel parry stick,some black leather armor reinforced with slender iron banding,a composite bow]
[combat-trainer: black.armor,battered.gloves,composite.bow,parry.stick,small.shield]
>
[combat-trainer: action count: 0 vs 10]
[combat-trainer: skill exp: 0 vs -1]
[combat-trainer: new skill needed for training]
[combat-trainer: checking weapons as nil!=Heavy Thrown]
[combat-trainer]>remove my tailband
You remove a polished steel tailband with serrated edges from your tail.
>
[combat-trainer]>turn my tailband
With a flick of your thumb, you spin your steel tailband into the air.  As it starts its downward spiral toward you, the steel tailband suddenly explodes into a fine mist, expanding into a polished steel katavdar with serrated edges as it settles into your palm.
>
[combat-trainer]>stance set 100 80 0
Setting your Evasion stance to 100%, your Parry stance to 80%, and your Shield stance to 0%.  You have 0 stance points left.
>
[combat-trainer: Selected: Hunt]
[combat-trainer]>hunt
```

**Comment by jandersson** [comment]
Sheathing

```
combat-trainer: ***Fatigue: 90***]
[combat-trainer: ***Target: 90***]
[combat-trainer]>lob
< Moving fluidly, you lob a polished steel katavdar with serrated edges at a rock troll.  A rock troll attempts to evade, receiving a glancing blow.  The katavdar lands a good hit (2/23) to the troll's right arm.
The steel katavdar falls to the ground!
[You're winded, nimbly balanced with no advantage.]
[Roundtime 3 sec.]
R>
A rock troll gestures at you.
The earth beneath your feet begins to shake violently!
The troll laughs monstrously and chants, "Acz aer sha'hhn!"  Suddenly, the ground begins to shake, the very rocks shuddering beneath the mystical might of the troll's words!

You manage to remain upright!
>
[combat-trainer]>get my steel katavdar
You pick up the katavdar lying at your feet.
>
[combat-trainer: action count: 7 vs 10]
[combat-trainer: skill exp: 10 vs 10]
[combat-trainer: new skill needed for training]
[combat-trainer: checking weapons as "Heavy Thrown"!=Brawling]
[combat-trainer]>turn my katavdar
With a flick of your thumb and a turn of your wrist, the katavdar trembles then shrinks, settling into your palm as a polished steel tailband with serrated edges.
>
[combat-trainer]>wear my tailband
>
* In a weak and directionless display of aggression, a rock troll feints to the side at you.  You evade, leaping aside like a cunning cat.  
[You're winded, nimbly balanced and opponent has slight advantage.]
>
You attach a polished steel tailband with serrated edges to your tail.
>
[combat-trainer: ***Fatigue: 88***]
[combat-trainer: ***Target: 90***]
```

**Comment by jandersson** [comment]
And the YAML
```
gear:
- :name: katavdar
  :is_leather: false
  :is_worn: false
  :transforms_to: tailband
  :transform_verb: turn
  :transform_text: With a flick
- :name: tailband
  :is_worn: true
  :transforms_to: katavdar
  :transform_verb: turn
  :transform_text: With a flick of your thumb and a turn of your wrist, the katavdar trembles then shrinks, settling into your palm as a polished steel tailband with serrated edges.
```

**Comment by rpherbig** [comment]
Thank you for the pull request. @rcuhljr or I will try to look at it soon, but we're both traveling for business until Thursday, so there may be some delays.

**Comment by jandersson** [comment]
Thanks. I realize these are pretty esoteric items, so i will try and dig up some others in the meantime.

**Comment by rpherbig** [comment]
The code looks fine to me. I'd be ok merging this and revisiting it once we
have more transform items with which to test.

@rcuhljr , ok to merge?

**Comment by rpherbig** [comment]
@jandersson Would you be up for contributing your character's YAML to our repo so we can point at an example of transform being used?

**Comment by rcuhljr** [comment]
Or alternatively put a sample somewhere, maybe the e-pedia wiki?

**Comment by jandersson** [comment]
Yea I can do both, I'll let you guys decide whats best.

I'll put the info i collect here: [https://elanthipedia.play.net/mediawiki/index.php/User:ARCHIMEDIAN/Notes](url)

Here's the YAML 
[Masah-setup.yaml.zip](https://github.com/rpherbig/dr-scripts/files/382027/Masah-setup.yaml.zip)

**Comment by rpherbig** [comment]
Let's do both

**Pull request merged**
