### PR TITLE
afk.lic - deal with hand objects and climbing

### PR DESCRIPTION
**Pull request by BinuDR**
There is an issue with the cliff at asketi's mount where it will try to climb the cliff but will fail because something's in the hands, and then it just keeps trying and failing.  This addresses that.

### CODE REVIEW

**Comment by jandersson** [comment]
I feel like this belongs in common-travel::walk_to https://github.com/rpherbig/dr-scripts/blob/master/common-travel.lic#L11

**Comment by BinuDR** [comment]
It needs to be part of go2 really.  The items in hand or at feet issue effect go2, and by extension walk_to.

If we fix go2 it'll take care of walk_to on its own.

When I have some time to dig into go2 more deeply, I'll see if I can fix it up in there.

**Comment by jandersson** [comment]
Its a solution to a travel related problem in a script to handle afk problems. Its adding a weird dependency.

**Comment by BinuDR** [comment]
I agree.  I didn't like the at feet stuff being handled in afk either.  We'll put it on the to do list to move these things to go2.

**Comment by BinuDR** [comment]
And while we're tinkering with go2, let's add the ability to have it release spells that get you in trouble in towns.

**Comment by jandersson** [comment]
It doesn't belong in afk.

**Comment by jandersson** [comment]
walk_to is meant to handle travel related problems that go2 does not address. this would be where the handling of at feet items should probably be as well. i am trying to push against adding more things to afk as a catchall.

**Comment by rpherbig** [comment]
I dislike this being in `afk`, but if we need it, we need it. I hope someone can look into a better solution, though.

**Pull request merged**
