### PR TITLE
[scripts] [common-theurgy] passing settings to quick_bless_item

### PR DESCRIPTION
**Pull request by MahtraDR**
Nothing uses this yet, and mostly because it doesn't work as is. 

https://github.com/rpherbig/dr-scripts/pull/5624 depends on this.

### CODE REVIEW

**Comment by rpherbig** [comment]
https://github.com/rpherbig/dr-scripts/blob/effe663e6ac2ff3d28fd554c37d3e7a8ba1dde8f/common-theurgy.lic#L110 appears to use it, why doesn't it work?

**Comment by MahtraDR** [comment]
> https://github.com/rpherbig/dr-scripts/blob/effe663e6ac2ff3d28fd554c37d3e7a8ba1dde8f/common-theurgy.lic#L110
> 
> appears to use it, why doesn't it work?

Plausibly user error on my part. I'll check again.

**Comment by MahtraDR** [comment]
ok, I don't think this is user error on my part.

as is:
```
>;e echo DRCTH.quick_bless_item('wine')                                                                                                                                                                                                       
--- Lich: exec1 active.                                                                                                                                                                                                                       
[exec1: ]                                                                                                                                                                                                                                     
--- Lich: exec1 has exited.   
```
passing `{}` 
```
>;e echo DRCTH.quick_bless_item('wine',{})                                                                                                                                                                                                    
--- Lich: exec1 active.                                                                                                                                                                                                                       
[exec1]>release mana                                                                                                                                                                                                                          
You aren't harnessing any mana.                                                                                                                                                                                                               
[exec1]>prep bless 1                                                                                                                                                                                                                          
You begin chanting a mantra to invoke the Bless spell.                                                                                                                                                                                        
>                                                                                                                                                                                                                                             
--- Exception: undefined method `cambrinth_items' for {}:Hash                                                                                                                                                                                 
common-arcana:647:in `cast_spell'                                                                                                                                                                                                             
--- Lich: exec1 has exited.          
```

passing `get_settings`
```
>;e echo DRCTH.quick_bless_item('wine',get_settings)                                                                                                                                                                                          
--- Lich: exec1 active.                                                                                                                                                                                                                       
[exec1]>release spell                                                                                                                                                                                                                         
You let your concentration lapse and feel the spell's energies dissipate.                                                                                                                                                                     
[exec1]>release mana                                                                                                                                                                                                                          
You aren't harnessing any mana.                                                                                                                                                                                                               
[exec1]>prep bless 1                                                                                                                                                                                                                          
You should stop playing before you do that.                                                                                                                                                                                                   
[exec1]>stop play                                                                                                                                                                                                                             
[exec1]>prep bless 1                                                                                                                                                                                                                          
You stop playing your song.                                                                                                                                                                                                                   
>                                                                                                                                                                                                                                             
You begin chanting a mantra to invoke the Bless spell.                                                                                                                                                                                        
[exec1]>cast my wine                                                                                                                                                                                                                          
>                                                                                                                                                                                                                                             
You gesture at some deep red wine.                                                                                                                                                                                                            
A brilliant silver glow surrounds some deep red wine for a few moments, but nothing else seems to happen.                                                                                                                                     
>                                                                                                                                                                                                                                             
[exec1: true]                                                                                                                                                                                                                                 
--- Lich: exec1 has exited.          
```

**Comment by MahtraDR** [comment]
In addition to the spell casting not working from a purely DRCA perspective, the known spells check was also failing, since `@known_spells.include?('Bless')` doesn't return true here.

**Comment by MahtraDR** [comment]
I'm not sure this feels quite right. By and large only theurgy uses most of these functions. Do we really need them in common-theurgy? It's a lot simpler if they're in theurgy proper.

**Pull request closed without merging**
