### PR TITLE
workorders.lic - removed knitting tools

### PR DESCRIPTION
**Pull request by BinuDR**
knitting_tools: was removed from base.  Removed it from workorders

### CODE REVIEW

**Comment by rpherbig** [comment]
We'll let this PR sit for a few days to make sure everyone using the old setting has had time to migrate over. Can you ping me if I haven't merged it by then?

**Comment by BinuDR** [comment]
I made this because people are getting an error if they hadn't ever defined knitting_tools in their yaml.  It gives an error about trying to add to a nil class.

**Comment by rpherbig** [comment]
Ah, gotcha! I'll merge it now then

**Comment by Sarvatt** [comment]
ahh I didn't realize this would be a problem, now that base has changed it really should be pulled.

**Comment by rpherbig** [comment]
Thanks @BinuDR

**Comment by Sarvatt** [comment]
sorry about that and thanks for catching it

**Comment by BinuDR** [comment]
Thanks

**Pull request merged**
