### PR TITLE
[script][inventory-manager] support for shadow servants

### PR DESCRIPTION
**Pull request by GreyhallowDR**
added an arg 'servant', casts PG on servant 
checks DRStats for guild
confirms successful PG cast on servant
sorry about the spacing

### CODE REVIEW

**Comment by mwest152** [comment]
I've been running this version, so i dont know if this is related to this or the original version, but I am having this issue:

```
R> ,inv search gold
--- Lich: inventory-manager active.
Checking Giulietta:
Match 1): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 2): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 3): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 4): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 5): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 6): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 7): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 8): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 9): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 10): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 11): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 12): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 13): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 14): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 15): an effervescent eddy of honey-hued light captured by a sungold frame (worn)
Match 16): an effervescent eddy of honey-hued light captured by a sungold frame (worn)

```
and it goes on to about 60+ matches and also does it for 4 other characters with the same eddy.

**Comment by Kiriawen** [comment]
@MahtraDR @GreyhallowDR 
Is this still in progress or ready for review?  If you don't intend to carry on with it please close out the PR.

Thanks!

**Comment by mwest152** [comment]
[inventory-manager.txt](https://github.com/rpherbig/dr-scripts/files/13733931/inventory-manager.txt)

Scrounger worked out the bugs on this for me, but its inventory manager and works with shadow servants.  Also will rummage your shelf in a vault.  I dont have premie or a family vault to test that functionality.  Also i really don't know how to do pull requests or I would have tried to put this script up myself.

**Comment by MahtraDR** [comment]
Closing this since it's been incorporated into https://github.com/rpherbig/dr-scripts/pull/6831

**Pull request closed without merging**
