### PR TITLE
titlecheck.lic - added arguments to optionally list ALL titles and/or SORT them

### PR DESCRIPTION
**Pull request by mikejcook**
I found that parsing the standard title output was challenging and wanted to see titles in a nice list. titlecheck provided that functionality, but only for titles new since the last run. I added some simple arguments that bypass checking the existing list and optionally sort the titles alphabetically.

### CODE REVIEW

**Comment by Dartellum** [comment]
I will grab these changes and give them a go.

**Comment by Dartellum** [comment]
Okay, works. However, alphabetical sorting removes the progression of titles. Yes, the blob output is hard to read and I like the list. Perhaps make the list display as in the original order and offer the sort.

**Comment by mikejcook** [comment]
I'm not sure what you mean. Sorting only happens when you use the sort argument. Without that argument, it'll display in the original, progression order.

Without any additional arguments, it's functionally identical to the original titlecheck

With all, it'll list all titles, regardless of what you've viewed previously

With sort, it'll list the titles sorted alphabetically, whether viewing only new titles or all

**Comment by Dartellum** [comment]
> I'm not sure what you mean. Sorting only happens when you use the sort argument. Without that argument, it'll display in the original, progression order.
> 
> Without any additional arguments, it's functionally identical to the original titlecheck
> 
> With all, it'll list all titles, regardless of what you've viewed previously
> 
> With sort, it'll list the titles sorted alphabetically, whether viewing only new titles or all

What I am saying is I like the list format you did when you pass sort in but I would like it to list it that way without sorting as well (optional, of course). The blob from the original is overwhelming sometimes. :smile:

**Comment by mikejcook** [comment]
Well, the list format was part of titlecheck originally. I just added the all and sort arguments.

So if you do ;titlecheck <cat> or ;titlecheck<cat> all, you should see what you are asking for? It'll put it in a list format, but without the sort. Just don't pass in the sort argument.

**Review by Dartellum — APPROVED** [review]

**Pull request merged**
