### PR TITLE
Slackbot Without Slack Gem

### PR DESCRIPTION
**Pull request by jandersson**
I removed the slack gem from this class and instead used http and json. I also obfuscated the token, Slack seems to crawl github and invalidates any tokens it finds. So this also includes the new token.

### CODE REVIEW

**Comment by rpherbig** [comment]
What do you think about putting the token in a UserVar (or whatever the account-wide version of that is)?

**Comment by jandersson** [comment]
Do you mean to store it there instead of anywhere in the script itself? So remove lines 7-9?

**Comment by rpherbig** [comment]
Correct. The obfuscation is there to work around something that Slack has good reason to check for. Anyone could grab that token and impersonate you in the Slack team with it, right?

**Comment by jandersson** [comment]
Yep, they could impersonate the bot I think is the implication

**Comment by jandersson** [comment]
Im wondering how to communicate the token to the user so that it can be stored in a uservar

**Comment by rcuhljr** [comment]
Except anyone you give the token to in game can also impersonate the bot. There's no way around this other then forcing people to make their own bots and store their own key in a uservar.

**Comment by rpherbig** [comment]
I'm not worried about Lichers we give the token to, I'm worried about people crawling GitHub for tokens (which does happen).

**Comment by rcuhljr** [comment]
Minimal obfuscation can stop that.

**Comment by rpherbig** [comment]
Encryption would, but I don't think this kind of obfuscation would stop anyone that was actually looking for tokens.

**Comment by jandersson** [comment]
I understand the risk that someone impersonates the bot could be disruptive, though I don't think any real harm can come from it other than spam (all it can do is act like another user). I can try to think of a way to pass the token in a secure fashion in the meantime. My thought is that a lichbot can be queried for the token if it isn't stored.

**Pull request merged**
