### PR TITLE
[script] [First aid] Remove DRC prefix where it doesn't belong.

### PR DESCRIPTION
**Pull request by MahtraDR**
As per title.

### CODE REVIEW

**Comment by asechrest** [comment]
Beat you to this one. Closing.

**Comment by asechrest** [comment]
I stand corrected. YOU beat me to this fix and I hadn't had a chance to review this morning before work.

**Comment by asechrest** [comment]
As long as @rpherbig is alright with it, a small fix of a breaking change like this, I'm ok if you merge your own PR.

**Comment by rpherbig** [comment]
> As long as @rpherbig is alright with it, a small fix of a breaking change like this, I'm ok if you merge your own PR.

Works for me

**Pull request closed without merging**
