### PR TITLE
Create slim-remedy.lic

### PR DESCRIPTION
**Pull request by Raykyn55**
Super basic version of remedy, designed for workorders/single-use crafting. Doesn't resume, assumes you have what you need.

Lifted some of the tools logic, but stripped out purchasing and item generation handling (because alcohol/water is ridiculously cheap).

### CODE REVIEW

**Comment by asechrest** [comment]
Thanks for the draft PR. Any reason to make this a separate script, vs. allowing the existing `remedy.lic` to handle a "slim" option?

**Comment by Raykyn55** [comment]
> Thanks for the draft PR. Any reason to make this a separate script, vs. allowing the existing `remedy.lic` to handle a "slim" option?

variable overlap and flags, primarily. It's also just easier visually, and for debug purposes. I was considering doing it as a rewrite, but there was a lot of functionality in the remedy script that craft, for example, needs remedy to handle.

**Comment by Raykyn55** [comment]
requires #6280

**Comment by Raykyn55** [comment]
going to collect these into one pr for testing purposes

**Pull request closed without merging**
