### PR TITLE
Common Arcana: Handle multiple cambrinth in cast_spell

### PR DESCRIPTION
**Pull request by jandersson**

### CODE REVIEW

**Comment by jandersson** [comment]
WRT the string to symbol change:
```
>;en echo get_settings.cambrinth_items.map { |x| x['cap'] }.inject(&:+)
--- Lich: exec1 active.
[exec1: ]
--- Lich: exec1 has exited.
>;en echo get_settings.cambrinth_items.map { |x| x[:cap] }.inject(&:+)
--- Lich: exec1 active.
[exec1: 48]
--- Lich: exec1 has exited.
>
```

**Comment by rpherbig** [comment]
Is that because you have `cap` as a symbol?

In base.yaml it's a string:
```

cambrinth_items:
--
175 | - name:
176 | cap:
177 | stored:
```

**Comment by jandersson** [comment]
Yes, that was it. I borrowed the sample settings from https://github.com/rpherbig/dr-scripts/pull/1852

**Comment by jandersson** [comment]
Fixed and retested

**Comment by rpherbig** [comment]
@jandersson reverted this due to reported problems

**Comment by jandersson** [comment]
Do you remember what the reported problems were by any chance?

**Comment by jandersson** [comment]
Ill test this out and see if I can narrow it down and resubmit a fixed version

**Comment by Sarvatt** [comment]
--- Lich: error: undefined method `each' for 5:Fixnum ; common-arcana:168:in `charge_and_invoke' ; common-arcana:119:in `find_charge_invoke_stow' ; --- Lich: buff has exited.

**Pull request merged**
