### PR TITLE
[script] [common-items] Use canonical model DRCI::Item to get name/regex

### PR DESCRIPTION
**Pull request by KatoakDR**
### Background
* Continuation of https://github.com/rpherbig/dr-scripts/pull/5041
* Some methods in `common-items` were on their own trying to determine the name or noun of an item, or create a regex pattern for it. The success rate depended significantly on how complete one's yaml configuration was when specifying the items.

### Changes
* Use the new `DRCI::Item.from_text(string)` method to convert a string argument into an `Item` class instance.
* Reuse the logic in `Item` class for `name`, `short_name`, and `short_regex` for consistency

### CODE REVIEW

**Comment by rpherbig** [comment]
Looks good to me ✔️

**Comment by KatoakDR** [comment]
@rpherbig Sorry, but could you revert this pull request please? It's had some unexpected consequences in scripts that's breaking for folks. Thanks

**Comment by rpherbig** [comment]
Done

**Comment by KatoakDR** [comment]
Thank you

**Pull request merged**
