### PR TITLE
[script][common-arcana] Calling our DRCMM functions from here [2 of 3]

### PR DESCRIPTION
**Pull request by MahtraDR**
Conveniently has settings to pass to the DRCMM functions too.

### CODE REVIEW

**Comment by KatoakDR** [comment]
For ease of reference, for multi step PRs would you mind adding the dependent PRs in the description. For this one it depends on https://github.com/rpherbig/dr-scripts/pull/5541#pullrequestreview-877643485

Example where I do this is with the hunting-buddy PRs that are open right now. 

Thanks!

**Comment by rpherbig** [comment]
I was moving too fast and merged the wrong PR, sorry!

**Comment by rpherbig** [comment]
Why not also delete DRCA's version of the function in this PR?

**Comment by KatoakDR** [comment]
> I was moving too fast and merged the wrong PR, sorry!

@MahtraDR other pro tip with multi step PRs is to put into draft mode the ones that are waiting on other PRs to merge so that it's also clearer to folks merging that conditions aren't yet ready. :)

**Comment by MahtraDR** [comment]
> Why not also delete DRCA's version of the function in this PR?

I plan to do that after all these are merged. Just in case I miss something, I at least won't break existing things that way.

**Pull request merged**
