### PR TITLE
smelt.lic: Specify stirring rod instead of just rod.

### PR DESCRIPTION
**Pull request by Sarvatt**
Fixes: #3609

Double checked that just rod wasn't used in any of the other forging scripts and it's ok.

### CODE REVIEW

**Comment by andymanak** [comment]
This broke smelt for me:

>tap stirring rod 
I could not find what you were referring to.
>tap stout rod
You tap a serpentine stout stirring rod that you are holding.

**Comment by rpherbig** [comment]
@sarvatt

**Comment by Sarvatt** [comment]
Not sure how to fix that. Enchanting rods will go in a crafting_container: at some point, just getting a rod from it isn't ok. Should I add a new setting for the rod adjective, or just special case this particular rod? I'm thinking the latter, most people will be using crafted rods.

**Comment by rpherbig** [comment]
A setting for the adjective seems straightforward, but it's a weak preference.

**Comment by Sarvatt** [comment]
ideally we'd get the rod adjective and noun from forging_tools: but I don't know how to do that

**Pull request merged**
