### PR TITLE
Use more descriptive names for built-in lich functions

### PR DESCRIPTION
**Pull request by rpherbig**
Lich offers quite a few aliases for its built-in functions. I think many are more descriptive than the original names we've been using.

I changed the ones I'm confident in. There are a few other options which I am undecided on (feedback welcome!):
* `checkmana` -> `mana`
* `checkhealth` -> `health`
* `checkname` -> `myname?`
* `checkright` -> `righthand`
* `checkleft` -> `lefthand`

### CODE REVIEW

**Comment by rcuhljr** [comment]
If you're doing hands you should make the wrapper user GameObj to get us noun+adj so we can stop using glance everywhere.

**Comment by rcuhljr** [comment]
Also myname? is not a predicate.

**Comment by rpherbig** [comment]
The aliases are built into lich, I didn't pick `myname?`. The non-predicateness of it is why I didn't make the change - I would have if it was simply `myname`.

**Comment by rcuhljr** [comment]
I misunderstood this, I thought you were making new aliases.

**Comment by rpherbig** [comment]
@rcuhljr Do you know if `checkhealth` is different than `DRStats.health`?

**Comment by rcuhljr** [comment]
They should be the same, I'm pretty sure they both populate off the healthbar xml data.

**Pull request merged**
