### PR TITLE
Almanac nouns in combat-trainer

### PR DESCRIPTION
**Pull request by Hiinky**

### CODE REVIEW

**Comment by Tarhish** [comment]
I think the previous version had the almanac setting in base.yaml, yeah?

**Comment by Hiinky** [comment]
Its three separate now.  I gave up on being consolidated and perfect

**Comment by Tarhish** [comment]
You might be handling this already then, but if this alone is pulled then no one besides you will have almanac: defined so they'll all crash out when they try to use the almanacs in combat-trainer

**Comment by rpherbig** [comment]
In the future please try to keep like changes packed up.

**Comment by Hiinky** [comment]
I so tried to make it one.  I need github desktop lessons....

updated for almanac_noun

**Pull request merged**
