### PR TITLE
[script][combat-trainer][update] Fix multiple failures when prone

### PR DESCRIPTION
**Pull request by asechrest**
Addressing issue #5242. Add a proper bput failure message for if you're knocked prone when trying Analyze. This failure message may need to be handled elsewhere. For now, handling the specific error case.

### CODE REVIEW

**Comment by asechrest** [comment]
Note: all this fix does is avoid the 15 second match failure and breaks us fully out of the analyze code block. The script then moves on to the next thing, which includes a call to `fix_standing` elsewhere.

I considered handling the error within `def analyze()` using a call to `DRC.fix_standing()` and the calling analyze() again, but we'd want to iterate the failure count, I think, to avoid an infinite loop. For now just opted for the simple fix.

**Comment by asechrest** [comment]
I added a commit to handle prone in the Barbarian analyze section. **I am unable to test this as I don't have a Barb.** Looks to me like it should work fine, but someone may want to test.

**Comment by Dartellum** [comment]
> Note: all this fix does is avoid the 15 second match failure and breaks us fully out of the analyze code block. The script then moves on to the next thing, which includes a call to `fix_standing` elsewhere.
> 
> I considered handling the error within `def analyze()` using a call to `DRC.fix_standing()` and the calling `analyze()` again, but we'd want to iterate the failure count, I think, to avoid an infinite loop. For now just opted for the simple fix.

Fail count should not change since no attempt to analyze was given. Do we count that it could not because prone as a failure to analyze? Need to test if it does enter a loop. I suppose it depends on the mob and if they can knock you down consistently, like rock trolls casting tremor.

**Comment by asechrest** [comment]
Most recent commit handles being prone when trying a Maneuver.

```
>lie
You lie down.
>
A musk hog hisses viciously and lunges at you!
* A musk hog claws, swiping with its hooves at you.  You block solidly with a dented pot lid dappled with scorch marks.  
[You're very badly balanced with opponent in superior position.]
>
[combat-trainer: ***Ready to use charged maneuver: crash***]
[combat-trainer]>maneuver crash
You must be standing to perform that maneuver.
>
[combat-trainer]>stand
You stand back up.
>
[combat-trainer]>maneuver crash
Bantree just arrived.
>
Taking a full step back, you plant your feet and ready a mighty attack.
Dashing in, you attempt to crash your sledgehammer through a musk hog!

A musk hog deftly sidesteps your pine-handled sledgehammer.

[You're badly balanced with opponent in strong position.]
Roundtime: 4 sec.
```

**Comment by vtcifer** [comment]
Have we thought about adding the "stand up fix" to bput instead, as another default "try again" match?

**Comment by Dartellum** [comment]
> Have we thought about adding the "stand up fix" to bput instead, as another default "try again" match?

I put that in my suggestions of code.

**Comment by asechrest** [comment]
@Dartellum I don't see your code suggestion?

@vtcifer Do you mean revising the bput method itself?

**Comment by asechrest** [comment]
I believe this now recovers from a prone position for both Tactics, Analyze, Charged Maneuvers, and Barbarian Analyze. Still unable to test the barb stuff, but the other stuff is tested on my character. Welcome further suggestions.

**Comment by Dartellum** [comment]
> @Dartellum I don't see your code suggestion?
> 
> 
> 
> @vtcifer Do you mean revising the bput method itself?

Look under the Commits tab.

**Comment by asechrest** [comment]
> > @Dartellum I don't see your code suggestion?
> > @vtcifer Do you mean revising the bput method itself?
> 
> Look under the Commits tab.

Hmmm. Am I missing it?

image

**Comment by Dartellum** [comment]
On the iPhone app it was under conversations. On the Web page, it is under Conversations. I started a review for each one. I also found the match should go here as well:

```
when /^Tactics$/i
      bput($tactics_actions.sample, 'roundtime', 'There is nothing else', 'Face what', 'You must be closer', 'You must be standing', 'Strangely, you don\'t feel like fighting right now', 'flying too high for you to attack', 'You should stand up first') unless game_state.npcs.empty?
```

image
image
image

**Comment by vtcifer** [comment]
> On the iPhone app it was under conversations. On the Web page, it is under Conversations. I started a review for each one. I also found the match should go here as well:

I don't think your review is published and viewable by anyone else yet (at least it's not showing up for me).

**Comment by vtcifer** [comment]
> @vtcifer Do you mean revising the bput method itself?

Indeed, I mean updating the DRC.bput method to natively handle the failure condition via trap, stand, retry, similar to how it handles RT/typeahead related issues.

```ruby
# [...]
      case response
      when /(?:\.\.\.wait |Wait |\.\.\. wait )([0-9]+)/
        unless ignore_rt
          pause(Regexp.last_match(1).to_i - 0.9)
          waitrt?
          put message
          timer = Time.now
        end
        next
      when /Sorry, you may only type ahead/
        pause 1
        put message
        timer = Time.now
        next
      when /^You should stand up first/
        fix_standing
        put message
        next
# [...]
```

**Comment by asechrest** [comment]
> > @vtcifer Do you mean revising the bput method itself?
> 
> Indeed, I mean updating the DRC.bput method to natively handle the failure condition via trap, stand, retry, similar to how it handles RT/typeahead related issues.
> 
> ```ruby
> 
> ```

You know, my first though was, "is that really the purview of `bput`"? But I see it already handles a coupe of other cases that are similar. I like the idea of it being centralized in DRC.

What sort of informal rule do we have about whether it should be handled in DRC.bput vs. when it should be handled in the script? I'm thinking something like: "if it's a failure case where we would nearly always want to fix the issue and retry the exact same bput, it can be handled in DRC.bput"?

**Comment by asechrest** [comment]
Handling this within DRC.bput.

**Pull request closed without merging**
