### PR TITLE
[script] [hunting-buddy] [6] option to stop when encumbered

### PR DESCRIPTION
**Pull request by KatoakDR**
### Dependencies
* https://github.com/rpherbig/dr-scripts/pull/5522
* https://github.com/rpherbig/dr-scripts/pull/5515
* https://github.com/rpherbig/dr-scripts/pull/5517
* https://github.com/rpherbig/dr-scripts/pull/5518
* https://github.com/rpherbig/dr-scripts/pull/5519
* https://github.com/rpherbig/dr-scripts/pull/5520

### Background
* Part of a series of updates I'm bringing to `hunting-buddy`
* As dependent PRs are merged then this one's diff will get smaller
* Previous proposal, https://github.com/rpherbig/dr-scripts/pull/5092

### Changes
* New per-hunt setting, `stop_on_encumbrance`, to indicate at which encumbrance level you want `hunting-buddy` to end combat prematurely. The range is 0 (None) to 11 (It's amazing you aren't squashed!). Default is nil to maintain current behavior; players opt-in.
* Because we only know your encumbrance by running the `encumbrance` command, put the check in the one-minute heartbeat section so as not to spam the output with encumbrance checks.

### Configuration
```yaml
hunting_info:
  - :zone:
      - rats
    # If specified then this is the encumbrance level at which you want hunting-buddy to abandon combat.
    # Being too encumbered hinders your defenses and increases your chances of receiving wounds.
    # Set a numeric value from 0 (None) to 11 (It's amazing you aren't squashed!)
    # https://elanthipedia.play.net/Encumbrance
    stop_on_encumbrance: 2
    ...
```

### Tests
_when encumbrance is at or above threshold then hunt is skipped_
```
[hunting-buddy]>encumbrance

  Encumbrance : It's amazing you aren't squashed!
> 
***STATUS*** Skipping hunt because encumbrance: It's amazing you aren't squashed!, threshold: 12

***STATUS*** Returning to safe room: 6058
```

### CODE REVIEW

**Review by asechrest — APPROVED** [review]
Tested:

Encumbrance threshold set to 0 before hunt and current encumbrance 0/11. Properly does not go to hunt.
image

`stop_on_encumbrance` set to a float of 0.5 (just to test), existing encumbrance 1/11:
image

Increasing encumbrance to >= set threshold mid-hunt (by picking up a thousand copper dokoras) properly catches it at the one-minute heartbeat encumbrance check:
image

Tested with yaml thresholds outside of the 0-11 bounds, protecting against user error, and properly flooring/ceiling-ing the values. No known use case for needing values below or above the 0-11 encumbrance marks:
image

Otherwise functions as normal hunting-buddy would.

**Comment by KatoakDR** [comment]
@asechrest thanks so much for the testing!

**Comment by asechrest** [comment]
> @asechrest thanks so much for the testing!

Thanks for the PR.

**Comment by asechrest** [comment]
> Tested with yaml thresholds outside of the 0-11 bounds, protecting against user error, and properly flooring/ceiling-ing the values. No known use case for needing values below or above the 0-11 encumbrance marks: image


[EDIT] - Note the encumbrance messaging hiccup. This is a regex issue in `drinfomon`. Future PR forthcoming.

**Comment by KatoakDR** [comment]
> > Tested with yaml thresholds outside of the 0-11 bounds, protecting against user error, and properly flooring/ceiling-ing the values. No known use case for needing values below or above the 0-11 encumbrance marks: image
> 
> [EDIT] - Note the encumbrance messaging hiccup. This is a regex issue in `drinfomon`. Future PR forthcoming.

Fixed in https://github.com/rpherbig/dr-scripts/pull/5618

**Pull request merged**
