### PR TITLE
Alleviate issue of backfire due to inaccurate checkcastrt from server lag

### PR DESCRIPTION
**Pull request by 13and3**
Related conversation:

[13:40] [DRPrime]-DR:Samyl: "waitcastrt? doesn't seem to be working quite right.  It's registering 0 time left, but the spell isn't yet fully prepared.  What'm I doing wrong?"
[13:41] [DRPrime]-DR:Atanamir: "waitcastrt? is inherently unreliable"
[13:41] [DRPrime]-DR:Sarvatt: "its lag to the server"
[13:41] [DRPrime]-DR:Atanamir: "due to lag to the server, yeah"
[13:41] [DRPrime]-DR:Atanamir: "it should include a sleep after it in nearly every case"
[13:42] [DRPrime]-DR:Samyl: "Okay... It's peppered throughout common-arcana (without a pause) eg with Buff.  What is the SOP to deal with that?"
[13:42] [DRPrime]-DR:Atanamir: "yes....I know... /teethgrit"
[13:42] [DRPrime]-DR:Samyl: "Just reduce my mana target? Add a prep time?"
[13:44] [DRPrime]-DR:Atanamir: "at some point I'm going to get fed up and actually submit a pr to include a sleep after every waitcastrt?...eventually"
[13:44] [DRPrime]-DR:Atanamir: "annoyance has not yet tipped over the wall of laziness just yet"
[13:44] [DRPrime]-DR:Samyl: "Might it be better to add a method to common_arcana called waitcastrt_pause? that does waitcastrt and adds a configurable pause?"
[13:45] [DRPrime]-DR:Yggrald: "pauses aren't robust tho"
[13:45] [DRPrime]-DR:Atanamir: "I see a project in your future, good sir or madame"
[13:46] [DRPrime]-DR:Samyl: "I will do this if it's the approach the community would prefer.. I just need a vague consensus.  eg Yggrald thinks adding a pause won't work.  A Fully Prepared flag also seems fragile."
[13:46] [DRPrime]-DR:Atanamir: "waitcastrt? does most of the work, but given latency, it always falls just short.  A pause coupled with waitcastrt is robust enough"
[13:46] [DRPrime]-DR:Yggrald: "if you have a handle on your max latency yes it'd be fine"
[13:47] [DRPrime]-DR:Atanamir: "I wonder if anyone suffers from more than a 2 second latency these days"
[13:47] [DRPrime]-DR:Yggrald: "I do sometimes"
[13:47] [DRPrime]-DR:Atanamir: "yeesh"
[13:47] [DRPrime]-DR:Yggrald: "but i don't use that function either way so my opinion doens't matter"
[13:48] [DRPrime]-DR:Atanamir: "do you have a better idea how to address the existing shortcomings of waitcastrt?"
[13:48] [DRPrime]-DR:Yggrald: "no i'm just shitting on your dreams :-/"
[13:48] [DRPrime]-DR:Atanamir: "Ahh, ok.  Carry on! :D"
[13:48] [DRPrime]-DR:Sarvatt: "waitcastrt is hardcoded to add a 60ms delay so if your ping is over that RIP"
[13:49] [DRPrime]-DR:Ashalf: "that's what 60000ms?"
[13:49] [DRPrime]-DR:Yggrald: "no it's 60 ms"
[13:49] [DRPrime]-DR:Atanamir: "Um"
[13:49] [DRPrime]-DR:Ashalf: "oshit, I read that as 60s delay"
[13:49] [DRPrime]-DR:Ashalf: "I'm a horrible person."
[13:49] [DRPrime]-DR:Yggrald: "hahaha"
[13:50] [DRPrime]-DR:Sarvatt: "https://github.com/rcuhljr/dr-lich/blob/master/lich.rbw#L4471"
[13:50] [DRPrime]-DR:Atanamir: "1s is 1000 ms"
[13:50] [DRPrime]-DR:Atanamir: "I deal with them all day long"
[13:50] [DRPrime]-DR:Atanamir: "I promise"
[13:51] [DRPrime]-DR:Barder: "but do you pinkie swear?"
[13:51] [DRPrime]-DR:Atanamir: "only for you Barder"
[13:51] [DRPrime]-DR:Atanamir: "oh, I missed the 60ms mention, my bad"

### CODE REVIEW

**Comment by 13and3** [comment]
Why does this test fail?

  1) Failure:
TestDRCA#test_ritual_with_skip_retreat [/home/travis/build/rpherbig/dr-scripts/test/test_common-arcana.rb:77]:
Expected script to send messages.
Expected ["cast"] to be empty.

**Comment by Sarvatt** [comment]
You will need to add the waitcastrt_and_pause method to common before any of the other changes go in so people don't hit the scenario where they log in another character (which updates scripts) while another one still had common-arcana in memory

**Comment by 13and3** [comment]
@Sarvatt Do you mean, create two separate pull requests, one with just wait_cast_rt in common-arcana, and another that updates all ancillary references?

**Comment by Sarvatt** [comment]
yeah

**Pull request closed without merging**
