### PR TITLE
[script] [vanity-pet] New script to stow/drop vanity pets that follow you

### PR DESCRIPTION
**Pull request by KatoakDR**
### Dependencies
* ~~Depends on https://github.com/rpherbig/dr-scripts/pull/4677~~

### Background
* Some [vanity pets](https://elanthipedia.play.net/Vanity_pet), like hogs and monkeys, can be set on the ground to follow you.
* At times, these pets need to be stowed away for safe keeping, such as before [burgling](https://elanthipedia.play.net/Burgle_command) so that they aren't lost when a room unloads.

### Changes
* Introduce new script `vanity-pet.lic` that can stow or drop your pet.
* Handles if the pet is already in your hands.
* Handles if the pet can't be dropped in the room (such as bank or item registration).
* When stowing pet, waits up to 15 seconds for pet to arrive in the room.

## Usage

```
  vanity-pet pet_action pet_name pet_container [debug]

   pet_action     STOW or DROP to either stow your pet in their container or drop them to the ground. 

   pet_name       Name of your pet. 

   pet_container  Container for your pet. 

   debug          Enable debug output 
```

### Drop Pet
```
> ;vanity-pet drop farm.hog woven.sack

--- Lich: vanity-pet active.

[vanity-pet]>get farm.hog from my woven.sack

You pluck a lazy farm hog from a soft woven sack with a golden piglet charm, the creature snorting as you wake it up.
> 
[vanity-pet]>drop my farm.hog

You set the farm hog on the ground.  It trots around you in a circle, happily oinking.

> 
--- Lich: vanity-pet has exited.
```

### Stow Pet
```
> ;vanity-pet stow farm.hog woven.sack

--- Lich: vanity-pet active.

[vanity-pet]>get farm.hog

You scoop the farm hog up.

> 
[vanity-pet]>put my farm.hog in my woven.sack

You tuck your farm hog into its snug woven sack and it curls up to go to sleep, snorting softly.
> 
--- Lich: vanity-pet has exited.
```

### Hook into hunting-buddy Script
```yaml
hunting_info:
  before:
  - vanity-pet stow farm.hog woven.sack
  after:
  - vanity-pet drop farm.hog woven.sack
```

### Hook into burgle Script
```yaml
burgle_settings:
  before:
  - vanity-pet stow farm.hog woven.sack
  after:
  - vanity-pet drop farm.hog woven.sack
```

### CODE REVIEW

**Comment by KatoakDR** [comment]
Switched to draft while wait on https://github.com/rpherbig/dr-scripts/pull/4677

**Comment by rpherbig** [comment]
✔️ Code looks good, I'm fine with merging this as-is.

One ❓ for you: I wonder if the script name is too short. `Pet` can be a verb or noun. Is 'pet' unambiguously referring to vanity pets in the DR context?

I don't have a suggestion for a new name. Let me know if you want to keep the existing name and I'll merge this PR.

**Comment by KatoakDR** [comment]
> Is 'pet' unambiguously referring to vanity pets in the DR context?

Hrmmm, good question. What do you think of these names:
* mypet.lic
* my-pet.lic
* vanity-pet.lic
* petstore.lic
* pet-store.lic

**Comment by rpherbig** [comment]
I don't have a strong preference, but given the options I would pick `vanity-pet.lic`.

**Comment by KatoakDR** [comment]
> I don't have a strong preference, but given the options I would pick `vanity-pet.lic`.

Cool, I’ve renamed the file and updated the examples. Thanks

**Pull request merged**
