### PR TITLE
[script][pick] Add option to pick for another player

### PR DESCRIPTION
**Pull request by Raykyn55**
Pretty simple edit, accepts the full name of a player currently in the room with you, uses all your pick settings to open the boxes, then gives the box back to the player. Will accept cash tips, but will ignore other tip offers. Once tip is received, drops buffs, re-dons gear, exits the script.

### CODE REVIEW

**Comment by Kiriawen** [comment]
why not just make it a ready state script?  Meaning you do `;pick other` or whatever arg and it waits for a box offer accepts the box from any player, picks it and then returns it to the player that offered it? Then there's no reason to specify a specific player.

**Comment by Raykyn55** [comment]
> 

Seems suspiciously similar to a locksmithing bot :D

**Comment by Raykyn55** [comment]
So, this edit allows YOU to pick for someone else, with all the normal pick settings and arguments (assumed difficult, etc). Additionally, the pickforme arg allows you to engage a locksmith to open your boxes, with behavior consistent with MOST scripts (eg accept the opened box before giving a new box, loot and dismantle while they work).

Finally, the two sides can work with one another. Someone running pick <player> and someone running pick <player> pickforme automates the whole process.

log from picker perspective:
```
>;pick choshem

--- Lich: pick active.

--- Lich: common-healing active.

--- Lich: common-healing-data active.

--- Lich: common-healing-data has exited.

--- Lich: common-healing has exited.

--- Lich: equipmanager active.

--- Lich: equipmanager has exited.

[pick]>inv combat

All of your combat equipment:

  a smokewood pelletbow with tarts painted along the stock
  some darkened smokewhorl leathers lined with vermilion firesilk
  some haralun elbow spikes
  a pugilist's armguard of layered black steel plates
  some steel knee spikes
  some steel spiked footwraps
[Use INVENTORY HELP for more options.]

--- Lich: buff active.


[buff]>Khri Safe

With but a quick thought, your hands steady and your mind gears itself to the purpose of getting into what others want you out of.
Roundtime: 3 sec.

--- Lich: buff has exited.

[pick: Waiting for proffer]

Xibar sets, slowly dropping below the horizon.
Choshem rummages through an imperial weave cloth lootpouch, pausing once in a while and then quickly resuming the search.

Gained: Inner Magic(+1)

Choshem exhales softly on his sanowret crystal, and scintillating sparks of light dance across its surface.

Gained: Augmentation(+1)

Verindi deftly removes a lockpick from her lockpick ring and begins to fiddle with a plain copper caddy using her lockpick.
Verindi returns her lockpick to the lockpick ring.

Gained: Utility(+1), Warding(+1)

Choshem's body below the waist is dripping water everywhere.
The bandages binding Verindi's chest soak through with blood as it begins bleeding again.
Verindi unwraps her bandages.
Choshem rummages through an imperial weave cloth lootpouch.
Choshem rummages through a featherlette pack trimmed with bright white cording with a frantic look of loss.
Choshem gets a deeply gouged brass skippet from inside his featherlette pack.
Blood Channeler Linel just arrived.
Choshem offers you a deeply gouged brass skippet.  Enter ACCEPT to accept the offer or DECLINE to decline it.  The offer will expire in 30 seconds.

[pick]>accept

You accept Choshem's offer and are now holding a deeply gouged brass skippet.
You notice Linel slip into a hiding place.

[pick]>glance my brass skippet

Gained: Perception(+1)

It looks like there is 1 trap left on the skippet.
Looking more closely you see...
This is a teleporter trap, if the bright crimson metal circle means anything.

It looks like there is 1 lock left on the skippet.
Looking more closely you see...
An intricate steel star houses a complex locking mechanism, with two different spots that each look like they're meant to house keys.

[pick]>disarm my brass skippet identify

Choshem gets a crust-covered ironwood trunk from inside his featherlette pack.
Somebody has already located and identified the current trap on the brass skippet...

The hinges of the brass skippet are covered with a thin metal circle that has been lacquered with a shade of bright crimson.
An aged grandmother could defeat this trap in her sleep. (1/17)

[pick]>disarm my brass skippet quick

You quickly work at disarming the skippet.
You work with the trap for a while but are unable to make any progress.
You get the distinct feeling your manipulation caused something to shift inside the trap mechanism.  This is not likely to be a good thing.
Roundtime: 1 sec.
Verindi works carefully at tending her wounded chest.

[pick]>disarm my brass skippet quick

You quickly work at disarming the skippet.
Slowly, so as not to accidentally jostle the brass skippet during the attempt, you work carefully at the bright crimson circle, and bend it away until its metal no longer touches the hinges at all.
Roundtime: 1 sec.

[pick]>glance my brass skippet

It looks like there are no traps left on the skippet.

It looks like there is 1 lock left on the skippet.
Looking more closely you see...
An intricate steel star houses a complex locking mechanism, with two different spots that each look like they're meant to house keys.

[pick]>pick my brass skippet ident

Somebody has already inspected the current lock on this skippet...

This lock is a laughable matter -- you could do it blindfolded! (2/17)

[pick]>pick my brass skippet quick

You deftly remove a lockpick from the lockpick wristcuff and begin to work at quickly picking open the skippet.
With a soft click, you remove your lockpick and open and remove the lock.
You quickly notice the lockpick is bent beyond practical use.  With a grimace, you discard the now useless lockpick.
Roundtime: 1 sec.

Gained: Locksmithing(+1)

[pick]>give my brass skippet to choshem

You offer your brass skippet to Choshem, who has 30 seconds to accept the offer.  Type CANCEL to prematurely cancel the offer.
Choshem has accepted your offer and is now holding a deeply gouged brass skippet.

[pick: Waiting for proffer]

Choshem offers you a crust-covered ironwood trunk.  Enter ACCEPT to accept the offer or DECLINE to decline it.  The offer will expire in 30 seconds.

[pick]>accept
```
log from pickee perspective (pickforme):
```
>;pick scrounger pickforme

--- Lich: pick active.

[pick]>open lootpouch

That is already open.

[pick]>open featherlette pack

That is already open.

[pick]>open enshrouding clouds

That is already open.

[pick]>open featherlette pack

That is already open.

[pick]>rummage /B my lootpouch

You rummage through an imperial weave cloth lootpouch looking for boxes but there is nothing in there like that.

[pick]>rummage /B my featherlette pack

You rummage through a featherlette pack trimmed with bright white cording looking for boxes and see a deeply gouged brass skippet, a crust-covered ironwood trunk, a pitted iron crate, a sturdy ironwood trunk, a cracked driftwood trunk, a misshaped deobar skippet, a misshaped ironwood strongbox, a worm-eaten driftwood box, a crust-covered wooden trunk, a copper-edged mahogany skippet, a misshaped iron strongbox, a reinforced wooden trunk, a reinforced copper skippet, a poorly made iron strongbox, a salt-stained brass chest, a copper-edged iron strongbox, a copper-edged steel chest, a pitted steel strongbox, a deeply gouged deobar box, a mud-stained iron trunk, a deeply gouged deobar trunk, a dented iron coffer, a mud-stained pine caddy, a pitted brass caddy, a copper-edged wooden chest, a rotting deobar chest, a crust-covered driftwood box and a crooked iron chest.
Boxes to pop: 28

[pick]>get my brass skippet from my featherlette pack

You get a deeply gouged brass skippet from inside your featherlette pack.
Blood Channeler Linel just arrived.

[pick]>give my brass skippet to scrounger

You offer your brass skippet to Scrounger, who has 30 seconds to accept the offer.  Type CANCEL to prematurely cancel the offer.
Scrounger has accepted your offer and is now holding a deeply gouged brass skippet.
You notice Linel slip into a hiding place.

[pick]>get my ironwood trunk from my featherlette pack

You get a crust-covered ironwood trunk from inside your featherlette pack.

[pick: Waiting for proffer]

Gained: Perception(+1)

Scrounger begins to fiddle with a deeply gouged brass skippet.
Verindi works carefully at tending her wounded chest.
Scrounger begins to fiddle with a deeply gouged brass skippet.
Scrounger looks up from the brass skippet with a satisfied grin.
Scrounger deftly removes a lockpick from his lockpick wristcuff and begins to fiddle with a deeply gouged brass skippet using his lockpick.
A soft click comes from the skippet.
Scrounger grimaces and discards his lockpick.
Scrounger offers you a deeply gouged brass skippet.  Enter ACCEPT to accept the offer or DECLINE to decline it.  The offer will expire in 30 seconds.

[pick]>accept

You accept Scrounger's offer and are now holding a deeply gouged brass skippet.

[pick]>give my ironwood trunk to scrounger

You offer your ironwood trunk to Scrounger, who has 30 seconds to accept the offer.  Type CANCEL to prematurely cancel the offer.
Scrounger has accepted your offer and is now holding a crust-covered ironwood trunk.

[pick]>open my brass skippet

You open the brass skippet...

In the brass skippet you see a small clear diamond, some copper coins, some bronze coins, a silver coin, and some gold coins.
You quickly pocket the coins.

[pick]>look in my brass skippet

In the brass skippet you see a small clear diamond.

[pick]>get diamond from my brass skippet

Scrounger looks up from the ironwood trunk with a satisfied grin.
You get a small clear diamond from inside your brass skippet.
Scrounger begins to fiddle with a crust-covered ironwood trunk.
Scrounger looks up from the ironwood trunk with a satisfied grin.

[pick]>stow my diamond

You open your pouch and put the clear diamond inside, closing it once more.

[pick]>dismantle my brass skippet caravan

You gaze at the brass skippet in your grasp, wondering what next to do with it.  As a caravan comes thundering by, you casually toss the brass skippet under a wheel, smiling at the satisfying crunch that results.
Roundtime: 3 seconds.
Scrounger deftly removes a lockpick from his lockpick wristcuff and begins to fiddle with a crust-covered ironwood trunk using his lockpick.
A soft click comes from the trunk.
Scrounger returns his lockpick to the lockpick wristcuff.
Scrounger offers you a crust-covered ironwood trunk.  Enter ACCEPT to accept the offer or DECLINE to decline it.  The offer will expire in 30 seconds.

[pick]>get my iron crate from my featherlette pack

You get a pitted iron crate from inside your featherlette pack.

[pick: Waiting for proffer]

[pick]>accept
```

**Comment by Raykyn55** [comment]
requires #6361

**Comment by Raykyn55** [comment]
Testing well, just waiting on the give_item PR referenced above.

**Pull request closed without merging**
