### PR TITLE
Skip moonblade check if not summoning weapons

### PR DESCRIPTION
**Pull request by jandersson**
Give this a few days for testing; would like to avoid breaking anything

This is to avoid the 'glance moon' spam users dont like too much.

### CODE REVIEW

**Comment by Sarvatt** [comment]
looks good to me, thanks for fixing this!

**Comment by rpherbig** [comment]
:+1:

**Comment by Sarvatt** [comment]
i dont see any reason to avoid merging this asap. its very straight forward and correct.

**Comment by jandersson** [comment]
Ok, I finally sat down and tested this. I forgot to make the summon_weapons variable non-private, so its good that this didnt get merged.

With that fixed, ct will check glance moon only once at startup:
```
[combat-trainer]>glance moon
I could not find what you were referring to.
>
[combat-trainer: skipping summoned weapons because no moonblade available]
[combat-trainer: checking weapons as nil!=Large Edged]
[combat-trainer]>get my bastard.sword
```

**Comment by jandersson** [comment]
It looks like it is still doing the glance, so will need to double check that logic.

**Comment by jandersson** [comment]
@rpherbig This is ready to go. Tested with and without moonblade usage. Players wont 'glance moon' anymore if no summoned weapons defined

**Pull request merged**
