### PR TITLE
YAML setting to skip Crossing-Repair

### PR DESCRIPTION
**Pull request by intangibles**
Added YAML setting to completely skip crossing-repair. Useful for people who don't want to repair, (and necromancers who blow their SO!)

I also figured this was a good time to plug in a setting for necromancers to avoid functions that could cause a social outrage spiral.

Setting is:
high_social_outrage: true/false
Default is set to false.

### CODE REVIEW

**Comment by rpherbig** [comment]
Per #1645, I thought repairing was _NOT_ affected by SO...

**Comment by intangibles** [comment]
Yeah @rpherbig.  But currently crossing-repair uses exchange/deposit at the bank!  So not sure if we would rather skip repair altogether or just skip the deposit/exchange functions.

**Comment by Morzain** [comment]
All I can tell you for sure is I'm in a bit of a SO spiral from trying to use ;training after being accused yesterday lol.

it successfully repaired all my gear but later on when it went to deposit into the bank I got clipped...as well as when ;pick tried to buy lockpicks.

**Comment by jayRyan24** [comment]
It seems to me that these settings do the exact same thing. What is the purpose of both of them? I can see it useful for people that don't want to repair each iteration, but two switches seems pointless. If the necro has high social outrage, they can just turn off the repairing. I could see the SO toggle being used if it got flagged automatically and wasn't a YAML setting.

**Comment by intangibles** [comment]
I'll remove the SO setting. It was a placeholder for a future toggle but doesn't need to be part of this PR.

**Comment by intangibles** [comment]
@rpherbig @rcuhljr 
Can either of you gentlemen push this through? I've removed the SO pieces and it is a simple repair toggle now.

Thanks!

**Pull request merged**
