### PR TITLE
modified stow_lootables function in combat-trainer

### PR DESCRIPTION
**Pull request by drsuik**
Modified stow_lootables function in combat-trainer to attempt to stow loot items in the picking_box_storage container set in YAML before declaring it unlootable and dropping it.  If picking_box_storage is not set or unable to store in set container, it finishes declaring it unlootable and dropping it.

I set this up mainly for boxes, as pick.lic will look in pick_box_storage after picking_box_source is empty. I don't see it unsustainably filling the container with loot. However, perhaps a function somewhere to clean up this container might be necessary. IE a fill my gempouch with my pick_box_storage?

### CODE REVIEW

**Comment by rcuhljr** [comment]
My biggest problem with this is that filling up both bags will cause severe problems, you'll be unable to take gear off successfully in order to lockpick the boxes filling up the entire inventory for example.

**Comment by drsuik** [comment]
That makes sense. Also, people who are harvesting boxes while training may not go through them quickly enough to clear out their containers. And burden could become an issue with lower circle characters. Would the ability to set a overflow box container separate from someone's main stow container be desirable(too keep it free for armor and such)? Coming with a burden warning in the description? IDK, I'll close this if the potential for severe problems can't be sorted out as this would be a niche benefit anyways

**Comment by rcuhljr** [comment]
I'm just positing that if you want to pursue this it should be an opt in feature in someones yaml.

**Comment by drsuik** [comment]
I added a store_extra_loot setting to base.yaml to drive this option. Its default is false.

**Comment by drsuik** [comment]
Bah, pick.lic doesn't look in pick_box_storage for unopened boxes. Will revisit

**Comment by rpherbig** [comment]
Should this be closed, or are you pursuing other ideas?

**Pull request closed without merging**
