### PR TITLE
[scripts] [common-items] [01] Add "DRCI" prefix to constants

### PR DESCRIPTION
**Pull request by KatoakDR**
This is the 1st of many PRs I'll be submitting for common-items.

To make it easier to review the changes, I'm phasing them in.

This one focuses on psuedo namespacing the constants.

### CODE REVIEW

**Comment by wstampley** [comment]
With constants like this - is the intent that they are just re-used inside DRCI, or that they are supposed to be available to other scripts/files to use as well?

I ask, because if they are considered internals for DRCI, I think we could put them inside the module itself, which would keep them from being global.

**Comment by wstampley** [comment]
It also might be nice to mark all the dependent PRs as drafts or something, because they're hard to review until this change goes in.

**Comment by KatoakDR** [comment]
> With constants like this - is the intent that they are just re-used inside DRCI, or that they are supposed to be available to other scripts/files to use as well?
> 
> I ask, because if they are considered internals for DRCI, I think we could put them inside the module itself, which would keep them from being global.

Just used within DRCA class. They were originally defined as $ constants so I ran with it. To not blow up the train of PRs already queued up, I’ll add a new PR to move the constants to class variables. Thanks

**Comment by KatoakDR** [comment]
> It also might be nice to mark all the dependent PRs as drafts or something, because they're hard to review until this change goes in.

To help with reviewing the downstream PRs, I’ve included in the description a link to the specific commit that PR is introducing. That’ll allow you to review and comment on the specific change without all the noise. Thanks

**Pull request merged**
