### PR TITLE
Crossing-training release_cyclics tweak

### PR DESCRIPTION
**Pull request by drboldwin**
makes it conditional against rite of grace and regenerate

### CODE REVIEW

**Comment by jandersson** [comment]
Regarding the discussion we had about RoG in hunting-buddy: What do you all think about a 'post-hunting' waggle_set? This would recast or cast RoG after hunting or any other buffs desired while ;sell-loot and ;crossing-repair are running?

**Comment by rcuhljr** [comment]
Could we have these cyclics it leaves up be listed in base_yaml? Do that and it's good to go.

**Comment by rpherbig** [comment]
@drboldwin @jandersson Does the 'after' functionality take care of this adequately?

**Comment by jandersson** [comment]
yes

**Pull request closed without merging**
