### PR TITLE
Coordinator: Pass settings to ensure_copper_on_hand

### PR DESCRIPTION
**Pull request by jandersson**
Small change that fixes usage of ensure_copper_on hand

### CODE REVIEW

**Comment by gerritlansing** [comment]
Looks good to me.

**Comment by Sarvatt** [comment]
are these lines even required actually? workorders checks for money itself and its different amounts than here, it might have just been cribbled out of crossing-training when it did non workorders also

**Comment by Sarvatt** [comment]
its potentially one more crafting room to society trip here, this is requiring 5 gold for shaping and workorders goes and gets a plat

**Comment by Sarvatt** [comment]
i could be wrong, on a phone and cant look it up but im almost positive workorders handles money on its own and this ensure copper on handle was just in crossig-training to handle he non workorders use case back in the day

**Comment by jandersson** [comment]
I checked - You are right, these lines should just be removed instead

**Pull request merged**
