### PR TITLE
New lift verb

### PR DESCRIPTION
**Pull request by Raykyn55**

### CODE REVIEW

**Comment by Hiinky** [comment]
:)  thank you for adding.

**Comment by Raykyn55** [comment]
```
[sew]>mark my robes with my stamp
You pull the robes tight across a flat piece of wood and then hammer the stamp onto a corner of the fabric.  This permanently stretches the fabric's threads, permanently embossing the stamp's symbol upon the piece.
Roundtime: 7 sec.
>
[sew]>put my basic stamp in my featherlette pack
You put your stamp in your featherlette pack.
>
robes Complete
[sew]>lift cloth
You pick up the cloth lying at your feet.
>
[sew]>put my cloth in my featherlette pack
You put your cloth in your featherlette pack.
```

**Comment by Raykyn55** [comment]
log for shape:
```
crown complete!
[shape]>lift lumber
You pick up the lumber lying at your feet.
>
[shape]>put my lumber in my featherlette pack
You put your lumber in your featherlette pack.
>
[shape]>prepare symbiosis
But you've already prepared the Chaos symbiosis!
>
[shape]>release symbiosis
You pause for a moment as the details of the Chaos symbiosis fade from your mind.
You release the Chaos symbiosis.
>
[shape]>release spell
You let your concentration lapse and feel the spell's energies dissipate.
>
[shape]>release mana
You aren't harnessing any mana.
>
--- Lich: shape has exited.
```

**Comment by Raykyn55** [comment]
log for enchant:
```
[enchant]>wave imbuement rod at totem on silversteel brazier
The spell is channeled through the fount hanging above, and down into the totem.  After focusing the streams into ordered groups you then direct them into exacting positions.
Roundtime: 6 sec.
The spell's energies settle upon the totem and seal off the pattern.  With the enchanting process completed, you believe it is safe to collect your things once more.
You collect the fount and place it at your feet.
You collect the totem and place it at your feet.
>
[enchant]>tie my imbuement rod to my forger's belt
You attach a translucent imbuement rod resembling a shard of ice to a strap on your forger's belt.
>
[enchant]>tie my silversteel brazier to my forger's belt
You attach a small silversteel brazier scattered with glittering starstones to a strap on your forger's belt.
>
[enchant]>lift fount
You pick up the fount lying at your feet.
>
[enchant]>put my fount in my featherlette pack
You put your fount in your featherlette pack.
>
[enchant]>lift totem
You pick up the totem lying at your feet.
>
[enchant]>get my stamp
You get a basic glaes stamp from inside your featherlette pack.
>
[enchant]>mark my totem with my stamp
You lazily wave the stamp over the freshly enchanted totem.  The imbue spell's expiring magic latches onto the engraved image and permanently imprint it within the sigil lines.
Roundtime: 7 sec.
>
[enchant]>put my stamp in my featherlette pack
You put your stamp in your featherlette pack.
>
--- Lich: enchant has exited.
```

**Comment by MahtraDR** [comment]
I'm reverting this. Looks like the new verb doesn't use adjectives, and we have a lot of reports of problems with this. There is an open request for Simu to implement adjectives, at which point we can revisit this.

**Comment by Raykyn55** [comment]
> I'm reverting this. Looks like the new verb doesn't use adjectives, and we have a lot of reports of problems with this. There is an open request for Simu to implement adjectives, at which point we can revisit this.

Can you give me an example?

**Comment by MahtraDR** [comment]
> > I'm reverting this. Looks like the new verb doesn't use adjectives, and we have a lot of reports of problems with this. There is an open request for Simu to implement adjectives, at which point we can revisit this.
> 
> Can you give me an example?

```
[enchant]>wave fey-bone rod at bone totem on uthamar brazier
The spell is channeled through the fount hanging above, and down into the totem.  After focusing the streams into ordered groups you then direct them into exacting positions.
Roundtime: 11 sec.
The spell's energies settle upon the totem and seal off the streams of mana.  With the enchanting process completed, you believe it is safe to collect your things once more.
You collect the fount and place it at your feet.
You collect the totem and place it at your feet.
R> 
Gained: Enchanting(+1)
R> 
[enchant]>put my fey-bone rod in my pack
...wait 1 seconds.
R> 
[enchant]>put my fey-bone rod in my pack
You put your rod in your traveler's pack.
> 
[enchant]>get my burin
You get a diamond-hide bound burin fixed with a Zoluren white sapphire from inside your traveler's pack.
> 
[enchant]>put my uthamar brazier in my pack
You put your brazier in your traveler's pack.
> 
[enchant]>put my burin in my pack
> 
You put your burin in your traveler's pack.
> 
[enchant]>lift fragile fount
What did you want to try and lift?
> 
[enchant]>lift bone totem
What did you want to try and lift?
> 
--- Lich: enchant has exited.
[workorders]>get my enchanting logbook
You get an enchanting work order logbook from inside your traveler's pack.
> 
[workorders]>bundle my totem with my logbook
You need to be holding the totem to do that.
[If the item is too heavy, you should first deed it by PUSHing it with a Deed Packet.]
```

**Comment by MahtraDR** [comment]
Multiple users reporting similar issues.

**Comment by Raykyn55** [comment]
> Multiple users reporting similar issues.

ah, that's a problem with the recipes file. Every artificing recipe using the bone totem and small sphere are listing adjective/noun pairs for the noun field:
```yaml
- name: unleashed gwethsmasher
  noun: bone totem
  type: artificing
  chapter: 2
  work_order: false
  enchant_stock1_name: abolition
  enchant_stock1: 2
  enchant_stock2_name: metamorphosis
  enchant_stock2: 7
  enchant_stock3_name:
  enchant_stock3:
  enchant_stock4_name:
  enchant_stock4:
  item: 16
  part:
```
Some(maybe all?) of those recipes produce an item that's no longer interacted with using "bone totem". This is only a problem in enchanting, and it's an easy fix:

```ruby
    if /You pick up/ =~ DRC.bput("lift #{'fount'}", /^You pick up/, /^What did you want to try and lift/)
      DRCC.stow_crafting_item('fount', @bag, @belt)
    end
    DRC.bput("lift #{@item.split(' ').last}", /^You pick up/, /^What did you want to try and lift/)
  end
```

Even if they offer the adjective/noun pairing on the lift verb, it's going to fail to lift these items. sew/shape are fine as is.  Alternatively, an edit to base-recipes to make the noun fields just the noun would work as well, and probably be more helpful longterm.

**Comment by Raykyn55** [comment]
noticed some changes to the lift verb this morning, now we don't even need a noun. What about a common method?

```ruby
    def lift?
        current = [DRC.right_hand,DRC.left_hand].compact # current contents of our hands
        if /You pick up/ =~ DRC.bput("lift", /^You pick up/, /^What did you want to try and lift/, /^There are no items lying at your feet/)
            return [DRC.right_hand,DRC.left_hand].compact - current # returns whatever item we lifted
        end
        false # nothing was lifted
    end
```

would either return the item/truthy or false, so we could evaluate the new item for proper treatment, eg use it if it's what we're looking for, or just stow whatever it is based on other settings, since we'd have the adj/noun from the method.

**Pull request merged**
