### PR TITLE
sew.lic: allow setting a material type for cloth

### LINKED ISSUE #2065: sew does not take the material into account for cloth
it hardcodes "get my cloth" and such in places, which can grab chamois cloths instead of crafting material.

### PR DESCRIPTION
**Pull request by Sarvatt**
default to burlap if not provided.
Fixes #2065

### CODE REVIEW

**Comment by Sarvatt** [comment]
Tested with `;sew stow sewing 3 "a cloth backpack" backpack` with a cham cloth as my "get cloth" item and burlap in a crafting bag. And also with  `;sew stow sewing 3 "a cloth backpack" backpack wool` with wool in a crafting bag and a cham cloth at the top of the get cloth list.

**Comment by rcuhljr** [comment]
So what happens if I have heavy wool cloth, fine wool cloth, and heavy silk cloth?

**Comment by Sarvatt** [comment]
it just goes by the material, wool cloth so that's something you'd have to sort out beforehand if you wanted to use a specific one like heavy, no different than now.

**Comment by Sarvatt** [comment]
ahh you mean it would work for any cloth before, gotcha

**Comment by Sarvatt** [comment]
Closing this and the other, I'm going to make the material type non-optional which will require the base update in the workorders PR.

**Pull request closed without merging**
