### PR TITLE
[script][burgle] Rework entry to use common methods

### PR DESCRIPTION
**Pull request by Raykyn55**
Use of DRCI.exits? precludes portals for storage, and several of the gets were bputs. Migrating the code over to items methods required reworking the entry checking. Instead of tapping, this does the entry management when you get (unless following).

### CODE REVIEW

**Comment by Raykyn55** [comment]
Added priority checks, logs to follow

**Comment by Raykyn55** [comment]
First, log for entry type: priorityrope with athletics@ 8:
```
>;burgle start
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>stow right
You put your casket in your entangling brambles.
>
[burgle]>get my heavy rope 
You get a coil of heavy rope from inside your scavenger's pack.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for entry type: prioritylockpick with athletics@8, locksmithing@12:
```
>;burgle start
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>stow right
You put your rope in your scavenger's pack.
>
[burgle]>tap my lockpick case 
You tap a darkly painted lockpick case depicting a pair of emerald-eyed panthers that you are wearing.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release spell
You let your concentration lapse and feel the spell's energies dissipate.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
>;ka
--- Lich: burgle has exited.
--- Lich: buff has exited.
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for burgle start rope with rope:
```
>;burgle start rope
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>get my heavy rope 
You get a coil of heavy rope from inside your scavenger's pack.
>
--- Lich: buff active.
[buff]>prepare symbiosis
But you've already prepared the Avoid symbiosis!
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release spell
You let your concentration lapse and feel the spell's energies dissipate.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for burgle start lockpick:
```
>;burgle start lockpick
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>tap my lockpick case 
You tap a darkly painted lockpick case depicting a pair of emerald-eyed panthers that you are wearing.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for burgle start rope while missing rope:
```
>drop rope
You drop a coil of heavy rope.
>release spell
You let your concentration lapse and feel the spell's energies dissipate.
>;burgle start rope
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>get my heavy rope 
What were you referring to?
>
[burgle]>tap my lockpick case 
You tap a darkly painted lockpick case depicting a pair of emerald-eyed panthers that you are wearing.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for burgle start lockpick, missing lockpick container:
```
>rem lock case
>
You remove a darkly painted lockpick case depicting a pair of emerald-eyed panthers from your belt.
>
You notice your augmented reflex slip away.
>put lock case in bramb
You put your case in your entangling brambles.
>close bramb
You quickly close some dense entangling brambles.
>
 * Thinker Crachim Khaldun joins the adventure.
>;burgle start lockpick
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>tap my lockpick case 
I could not find what you were referring to.
>
[burgle]>get my heavy rope 
You get a coil of heavy rope from inside your scavenger's pack.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
>
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for cycle with athletics higher mindstate:
```
>;burgle start
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>tap my lockpick case 
You tap a darkly painted lockpick case depicting a pair of emerald-eyed panthers that you are wearing.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for burgle cycle with locksmithing above athletics:
```
>;burgle start
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>stow right
You put your casket in your entangling brambles.
>
[burgle]>get my heavy rope 
You get a coil of heavy rope from inside your scavenger's pack.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```
log for prioritylockpick with locksmithing above athletics, but lower than threshold:
```
>;burgle start
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>stow right
You put your rope in your scavenger's pack.
>
[burgle]>tap my lockpick case 
You tap a darkly painted lockpick case depicting a pair of emerald-eyed panthers that you are wearing.
>
--- Lich: buff active.
[buff]>prepare symbiosis
You recall the exact details of the Avoid symbiosis, preparing to integrate it with the next spell you cast.
>
[buff]>release symbiosis
You pause for a moment as the details of the Avoid symbiosis fade from your mind.
You release the Avoid symbiosis.
>
[buff]>release spell
You let your concentration lapse and feel the spell's energies dissipate.
>
[buff]>release mana
You aren't harnessing any mana.
>
[buff]>prepare Blend 15
>;ka
--- Lich: burgle has exited.
--- Lich: buff has exited.
That won't affect your current attunement very much.
With tense movements you prepare your body for the Blend spell.
```

**Comment by Raykyn55** [comment]
log for missing both:
```
>;burgle start
--- Lich: burgle active.
[burgle: Pausing [] to run burgle]
[burgle]>open my scavenger's pack
That is already open.
>
[burgle]>burgle recall
You take a moment to think, you believe...
The heat has died down from your last caper.
>
[burgle]>tap my lockpick case 
I could not find what you were referring to.
>
[burgle]>get my heavy rope 
What were you referring to?
>
Couldn't find entry items: heavy rope and lockpick case are missing.
[burgle: Unpausing [], burgle has finished.]
--- Lich: burgle has exited.
```

**Comment by MahtraDR** [comment]
Can you resolve the conflicts, and we see what rubocop says. :)

**Pull request closed without merging**
