### PR TITLE
Adding hiding to the list of climbing. 

### PR DESCRIPTION
**Pull request by jayRyan24**
**This will fix issues with NPC's that point out people hiding and ruin the flow.

### CODE REVIEW

**Comment by rpherbig** [comment]
Looks good to me. Any comments @rcuhljr ?

**Comment by jayRyan24** [comment]
```
You run east.                                                                                                      
[Corik's Wall, Forward Battlements]                                                                                
The porous stone is worn by the ages, yet dark brown stains mar the parapets and wall walk.  They stubbornly defy  
  the weather and remain as silent monuments to the fallen who refuse to be forgotten.  You also see Captain of the
  Watch Grimnur and an onager.                                                                                     
Also here: Surgeon Gallifreius.                                                                                    
Obvious paths: north, east, west.                                                                                  
Room Number: 8905                                                                                                  
>                                                                                                                  
[go2: travel time: 0:01:25]                                                                                        
--- Lich: go2 has exited.                                                                                          
[crossing-training]>retreat                                                                                        
The Watch Grimnur discovers Gallifreius, ruining his hiding place!                                                 
>                                                                                                                  
You are already as far away as you can get!                                                                        
[crossing-training]>climb practice wall                                                                            
You begin to practice your climbing skills.                                                                        
>                                                                                                                  
Surgeon Gallifreius slouches east.                                                                                 
>                                                                                                                  
You feel fully rested.                                                                                             
>                                                                                                                  
You continue to practice your climbing skills.                                                                     
>                                                                                                                  
Surgeon Gallifreius just arrived.                                                                                  
>                                                                                                                  
The Watch Grimnur discovers Gallifreius, ruining his hiding place!                                                 
>                                                                                                                  
You continue to practice your climbing skills.                                                                     
>                                                                                                                  
The Watch Grimnur discovers Gallifreius, ruining his hiding place!                                                 
>                                                                                                                  
The Watch Grimnur discovers Gallifreius, ruining his hiding place!                                                 
>                                                                                                                  
The Watch Grimnur discovers Gallifreius, ruining his hiding place!                                                 
>                                                                                                                  
The Watch Grimnur discovers Gallifreius, ruining his hiding place!                                                 
>                                                                                                                  

```

**Comment by jayRyan24** [comment]
This could probably be put through, not sure what the wait is. Gall and others could use this.

**Comment by rcuhljr** [comment]
This broke crossing training for people using the branch for practice since that method call wasn't updated.

**Pull request merged**
