### PR TITLE
[script][maneuvers] Create maneuvers.lic

### PR DESCRIPTION
**Pull request by Raykyn55**
Neat little pvp helper, has a few yaml settings:
```yaml
    maneuvers_default_weapon_skill: Small Edged # The weapon you dance with
    maneuvers_powershot_weapon_skill: Crossbow # Powershot weapon, really only works with preloaded xbow
    maneuvers_reload: true # Whether to reload after a powershot. First load on startup by default, false means won't reload after a shot.
    maneuvers_doublestrike_skills:
    - Large Edged
    - Large Blunt
```
Basic idea is a script that handles weapon swaps and maneuver cooldowns during PVP, keeping track of cooldowns for each, notifying you when one comes off cooldown. Picks you up if you fall down. Has some implementation for warrior mage ele weapons, need adjustment for barbs.

 Engagement is via ;send
```
>;send impale
--- sent: impale
[maneuvers]>stow my cutlass
You put your cutlass in your thigh bag.
>
[maneuvers]>get my military.fork
You get a spiritwood and indurium military fork covered in spiraling demon gaze agates from inside your thigh bag.
>
[maneuvers]>maneuver impale
You angle to the side and prepare to impale your enemy.
Swiftly, you launch an assault with wide swipes of your fork!

Your military fork lands a powerful strike (10/23) to a zombie stomper's left hand!

[You're solidly balanced with opponent in good position.]
Roundtime: 3 sec.
>
The zombie stomper closes to pole weapon range on you!
>
[maneuvers]>stow my military.fork
...wait 1 seconds.
>
With a soft clumping sound, a mutant togball somersaults into view, rolling head over feet.  Eventually it stops and unfurls its body to survey its new surroundings.
>
[maneuvers]>stow my military.fork
The zombie stomper closes to melee range on you!
>
You put your fork in your thigh bag.
>
[maneuvers]>get my cutlass
* A zombie stomper grunts revoltingly and punches at you.  You block with a morgawr-scale targe.  
[You're winded, solidly balanced and opponent has slight advantage.]
>
You get a haralun cutlass from inside your thigh bag.
```
```
>;s list
--- sent: list
Time remaining on impale : 53.5662441
crash ready for use
cleave ready for use
twirl ready for use
powershot ready for use
palmstrike ready for use
doublestrike ready for use
suplex ready for use
```
after 54 seconds:
```
* A zombie stomper charges at you.  You block with a morgawr-scale targe.  
[You're solidly balanced with no advantage.]
>
impale now off cooldown
* A zombie stomper charges wide at you.  You dodge.  
[You're solidly balanced and in strong position.]
```

### CODE REVIEW

**Comment by Raykyn55** [comment]
TODO:
1. adjust cooldowns intelligently for barbs
2. add debil options
3. add tm options
4. add thrown with bonding
5. monitor pvp buffs

**Comment by Raykyn55** [comment]
Did a decent amount of testing, I don't think ACMs with elemental weapons is a viable strat, you rapidly run out of charge. Thinking make ele weapons a yaml array, let the user set their comfort level.

**Comment by Raykyn55** [comment]
TODO: add SK handling for super uber power shot

**Comment by Raykyn55** [comment]
Final version ready for testing:
- Scrapped elemental weapons for maneuvers, drains charge far too quickly. Perhaps HLC can sustain this? not sure.
- Rather than implementing SK for rangers, simply added a cooldown timer on it.
- Barb cooldown reduction handled via flag, sets to min reduction.
- Added spells, and additional yaml settings for each.

Potentially:
- hurl with bond
- list of essential buffs, simplify messaging in response to ward break, ward failure.

**Comment by asechrest** [comment]
Looks neat. I don't PVP. 

Can you add `parse_args` functionality, a `script_summary` arg, and the settings in `base-help.yaml`?

**Comment by Raykyn55** [comment]
> Looks neat. I don't PVP.
> 
> Can you add `parse_args` functionality, a `script_summary` arg, and the settings in `base-help.yaml`?

Donezo

**Comment by Raykyn55** [comment]
New yaml pattern:
```yaml
maneuvers_reload: true # Whether to reload after a powershot. First load on startup by default, false means won't reload after a shot.
maneuvers_tm_spell_and_mana: lb 15 # spell abbreviation/name and mana for targeted spell
maneuvers_aoe_spell_and_mana: starcrash 31 # spell abbrev/name and mana for aoe (tremors, starcrash, etc)
maneuvers_cyclic_spell_and_mana: ee 8 # spell abbrev/name and mana for cyclic (USOL, EE, etc)
maneuvers_debil_spell_and_mana: df 6 # spell abbrev/name and mana for debil
maneuvers_debil_prep_time: 2 # prep time for debil cast, 0 is snap cast, default is 5 seconds    
maneuvers_bonded_thrown_skill: Heavy Thrown # Only if this is bonded, uses hurl
maneuvers_bombo_list: # weapon skills for each maneuver
  default: Large Edged # Weapon you dance with, decent balance/damage
  impale: Polearms
  cleave: Large Edged
  crash: Small Blunt
  doublestrike: ["Large Edged", "Small Blunt"]
  twirl: Staves
  palmstrike:
  powershot: Crossbow
```
Removed grapple, suplex still present but not in bombo, assumes you're grappled.
fixed casting

**Pull request closed without merging**
