### PR TITLE
[scripts] [common-arcana] Adding missing reference to DRCMM

### PR DESCRIPTION
**Pull request by MahtraDR**
Found whilst testing removing them all that this one I'd missed.

without
```
 --- Lich: go2 has exited.                                                                                                                                                                                                                    
 --- Lich: outdoorsmanship active.                                                                                                                                                                                                            
 --- Lich: error: undefined method `set_moon_data' for #<Outdoorsmanship:0x0000560c4236d4c8>                                                                                                                                                  
 Did you mean?  setup_data                                                                                                                                                                                                                    
         common-arcana:743:in `crafting_prepare_spell'                                                                                                                                                                                        
         common-arcana:781:in `crafting_magic_routine'                                                                                                                                                                                        
 --- Lich: outdoorsmanship has exited.                                                                                                                                                                                                        
 You feel fully attuned to the mana streams again.     
```

With, no errors.

### CODE REVIEW

**Comment by MahtraDR** [comment]
This one is safe to merge now, since we copied the defs over a few days ago already, and we haven't removed from DRCA yet anyway.

**Comment by KatoakDR** [comment]
@MahtraDR should this PR also be updating https://github.com/rpherbig/dr-scripts/blob/eee8fb9259797c43d15b15b9c5fde765311db803/common-arcana.lic#L542 to use DRCMM?

**Comment by MahtraDR** [comment]
> @MahtraDR should this PR also be updating this line to use DRCMM?
> 
> https://github.com/rpherbig/dr-scripts/blob/eee8fb9259797c43d15b15b9c5fde765311db803/common-arcana.lic#L542

I didn't plan on it, because that line is going to disappear once we merge in https://github.com/rpherbig/dr-scripts/pull/5576

**Comment by KatoakDR** [comment]
> I didn't plan on it, because that line is going to disappear once we merge in #5576

Gotcha

**Comment by MahtraDR** [comment]
> > I didn't plan on it, because that line is going to disappear once we merge in #5576
> 
> Gotcha

Sorry, to make it clear, that line works in live now. The only reason I got the error is I am testing what happens when I remove all those defs later.

**Review by KatoakDR — APPROVED** [review]

**Pull request merged**
