### PR TITLE
Add researcher script

### PR DESCRIPTION
**Pull request by jandersson**
Adding a stand alone research script. This is a work-in-progress while more research topics are added (and the commit history is cleaned up).

### CODE REVIEW

**Comment by rpherbig** [comment]
> the commit history is cleaned up

Use the force push, Luke!

**Comment by jandersson** [comment]
Think that bput timeout test needs fixing

**Comment by khrispyb** [comment]
When running this it is using minimum Mana for GAF even though I have it as automana true in waggle for that spell. When researching in crossing training it uses my automana setting. Something I need to do differently to get it to use auto mana scale?

Separately, could we add research plane (astrology) to the list pls?

**Comment by rpherbig** [comment]
@jandersson any updates on this?

**Comment by jandersson** [comment]
I will close this until I feel like i want to focus on developing it or another stand alone research script gets merged.

The branch will still be there if someone wants to cherry-pick something from it.

**Pull request closed without merging**
