### PR TITLE
healme.lic - use waggle for hw and hs

### PR DESCRIPTION
**Pull request by Hazado**

### CODE REVIEW

**Comment by BinuDR** [comment]
This already uses a waggle set.
```waggle_sets:
  healing:
    Heal Wounds:
      mana: 5
      cambrinth:
      - 5
    Heal Scars:
      mana: 8
      cambrinth:
      - 8```

**Comment by Hazado** [comment]
No it uses empath_healing not waggle_sets for heal wounds and heal scars

**Comment by BinuDR** [comment]
Really?  I wonder which script I have that waggle set made for.

**Comment by BinuDR** [comment]
```    using_waggle = false
    spells = if @settings.waggle_sets['healing']
               using_waggle = true
               @settings.waggle_sets['healing']
             else
               @settings.empath_healing
             end

**Comment by Hazado** [comment]
Yes thats for regenerate and heal. For heal wounds and heal scars it doesnt use it

**Comment by BinuDR** [comment]
Ah, yeah I have both ways setup in my yaml.  That must be for a different script then.  My mistake.

**Pull request merged**
