### PR TITLE
Update base-recipes.yaml

### PR DESCRIPTION
**Pull request by nro2**
Ran into an issue where with 850 engineering and all shaping techs, no recipes were flagged true for workorders.  Changed some bows to true to fix the issue.

### CODE REVIEW

**Comment by Sarvatt** [comment]
have you tested the composite bows that need a bone backer to be sure they actually work?

**Comment by nro2** [comment]
I originally thought I had tested one with a bone backer.  Let me go and check, as of right now, forester’s bow does not work. I might go back and edit out anything that has a bone backer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Sarvatt** [comment]
I think shape.lic has a bug with combining parts on bows with a ' in the name, seem to remember running into that bug when i was manually adding workorder items

**Comment by nro2** [comment]
Oh, interesting.  I will try to get a workorder with a bow without a ‘ in it that uses bone backer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nro2** [comment]
Just successfully crafted a battle bow with a bone backer.  The error that I had with the forester's bow was at the beginning when it was entered arguments.  

Provided Arguments: 'log 4 "a forester's bow" maple bow'

It was well before the combine even occured, so maybe it was just an issue with the name.  Either way, it seems to work fine with bone backers.  I will go ahead and put false on anything that I changed with ' in the name.

**Comment by Sarvatt** [comment]
cool, thanks for that! Looks good to me with that change.

**Comment by nro2** [comment]
Should be good to go!  Thanks!

**Comment by rpherbig** [comment]
Thank you for your contribution @nro2 ! And for the review, @Sarvatt !

**Pull request merged**
