### PR TITLE
;performance support for things other than zills

### PR DESCRIPTION
**Pull request by Tarhish**
Could do a little more than this, but for now I added a worn_instrument variable that defaults to zills.

Resubmit to make Travis happier.

### CODE REVIEW

**Comment by rpherbig** [comment]
Do you plan to also update `athletics.lic`, `coordinator.lic`, or `crossing-training.lic`?

**Comment by Tarhish** [comment]
Yeah, might as well do that now while I've got it going.  The only thing I can't touch is ;play

**Comment by Tarhish** [comment]
I was busy the last couple days, but I actually want to commonize the cleaning and playing since I'm touching this.  Shouldn't be too long.

**Comment by Tarhish** [comment]
Yep, commonizing it worked better than expected.  I'm going to close this and submit the common changes after a few more tests, probably tomorrow.

**Pull request closed without merging**
