### PR TITLE
Lets you use an array of optional rooms.

### PR DESCRIPTION
**Pull request by jayRyan24**
```hunting_info:
- :zone:
  - void_moths
  - cabalist
  - archons
  args:
  - d0
  full_waiting_room:
  - 90210
  - 12345
  - 501
  stop_on:
  - Heavy Thrown
  stop_on_low:
  - Locksmithing
  - Athletics

### CODE REVIEW

**Comment by jayRyan24** [comment]
```
>;en DRCT.walk_to([791, 789, 792].sample)
--- Lich: exec1 active.
--- Lich: go2 active.
--- Lich: 'textsubs' has been stopped by go2.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>south
You go south.
[The Crossing, Town Green Southwest]
The hedgerow to the west meets the row of tall lunat trees that separates the Town Green from the commercial traffic on Lunat Shade Road due south.  The growth is especially dense here, with no way to slip past either of the living fences.  The small thorns on the hedges, to keep out stray livestock in search of prime pasture, look daunting in any case.  You also see the Town Pillory and a street urchin.
Obvious paths: north, northeast, east, west.
Room Number: 791
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: exec1 has exited.
>;en DRCT.walk_to([791, 789, 792].sample)
--- Lich: exec1 active.
--- Lich: exec1 has exited.
>;en DRCT.walk_to([791, 789, 792].sample)
--- Lich: exec1 active.
--- Lich: go2 active.
--- Lich: 'textsubs' has been stopped by go2.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>north
You go north.
[The Crossing, Town Green Northwest]
The entrance to Tembeg's Armory is through a hacked-out breach in the thick hedges that border the Green here.  Tembeg, being a humble sort, has laid down a few planks leading into his establishment to serve as a walkway.  Samples of his work are hung on hooks on the exterior of the unpainted wood structure but no sign or other eye-catching gimmicks are noticeable.  
Obvious paths: east, southeast, south, northwest.
Room Number: 789
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: exec1 has exited.
>;en DRCT.walk_to([791, 789, 792].sample)
--- Lich: exec1 active.
--- Lich: go2 active.
--- Lich: 'textsubs' has been stopped by go2.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>southeast
You go southeast.
[The Crossing, Town Green South]
A gap in the stand of lunat trees leads south into Lunat Shade Road.  In that general direction the lights shining from Berolt's Dry Goods, the Town Hall, the soaring presence of the Temple, the Provincial Bank and other key structures can be seen.  A few loafers loll on the grass, watching those entering and leaving the green, or laying back to gaze at the night sky.  A lone nightingale serenades from the hedges bordering the park, unaware of its appreciative audience.  You also see a town guard.
Obvious paths: north, northeast, east, south, west, northwest.
Room Number: 792
>
A town guard ambles east.
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: exec1 has exited.
>;en DRCT.walk_to([791, 789, 792].sample)
--- Lich: exec1 active.
--- Lich: go2 active.
--- Lich: 'textsubs' has been stopped by go2.
[go2: ETA: 0:00:00 (1 rooms to move through)]
[go2]>west
You go west.
[The Crossing, Town Green Southwest]
The hedgerow to the west meets the row of tall lunat trees that separates the Town Green from the commercial traffic on Lunat Shade Road due south.  The growth is especially dense here, with no way to slip past either of the living fences.  The small thorns on the hedges, to keep out stray livestock in search of prime pasture, look daunting in any case.  You also see the Town Pillory and a street urchin.
Obvious paths: north, northeast, east, west.
Room Number: 791
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
--- Lich: exec1 has exited.
```

**Comment by jayRyan24** [comment]
Sample also works with singles.
```
>;en arr = [1234]; echo arr.sample
--- Lich: exec1 active.
[exec1: 1234]
--- Lich: exec1 has exited.
>;en arr = [1234, 502, 332, 3394]; echo arr.sample
--- Lich: exec1 active.
[exec1: 502]
--- Lich: exec1 has exited.
```

**Comment by rpherbig** [comment]
@jayRyan24 Wait, I may have misread this...  sample does work with an array of size one, but aren't most of the calls to `walk_to` passing in an int and not an array?

**Comment by rpherbig** [comment]
Yeah, check these out: https://github.com/rpherbig/dr-scripts/blob/664cef0efb8809b33021bc7a0dd5f38e7bc20fa8/common-crafting.lic#L19 and https://github.com/rpherbig/dr-scripts/blob/664cef0efb8809b33021bc7a0dd5f38e7bc20fa8/common-crafting.lic#L54

I think you need the `sample` call to be in `hunting-buddy`, not `DRCT`.

**Pull request merged**
