### PR TITLE
Update combat-trainer.lic

### PR DESCRIPTION
**Pull request by Akhorishaan**
Corrected a variable check to make moonblades work again.

### CODE REVIEW

**Comment by rpherbig** [comment]
This conditional hasn't changed since May 2019. I'm curious how we only found/fixed this now.

@jandersson @Sarvatt @jayRyan24 any thoughts on this change?

cc @KatoakDR @BinuDR

**Comment by KatoakDR** [comment]
Hi @Akhorishaan, thanks for contributing to the Lich script repository. Could you share the pertinent pieces of your logs where combat-trainer is skipping using your summoned weapon? And, would you please share a copy of your character's yaml file, it can aid with us testing the change and seeing if we can reproduce the problem.

Thanks!

**Comment by Akhorishaan** [comment]
Of course, of course.  This probably wasn't fixed for so long because it's a niche application and nobody uses moonblade but me and maybe two other people, so there's no pressure to fix the problem.

**Comment by KatoakDR** [comment]
Thanks, we'll take a look and follow up

**Comment by KatoakDR** [comment]
> noticed that it was skipping summoned weapons every time it looked for a new weapon to train

Yes, I'm seeing this, too. Investigating...

**Comment by Akhorishaan** [comment]
Oh yeah, I see that now, it's only nil when it isn't in your hand, but if it is in your hand then it is populated with the moon.  Which explains why if you grab the moonblade manually with the original version of the script, it'll go through a cycle of using each type before forgetting it exists again.  May just have to add a separate variable that doesn't change based on what is in your hands, as you mentioned.

**Comment by KatoakDR** [comment]
> May just have to add a separate variable that doesn't change based on what is in your hands, as you mentioned. Like just something that gets set once whenever a new moonblade is summoned.

Yep! Trying that out right now :)

**Comment by KatoakDR** [comment]
I got it working by tracking its own variable for the last moon used. Polishing up the changes and will submit a PR. Thanks

**Comment by rpherbig** [comment]
The logic in `moon_used_to_summon_weapon` changed only a few months ago in PR #4473 - maybe that's related

**Comment by KatoakDR** [comment]
> The logic in `moon_used_to_summon_weapon` changed only a few months ago in PR #4473 - maybe that's related

Good catch, and apologies that I introduced the issue.

At the time I submitted that earlier PR, we weren't sure how many name variants a moon* weapon could have -- but seems it's either a `moonblade` or a `moonstaff` so we may be able to revert that method to not rely on looking at someting **in your hands** but rather if the game is able to glance at a `moon(blade|staff)`. The original "glance moon" was insufficient because wearing jewelry or other items whose noun is "moon" would cause issues.

I went to bed last night before submitting my PR that tracks the moon that the moonblade spell was cast on. Might be useful to have both changes?

**Comment by KatoakDR** [comment]
OK, before we modify `combat-trainer`, I've submitted enhancements to `common-summoning` and `common-moonmage` to better handle the detection and holding of moon weapons. Once those are merged let's continue to test combat-trainer as-is to see if that resolves our issue. If not, we can move forward with adding an internal variable to `game_state` to keep track of the moon used when moonblade spell is cast. Thanks!

* https://github.com/rpherbig/dr-scripts/pull/4744 - fixes bug where you had to be holding the moon weapon to detect the moon used
* https://github.com/rpherbig/dr-scripts/pull/4745 - simplifies logic for taking hold of a moon weapon

**Comment by KatoakDR** [comment]
@rpherbig This PR  can be closed as it was superceded by the following merged PRs:
* #4744 - fixes bug where you had to be holding the moon weapon to detect the moon used
* #4745 - simplifies logic for taking hold of a moon weapon
* #4746 - adds clarifying comments to combat-trainer when using moonblade spell

Thanks!

**Pull request closed without merging**
