### PR TITLE
update base.yaml - add other outfit tools

### PR DESCRIPTION
**Pull request by BinuDR**
Added more outfitting tools to the base list.

### CODE REVIEW

**Comment by Sarvatt** [comment]
is this ok if you only having knitting needles? it was only knitting on purpose for the first 401 ranks, making everyone buy the full set and repair them by default doesn't seem right

**Comment by Sarvatt** [comment]
which leads to people missing tools when they repair in another craft script oddly enough

**Comment by BinuDR** [comment]
If you only have knitting needles, just override this in your yaml with
outfitting_tools:
  - knitting needles

I'm not sure how it would behave if you try to repair when you only have needles without overriding it.

**Comment by Sarvatt** [comment]
1-401 ranks is the vast majority of the user base imo, defaults that work out of the box for them is what i was concerned about

**Comment by BinuDR** [comment]
I'll test it and see what happens.

**Comment by Sarvatt** [comment]
;workorder outfitting repair with only knitting needles should be all it needs to test

**Pull request merged**
