### PR TITLE
[script][forge] Ingot handling

### PR DESCRIPTION
**Pull request by Raykyn55**
Adds the metal-type ingot to your bag items before fetching, so that it always fetches from your crafting container, instead of grasping at any ol' metal-type ingot you might be carrying.

### CODE REVIEW

**Comment by Raykyn55** [comment]
same issue as sew, though likely unfixable. Game is coded to automatically default stow any spare metal after the first pound into default bag.

**Comment by Dartellum** [comment]
> same issue as sew, though likely unfixable. Game is coded to automatically default stow any spare metal after the first pound into default bag.

Perhaps you can capture where the game stowed the metal and then use `transfer-items` or just code it in to move that metal back to the crafting container.

**Comment by Raykyn55** [comment]
> 

not a bad idea, catch the bag iwth a flag maybe, and compare the flag with the crafting container, resolve in finish method?

**Comment by Raykyn55** [comment]
Eventually I think we'll need to determine what your default bag is, and make that information available to these scripts. Either a yaml setting (pita) or ideally something in dependency.

**Pull request closed without merging**
