### PR TITLE
Updating my YAMLS.

### PR DESCRIPTION
**Pull request by jayRyan24**
Adding in new characters, Jardani and Sseng as well.

### CODE REVIEW

**Comment by jayRyan24** [comment]
I'll fix this in a bit.

**Comment by jayRyan24** [comment]
Is this failing due to issues with the old files?

**Comment by Sarvatt** [comment]
It's failing because there are settings not in base.yaml like buff_spells_force_cambrinth

-["training_list", "maf", "sap", "pom", "sl", "bene", "mpp", "mapp", "center", "bless", "pfe", "mf", "hyh", "ghs", "rej", "rez", "dr", "buffs", "magic_training", "buff_spells_force_cambrinth", "lockpick_ignore_diffi1culty", "picking_pet_boxes_on_hand", "shadowling", "shad", "pg", "cv", "psy"]

**Comment by Sarvatt** [comment]
you can just add them to the test ignore list like all your other dudes

https://github.com/rpherbig/dr-scripts/blob/master/test/test_valid_yaml.rb#L19

**Comment by jayRyan24** [comment]
AH ok, thanks @Sarvatt for the explanation. I forgot all about that, and didn't even know you could go further into that. Thanks!

**Pull request merged**
