### PR TITLE
[script][common-arcana]adding methods for checking symbiotic research and releasing magical research

### PR DESCRIPTION
**Pull request by Valherun**
update common-arcana to support 2 methods needed by upcoming researcher.lic and check-symbiosis.lic

### CODE REVIEW

**Comment by Valherun** [comment]
I wasn't sure of the best way to make changes to common-arcana that are required for this PR (addition of 2 functions). 

So I did them separately, let me know if it would be better to do them all together in the future.

**Review by KatoakDR — APPROVED** [review]

**Comment by KatoakDR** [comment]
FYI @rpherbig, Valherun wrote and proposed a new script in Lich discord. I [shared my feedback](https://discord.com/channels/745675889622384681/745696628714897508/939773028424896552) and said we'd need 3 PRs:
1. This one for the methods I thought made sense for common-arcana
2. The "researcher" script that's in Lich's repository so we have it on GitHub. Briarleigh is also helping merge their changes for that proposal. 
3. The actual new script "check-symbiosis"

**Comment by Valherun** [comment]
might of done only 2 PR's with both the new researcher and check-symbiosis /ducks

**Comment by rpherbig** [comment]
Looks good, and I think the two PR approach makes sense

**Pull request merged**
