### PR TITLE
Duskruin 422 Labyrinth

### PR DESCRIPTION
**Pull request by jandersson**
Working draft. Another user reported that this caught a rat

### CODE REVIEW

**Comment by jandersson** [comment]
#1490 should be what you need

**Comment by jandersson** [comment]
Should work for #1489

**Comment by rpherbig** [comment]
I think it would be nice to add the header block with a link to elanthipedia (and add some documentation there), but that won't hold up merging this.

**Comment by jandersson** [comment]
Great! I will add this. How does it work if this is already merged? Do I create a new branch for updates or can i just push to this same branch?

**Comment by jandersson** [comment]
I've pushed new changes to this same branch. I'm going to try out this 'revert' button.. let me know if you want me to do this another/a better way

**Comment by jandersson** [comment]
Not what I wanted! OK, new branch it is

**Pull request merged**
