### PR TITLE
[scripts][common]Improved handling for being immobilized, or stunned, or webbed.

### PR DESCRIPTION
**Pull request by MahtraDR**
As per title, and suggested by Raykyn55 https://github.com/rpherbig/dr-scripts/pull/6408#issuecomment-1438690967

Would it make sense to do something like this for the handling being stunned too? Something like

```ruby
      when /^You are still stunned/
      next if stunned?
```

### CODE REVIEW

**Comment by MahtraDR** [comment]
@Raykyn55 Whatcha think?

**Comment by MahtraDR** [comment]
Ah, we'd need a recovery condition. Thinking...

**Comment by Raykyn55** [comment]
This is what I'm running as of this morning:
```ruby
      when /^You can't do that while entangled in a web/
        while webbed? do pause 0.1 end
        put message
        timer = Time.now
        next
      when /^You are still stunned/, 
        while stunned? do pause 0.1 end
        put message
        timer = Time.now
        next
```
For some reason pause 0.1 while webbed? threw an error, which is a new one. This seems to work though.

**Comment by Raykyn55** [comment]
for a more permanent solution, at least specifically for IP, there does appear to be xml indicators for IP:
```
<prompt time="1677007261">IP&gt;</prompt>
```
which when it falls off becomes: 
```
<prompt time="1677007262">P&gt;</prompt>
```
combat indicators by style, but I can't figure out what to do with them wrt capturing. I can't find XMLData to add it, nor would I know how to capture that if I did.

**Comment by MahtraDR** [comment]
> for a more permanent solution, at least specifically for IP, there does appear to be xml indicators for IP:
> 
> ```
> <prompt time="1677007261">IP&gt;</prompt>
> ```
> 
> which when it falls off becomes:
> 
> ```
> <prompt time="1677007262">P&gt;</prompt>
> ```
> 
> combat indicators by style, but I can't figure out what to do with them wrt capturing. I can't find XMLData to add it, nor would I know how to capture that if I did.

That's not an actual xml indicator. What that is updating is the prompt, which not everyone has set. `set StatusPrompt` by contrast, the stunned xml indicator is extremely verbose, and specific (and always happens*)

**Comment by MahtraDR** [comment]
> This is what I'm running as of this morning:
> 
> ```ruby
>       when /^You can't do that while entangled in a web/
>         while webbed? do pause 0.1 end
>         put message
>         timer = Time.now
>         next
>       when /^You are still stunned/, 
>         while stunned? do pause 0.1 end
>         put message
>         timer = Time.now
>         next
> ```
> 
> For some reason pause 0.1 while webbed? threw an error, which is a new one. This seems to work though.

`webbed?` is a status in lich, but from GS. We don't get that in our XML stream in DR. I'd leave the old behaviour for webbing.

**Comment by Raykyn55** [comment]
> 
```
<indicator id='IconWEBBED' visible='y'/>Reonin gestures at you.

<pushStream id="combat" />A thousand tiny spiders crawl out of their hiding places and begin crawling over you, trapping you in a cocoon of sticky webbing!
```

It's the little green symbol that shows up in wrayth. The lich method for capturing both is via indicator(XMLData.indicator shows the full list)

**Comment by MahtraDR** [comment]
> > 
> 
> ```
> <indicator id='IconWEBBED' visible='y'/>Reonin gestures at you.
> 
> <pushStream id="combat" />A thousand tiny spiders crawl out of their hiding places and begin crawling over you, trapping you in a cocoon of sticky webbing!
> ```
> 
> It's the little green symbol that shows up in wrayth. The lich method for capturing both is via indicator(XMLData.indicator shows the full list)

!!! That's new!!! That's amazing! 

One thing to note about these, they're only mostly reliable :) The stun from getting your hand chopped off burgling wasn't registering in the XML for a long time, for example.

**Comment by MahtraDR** [comment]
I've kept the `pause 0.5` line in case we encounter a situation where the stun/webbing isn't registering in the XML, but the game still says we're webbed/stunned. At worse we lose half a second. This should take care of the spam though.

**Comment by MahtraDR** [comment]
This version is running really well now.

**Comment by MahtraDR** [comment]
Resolves https://github.com/rpherbig/dr-scripts/issues/3395 for realsies.

**Pull request merged**
