### PR TITLE
Refactoring play.lic

### PR DESCRIPTION
**Pull request by jandersson**
* Uses DRC.play_song?

I have one reservation on using this common method: It looks like it can
run safe-room which I don't believe we want an 'always on' script to do.

* Invert xp predicate

* Add no_play scripts to base and base-empty

### CODE REVIEW

**Comment by jandersson** [comment]
Have marked this as a WIP/Draft while thinking about the safe-room issue with `DRC.play_song?`. May revert this back to fput.

**Comment by rpherbig** [comment]
I'm fine either way. Have you considered adding _yet another_ optional arg to `play_song?`?

**Comment by jandersson** [comment]
> I'm fine either way. Have you considered adding _yet another_ optional arg to `play_song?`?

Yep :) currently considering this now. I think at some point we possibly want `play_song?` broken up so the individual components are a bit more accessible.

**Comment by jandersson** [comment]
Ill cherry-pick the common changes into a separate PR, then remove the draft marker on this one

**Comment by jandersson** [comment]
I'll re-open this when I have an active account.

**Pull request closed without merging**
