### PR TITLE
[script][common-crafting] Add consumables check to common crafting

### PR DESCRIPTION
**Pull request by Raykyn55**
This is a follow-on from a discussion with Dart, a DRAFT of a potential centrally handled consumables check for the grunt scripts forge, shape, sew, etc. Called with a good deal of information, some of which is not currently fetched by these scripts, so that information will need to be added in initialize:
```
crafting_data = get_data('crafting')
@info = crafting_data['blacksmithing'][@hometown]
```
adapted to other disciplines per script. This is then called as:
```
DRCC.check_consumables('oil', @info['finisher-room'], @info['finisher-number'], @bag, @bag_items, @forging_belt)
```
I'd probably call it before studying the book, but could be done earlier. 

```
>;forge blacksmithing 6 "metal crown" steel crown
--- Lich: forge active.
--- Lich: buff active.
No waggle set found for name: forge
--- Lich: buff has exited.
[forge]>get my oil
What were you referring to?
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>go building
>
[Crossing Forging Society, Book Store]
Freshly chiseled granite walls surround an area where forgers can quickly resupply.  A passageway covered by a leather flap pierces the wall to the south, and from the passage resound the clangs of an anvil chorus.  A simple wooden door leads back outside.  You also see a large sign and a prestige board.
Also here: Brother Markolf.
Obvious exits: south.
Room Number: 8771
Room Exits: go door
>
[go2]>south
[go2]>east
You go south.
[Crossing Forging Society, Lobby and Maker's Mark Ordering]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a blacksmithing chart hanging from the wall, a weaponsmithing chart hanging from the wall, an armorsmithing chart hanging from the wall and a large sign.
Obvious exits: north, east, south, west.
Room Number: 8772
>
You go east.
[Crossing Forging Society, Tool Store]
Masters and journeyman of the forging craft find a home in this room purchasing tools and ingredients.  Loud thumps and groaning accompany the loading and unloading of goods from storage.  You also see a clerk, a sturdy low counter with a small placard on it, a large sign and a steel crate.
Also here: Bloodluster Brutoc.
Obvious exits: north, south, west.
Room Number: 8776
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[forge]>order 6
The attendant says, "You can purchase a flask of oil for 1,000 Kronars.  Just order it again and we'll see it done!"
>
[forge]>order 6
The attendant takes some coins from you and hands you a flask of oil.
>
[forge]>put my oil in my backpack
You put your oil in your backpack.
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>west
You go west.
[Crossing Forging Society, Lobby and Maker's Mark Ordering]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a blacksmithing chart hanging from the wall, a weaponsmithing chart hanging from the wall, an armorsmithing chart hanging from the wall and a large sign.
Obvious exits: north, east, south, west.
Room Number: 8772
>
[go2]>north
[go2]>go door
You go north.
[Crossing Forging Society, Book Store]
Freshly chiseled granite walls surround an area where forgers can quickly resupply.  A passageway covered by a leather flap pierces the wall to the south, and from the passage resound the clangs of an anvil chorus.  A simple wooden door leads back outside.  You also see a large sign and a prestige board.
Also here: Brother Markolf.
Obvious exits: south.
Room Number: 8771
Room Exits: go door
>
[The Crossing, Trothfang Street]
Due north you see the square that marks the entrance to the Barbarians' Guild, with its arcade of caryatides and telamones, life-size and lifelike sculptures of former female and male Arena Champions.  The covered entryway to the Arena is dead ahead to the east, while beyond that rise the town walls.  You also see a flask of oil, a flask of oil, a flask of oil, a glowing forge, a large waste bucket, a slack tub filled with water, a pile of fuel, an iron anvil and the Crossing Forging Society Building.
Obvious paths: north, east.
Room Number: 760
Room Exits: go building
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[forge]>get my blacksmithing book
You get a book of master blacksmithing instructions from inside your backpack.
>
[forge]>turn my book to chapter 6
You turn your book to chapter 6, entitled "Forged Item Design".
>
[forge]>read my book
              -=    Chapter 6 : Forged Item Design    =-

 Page 1: a shallow metal cup                     Page 18: a metal lockpick ring
 Page 2: a metal rod                             Page 19: a metal herbal case
 Page 3: a tall metal mug                        Page 20: a metal jewelry box
 Page 4: a short metal mug                       Page 21: a metal flights box
 Page 5: a soft metal keyblank                   Page 22: a metal razor
 Page 6: a metal horseshoe                       Page 23: a large metal flask
 Page 7: a back scratcher                        Page 24: a metal armband
 Page 8: some metal barbells                     Page 25: a metal instrument case
 Page 9: a large metal horseshoe                 Page 26: a metal chest
 Page 10: a small metal flask                    Page 27: a metal backtube
 Page 11: a metal ankle band                     Page 28: a metal starchart tube
 Page 12: a metal lockpick case                  Page 29: some metal clippers
 Page 13: a metal origami case                   Page 30: a metal crown
 Page 14: a metal bolt box                       Page 31: a metal torque
 Page 15: a metal talisman case                  Page 32: a metal mask
 Page 16: a metal flask                          Page 33: a metal headdress
 Page 17: a metal oil lantern                    
>
[forge]>turn my book to page 30
You turn your book to page 30, instructions for crafting a metal crown.
>
[forge]>study my book
You review the crown instructions and completely understand all facets of the design.
You now feel ready to begin the crafting process.
Roundtime: 10 sec.
>;ka
--- Lich: forge has exited.
```
```
>;forge blacksmithing 6 "metal crown" steel crown
--- Lich: forge active.
--- Lich: buff active.
No waggle set found for name: forge
--- Lich: buff has exited.
[forge]>get my oil
You get a flask of oil from inside your backpack.
>
[forge]>count my oil
The oil has 50 uses remaining.
>
[forge]>put my oil in my backpack
You put your oil in your backpack.
>
[forge]>get my blacksmithing book
You get a book of master blacksmithing instructions from inside your backpack.
>
[forge]>turn my book to chapter 6
You turn your book to chapter 6, entitled "Forged Item Design".
>
[forge]>read my book
              -=    Chapter 6 : Forged Item Design    =-

 Page 1: a shallow metal cup                     Page 18: a metal lockpick ring
 Page 2: a metal rod                             Page 19: a metal herbal case
 Page 3: a tall metal mug                        Page 20: a metal jewelry box
 Page 4: a short metal mug                       Page 21: a metal flights box
 Page 5: a soft metal keyblank                   Page 22: a metal razor
 Page 6: a metal horseshoe                       Page 23: a large metal flask
 Page 7: a back scratcher                        Page 24: a metal armband
 Page 8: some metal barbells                     Page 25: a metal instrument case
 Page 9: a large metal horseshoe                 Page 26: a metal chest
 Page 10: a small metal flask                    Page 27: a metal backtube
 Page 11: a metal ankle band                     Page 28: a metal starchart tube
 Page 12: a metal lockpick case                  Page 29: some metal clippers
 Page 13: a metal origami case                   Page 30: a metal crown
 Page 14: a metal bolt box                       Page 31: a metal torque
 Page 15: a metal talisman case                  Page 32: a metal mask
 Page 16: a metal flask                          Page 33: a metal headdress
 Page 17: a metal oil lantern                    
>
[forge]>turn my book to page 30
You turn your book to page 30, instructions for crafting a metal crown.
>
[forge]>study my book
You review the crown instructions and completely understand all facets of the design.
You now feel ready to begin the crafting process.
Roundtime: 10 sec.
```

Interested in thoughts/tests!

### CODE REVIEW

**Comment by Dartellum** [comment]
We probably do not need this, if called from the "grunt" script: 
```ruby
    when 'You get'
      /(\d+)/ =~ DRC.bput("count my #{name}", 'The .* has (\d+) uses remaining')
      if Regexp.last_match(1).to_i < 3
        DRCT.dispose(name)
        DRCT.order_item(room, number)
      end
```

As we can then consume the entire product, polish, pins, glue, etc, without worrying about obtaining before hand. Also, we could then remove the check in `workorders.lic` for the same.

**Comment by Dartellum** [comment]
I also found `def turn_to` is not called in `forge.lic`.

**Comment by Dartellum** [comment]
I changed it to this:
```ruby
  def check_consumables(name, room, number, bag, bag_items, belt)
    current = Room.current.id
    DRCT.order_item(room, number) if DRC.bput("get my #{name} from my #{bag}", 'You get', 'What were') == 'What were'
    DRCC.stow_crafting_item(name, bag, belt)
    DRCT.walk_to(current)
  end
```

**Comment by Raykyn55** [comment]
> I changed it to this:
> 
> ```ruby
>   def check_consumables(name, room, number, bag, bag_items, belt)
>     current = Room.current.id
>     DRCT.order_item(room, number) if DRC.bput("get my #{name} from my #{bag}", 'You get', 'What were') == 'What were'
>     DRCC.stow_crafting_item(name, bag, belt)
>     DRCT.walk_to(current)
>   end
> ```

So instead of checking ahead of time, it just assumes you have them. Then when it goes to swap, if you DON"T, it'll run to the craft shop, buy more, then run back. I can see the logic, and the avoidance of waste, but i do see a couple potential issues:

1. Some folks, myself in particular, don't craft in the societies (forge notwithstanding) This means a potentially lengthly trip mid-craft. I'd kind of prefer having it upfront.

Leaving that aside:

2. This would have to be called as the "get" (order x unless you get x), and the script would assume you now have it in hand. So we either remove the line 4 stow above, or this resends the get command at the end of the method (eg add the conditional after the walk_to.)
```ruby
   def check_consumables(name, room, number, bag, bag_items, belt)
     current = Room.current.id
     DRCT.order_item(room, number) if DRC.bput("get my #{name} from my #{bag}", 'You get', 'What were') == 'What were'
     DRCC.stow_crafting_item(name, bag, belt)
     DRCT.walk_to(current)
     DRC.bput("get my #{name} from my #{bag}", 'You get')
   end
   ```

Like to discuss pros and cons of 1.

**Comment by Dartellum** [comment]
> 

I do not either, except for sewing for some reason (I need to recall why). Forging you do in Society or personal forge or portable. 
```
2022-07-13 17:55:20 -0400:You lean the short-hafted halberd against the grindstone and begin to sharpen its many edges. Afterwards you sharpen the halberd's points and apply a nice polish to the metal's surface.
2022-07-13 17:55:21 -0400:With grinding complete, the metal now needs protection by pouring oil on it.
2022-07-13 17:55:21 -0400:Roundtime: 19 sec.
2022-07-13 17:55:22 -0400:You feel fully rested.
2022-07-13 17:55:39 -0400:[forge]>get my oil from my embroidered backpack
2022-07-13 17:55:39 -0400:You get a flask of oil from inside your embroidered backpack.
2022-07-13 17:55:39 -0400:[forge]>put my oil in my embroidered backpack
2022-07-13 17:55:39 -0400:You put your oil in your embroidered backpack.
2022-07-13 17:55:39 -0400:[forge]>get my oil
2022-07-13 17:55:40 -0400:You get a flask of oil from inside your embroidered backpack.
2022-07-13 17:55:40 -0400:[forge]>pour my oil on my halberd
2022-07-13 17:55:40 -0400:After applying some of the oil to the rag, you vigorously buff several rough spots on the short-hafted halberd and spread the protective sheen across the metal's surface.
2022-07-13 17:55:40 -0400:Roundtime: 19 sec.
2022-07-13 17:55:40 -0400:Applying the final touches, you complete working on a steel short-hafted halberd.
2022-07-13 17:55:42 -0400:The grindstone begins to lose momentum.
```

So, pros, you do not waste any oil, particularly if you purchased special from HE (or some fest) and now not throwing it away accidentally if you forgot to move it out of location used for oil. 

I do see the movement if not near the Society as a possible nuisance. Although, I do not mind the moving as I can get anywhere walking or swimming within 30 seconds or less. Ratha and the Island are not in that... 

However, we could have the check at the beginning and in the routine itself so the item is completed in the event you run out mid crafting. 

As for the double get, yes, can remove the stow command.

**Comment by Raykyn55** [comment]
So I like the idea of a catch in case the oil/polish/etc is out, but I'm concerned with rewriting the method for exactly that possibility.  What about making this change inside of forge, using skip_exit for just the consumables, then a catch for use (Pour what):
```
>;forge resume blacksmithing crown
--- Lich: forge active.
--- Lich: buff active.
No waggle set found for name: forge
--- Lich: buff has exited.
[forge]>look on anvil
>
On the iron anvil you see an unfinished steel crown.
>
[forge]>release mana
You aren't harnessing any mana.
>
[forge]>prepare symbiosis
But you've already prepared the Chaos symbiosis!
>
[forge]>prepare NON 15
You raise your palms skyward, chanting the equation of the Nonchalance spell.
>
[forge]>analyze crown on anvil
You thoroughly analyze the crown, revealing some of its secrets.
When crafting is complete this will be a type of finished metal head jewelry.
Although finished, the metal will quickly rust and wear if not properly protected.  POUR OIL on the crown to complete the forging process.
From the progress so far, it looks like the crown is masterfully-crafted (12/12).
The crown is an intricate piece to make.
Roundtime: 7 sec.
>
[forge]>get my oil
...wait 1 seconds.
>
[forge]>get my oil
What were you referring to?
>
[forge: ]
[forge: You seem to be missing: oil]
[forge]>get crown on anvil
You get an unfinished steel crown from atop an iron anvil.
>
[forge]>swap
You move an unfinished steel crown to your left hand.
>
[forge]>pour my oil on my crown
Pour what?
>
[forge]>get my oil
What were you referring to?
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>go building
[Crossing Forging Society, Book Store]
Freshly chiseled granite walls surround an area where forgers can quickly resupply.  A passageway covered by a leather flap pierces the wall to the south, and from the passage resound the clangs of an anvil chorus.  A simple wooden door leads back outside.  You also see a large sign and a prestige board.
Also here: Mathematician Avrenka.
Obvious exits: south.
Room Number: 8771
Room Exits: go door
>
[go2]>south
[go2]>east
You go south.
[Crossing Forging Society, Lobby and Maker's Mark Ordering]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a blacksmithing chart hanging from the wall, a weaponsmithing chart hanging from the wall, an armorsmithing chart hanging from the wall and a large sign.
Obvious exits: north, east, south, west.
Room Number: 8772
>
You go east.
[Crossing Forging Society, Tool Store]
Masters and journeyman of the forging craft find a home in this room purchasing tools and ingredients.  Loud thumps and groaning accompany the loading and unloading of goods from storage.  You also see a clerk, a sturdy low counter with a small placard on it, a large sign and a steel crate.
Obvious exits: north, south, west.
Room Number: 8776
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[forge]>order 6
The attendant says, "You can purchase a flask of oil for 1,000 Kronars.  Just order it again and we'll see it done!"
>
[forge]>order 6
The attendant takes some coins from you and hands you a flask of oil.
>
[forge]>put my oil in my backpack
>
You put your oil in your backpack.
>
--- Lich: go2 active.
[go2: ETA: 0:00:00 (3 rooms to move through)]
[go2]>west
You go west.
[Crossing Forging Society, Lobby and Maker's Mark Ordering]
A chamber with stone walls and a lofty, vaulted ceiling links the rooms of the forge.  Its high arches help to subdue the clangor, letting it rise and echo in the space overhead.  Waves of heat and flickering reddish light from the foundries to the west strive with the scream of the grindstones to the east and the pounding din of metal on metal from the smithies to the south.  You also see a blacksmithing chart hanging from the wall, a weaponsmithing chart hanging from the wall, an armorsmithing chart hanging from the wall and a large sign.
Obvious exits: north, east, south, west.
Room Number: 8772
>
[go2]>north
[go2]>go door
You go north.
[Crossing Forging Society, Book Store]
Freshly chiseled granite walls surround an area where forgers can quickly resupply.  A passageway covered by a leather flap pierces the wall to the south, and from the passage resound the clangs of an anvil chorus.  A simple wooden door leads back outside.  You also see a large sign and a prestige board.
Also here: Mathematician Avrenka.
Obvious exits: south.
Room Number: 8771
Room Exits: go door
>
[The Crossing, Trothfang Street]
Due north you see the square that marks the entrance to the Barbarians' Guild, with its arcade of caryatides and telamones, life-size and lifelike sculptures of former female and male Arena Champions.  The covered entryway to the Arena is dead ahead to the east, while beyond that rise the town walls.  You also see a glowing forge, a large waste bucket, a slack tub filled with water, a pile of fuel, an iron anvil and the Crossing Forging Society Building.
Obvious paths: north, east.
Room Number: 760
Room Exits: go building
>
[go2: travel time: 0:00:00]
--- Lich: go2 has exited.
[forge]>get my oil
You get a flask of oil from inside your backpack.
>
[forge]>pour my oil on my crown
After applying some of the oil to the rag, you vigorously buff several rough spots on the crown and spread the protective sheen across the metal's surface.
Roundtime: 30 sec.
Applying the final touches, you complete working on a steel crown.
```
Reasons for this over yours:
1. Original method still works to count at the start, so for things like pins we aren't setting ourselves up for failure by only having 1 use, which was the whole reason we have this check to begin with.
2. We don't have to change how the method handles the oil, as it's current use checks then stows, which is ideal for a beginning check, less so for getting it later. 

In the end, it's 6 of one, half a dozen of the other, but I think these are changes that properly belong in forge, and in the unlikely event that we use more than 3 of a consumable for a single item, we can call that method in the case statement. I'll DM you a copy of forge with the changes I think make sense.

**Pull request merged**
