### PR TITLE
Updating shape to not grab 'leather cord'

### PR DESCRIPTION
**Pull request by izawwlgood**
Correct cord is 'short cord' or just 'cord'.

### CODE REVIEW

**Comment by Tarhish** [comment]
The regex looks like it'll match 'cord' or 'strip' just fine, but it also looks like the if args.continue line accidentally got the axe.  I'll swap it in though, and try it out.

**Comment by rpherbig** [comment]
Yeah, ❓ what happened to `args.continue`?

**Comment by Dartellum** [comment]
Does it need the double parentheses: **(**(?:strip|cord)**)**?

**Comment by Dartellum** [comment]
I put the change in my file and am testing. I have the `if args.continue` in mine.

**Comment by rpherbig** [comment]
There is a merge conflict in `shape.lic`

**Comment by jandersson** [comment]
Hey folks, this has been open for over a year. No disrespect meant but please re-open this if you want to continue.

**Pull request closed without merging**
