### PR TITLE
[script] [combat-trainer] Advanced Combat Maneuvers

### PR DESCRIPTION
**Pull request by KatoakDR**
## Dependencies
* Depends on https://github.com/rpherbig/dr-scripts/pull/5076

### Background
* "Charged Combat Maneuvers" were changed to "Advanced Combat Maneuvers" ([forum post](https://elanthipedia.play.net/Post:Charged_Combat_Maneuvers_-_07/07/2021_-_00:32), [wiki page](https://elanthipedia.play.net/Combat_maneuvers#Advanced_Combat_Maneuvers)).
* Without the need for the ramp up time https://github.com/rpherbig/dr-scripts/pull/5069, they are more viable to be part of regular combat routines, especially for Barbarians who have high likelihoods of reducing the 90 second cooldown to 60 seconds.
* Continuation of https://github.com/rpherbig/dr-scripts/pull/5044, which introduced prioritizing doublestrikes maneuvers.

### Changes
* Add new setting `doublestrike_trainables` to define which mainhand weapon skills you want to use when attempting doublestrikes. This lets you, for example, opt out of trying (and failing) doublestrikes with staves if you use a quarterstaff (two-handed) instead of a short staff (one-handed). Same with polearms like halberds vs. light spears.
* For the true combat maneuver enthusiast, including suggested YAML configuration below for how to perform maneuvers frequently.
* When prioritizing doublestrikes, if that specific maneuver is on cooldown then fallback to trying the specific maneuver for the mainhand weapon, and if that maneuver is on cooldown then do regular attack.
* When tracking cooldowns for each combat maneuver, detect when Barbarians reduce their cooldown so that the maneuver will be attempted sooner rather than later.
* Support dual loading with powershot maneuver. Powershot will only fire one arrow from a dual loaded bow, so in these scenarios to not waste the other arrow, the script will perform the second shot immediately.
* Format `@skill_map` to be (subjectively) more readable and maintainable.

### Configuration
<details>
<summary>toggle sample configuration</summary>

```yaml
training_abilities:
  Charged Maneuver:
    # By default, maneuvers are performed as long as the Expertise skill needs training.
    # To make combat maneuvers a regular attack in your routine, set the :check: property to a
    # non-existant skill that'll never reach the value of combat_training_abilities_target.
    :check: Always
    # Also, since every maneuver type has its own cooldown (e.g. you can 'cleave' then 'crash'
    # back to back but then have to wait for their respective cooldowns before you can do them again),
    # set the training ability cooldown to a lowish value so that the script is regularly performing
    # maneuvers for your equipped weapons as soon as they are off cooldown.
    # This example checks every 10 seconds, and if a maneuver is ready then it's performed.
    # This increases the chances of performing a maneuver, especially when you swap to a new weapon.
    :cooldown: 10

# If "Charged Maneuver" is set in your training_abilities, this setting
# will attempt doublestrikes by temporarily wielding an "aiming trainable"
# in your offhand when your holding a "doublestrike trainable" in your main hand.
# If this is false then doublestrikes are only attempted if you are a Barbarian using whirlwind.
# I recommend enabling this, especially if you already use aiming trainables with ranged weapons,
# because it increases the training of multiple weapons at the same time.
prioritize_maneuver_doublestrike: true

# When prioritizing doublestrike maneuvers, this list indicates which
# melee, one-handed weapon skills in your mainhand signal that
# it's ok to attempt doublestrikes. If a doublestrike is attempted then
# a weapon from your aiming trainables will be equipped offhand.
#
# This setting is necessary if you use twohanded staves or polearms so
# that you can opt them out of doublestrike attempts because they will
# fail because the weapon itself requires two hands.
# If you're able to use the weapon for an aiming trainable then it's
# suitable to be a doublestrike trainable. This separate setting gives you control,
# however, to use different weapons for aiming and doublestrike purposes.
doublestrike_trainables:
  - Small Edged
  - Small Blunt
  - Large Edged
  - Large Blunt
  # - Staves
  # - Polearms

# In addition to being the skills trained while aiming ranged weapons,
# when prioritizing doublestrike maneuvers, one of the
# non-thrown, one-handed melee weapons in this list will be
# equipped temporarily in your offhand to do the strike.
aiming_trainables:
  - Small Edged
  - Small Blunt
  - Large Edged
  - Large Blunt
  - Light Thrown
  - Heavy Thrown
  # - Staves
  # - Polearms
  - Brawling
```
</details>

### CODE REVIEW

**Comment by rpherbig** [comment]
@jayRyan24 can you take a look at this?

**Comment by jayRyan24** [comment]
Looks solid to me.

**Comment by KatoakDR** [comment]
I ran into a snag with repeating crossbows and when combat-trainer would try to perform `maneuver powershot`. Rather than kludge a fix, I'm going to submit a second PR to improve repeating crossbow support then come back to this PR. I figure it'd be better to review/approve/merge those changes separately since they aren't really related.

**Comment by rpherbig** [comment]
Thank you for the separate PR

**Comment by KatoakDR** [comment]
This is ready for final review, thanks

**Pull request merged**
