### PR TITLE
Weaponsmithing chapter 8 additions

### PR DESCRIPTION
**Pull request by Dartellum**
**Again, vanity-pet is haunting me (the file format really needs fixed, and merging this will likely do that.** 

This request is to add the complete list of chapter 8 weapons and will fix the duplicates that came back into the file. I am not really sure how chapter 7 duplicates revived themselves from the update that corrected them. All the deletions for chapter 7 recipes are duplicates. Please check the file to confirm chapter 7 recipes exist still.

### CODE REVIEW

**Comment by rpherbig** [comment]
I'm not sure how to review this. @jayRyan24 @jandersson @KatoakDR ?

**Comment by KatoakDR** [comment]
> I'm not sure how to review this. @jayRyan24 @jandersson @KatoakDR ?

I'm unfamiliar with the recipes/crafting scripts, sorry I can't help there.

Regarding vanity-pet -- I think @Dartellum says https://github.com/rpherbig/dr-scripts/pull/4706 resolved some issues? Or maybe the issues resolved themselves after he re-cloned the repo after having to rebuild his hard drive? If the file isn't a problem for him creating PRs any more then maybe this one needs to be re-created and 4706 closed?

**Comment by Dartellum** [comment]
> > I'm not sure how to review this. @jayRyan24 @jandersson @KatoakDR ?
> 
> I'm unfamiliar with the recipes/crafting scripts, sorry I can't help there.
> 
> Regarding vanity-pet -- I think @Dartellum says #4706 resolved some issues? Or maybe the issues resolved themselves after he re-cloned the repo after having to rebuild his hard drive? If the file isn't a problem for him creating PRs any more then maybe this one needs to be re-created and 4706 closed?

My other PR did not have vanity-pet haunt it. Let me recreate this one later today (1:30 AM here) and see. I have more recipes to add from other chapters, including a request in the issues.

**Comment by Dartellum** [comment]
Closing this one due to `vanity-pet.lic` :ghost: me. :smile:

**Pull request closed without merging**
