### PR TITLE
mech-lore.lic: Remove timer usage, this is a short lived script.

### PR DESCRIPTION
**Pull request by Sarvatt**
This script would never run 300 seconds anyway, just try to dump junk if the setting exists and there is enough trash on the ground.

### CODE REVIEW

**Comment by rpherbig** [comment]
@rcuhljr @jandersson any thoughts on this one?

**Comment by Sarvatt** [comment]
@junk_timer was never initialized in this and it isn't working right now, adding a @junk_timer = Time.now to the initialization just seemed silly because this doesn't run for the 300 second dump junk timer on any character I've seen.

**Comment by Sarvatt** [comment]
ripping out the dump junk support from mech-lore would be an option too. crossing-training calls mech-lore and does a dump_junk itself right after

https://github.com/rpherbig/dr-scripts/blob/master/crossing-training.lic#L642

**Comment by rpherbig** [comment]
Removing it seems reasonable to me

**Comment by Sarvatt** [comment]
There we go

**Pull request merged**
