### PR TITLE
[script][equipmanager.lic] - Fix wield weapon match failure with hand injury

### PR DESCRIPTION
**Pull request by asechrest**
Reported via #5637 

This fixes the match hang. I do wonder, though, whether the `wield` verbs balks if you have a bad hand injury, but the `get` verb would still work to get a weapon in your hand?

### CODE REVIEW

**Comment by MahtraDR** [comment]
I'm not sure just fixing the match so there is t a hang is appropriate here. This needs more thinking to address the "ok too damaged to hold weapons, what do I do now?" Question. Do they even stay in combat then? Necro make things complicated, they can't just go get healed by an empath.

**Comment by KatoakDR** [comment]
This script is about handling your gear regardless the context, so I lean towards improving match strings to avoid hang ups.

A script like hunting-buddy or combat-trainer whose context is combat and goal is to keep the character alive should be monitoring the character's health and escaping as appropriate.

For example, if combat-trainer tries to wield a weapon but equipment-manager returns false, then that's a signal that either (a) they aren't able to hold it, or (b) their gear config is wrong. Whether the combat script stays in combat or not I think is the responsibility of the calling script, not equipment-manager.

My two kronars :)

**Review by MahtraDR — APPROVED** [review]

**Comment by asechrest** [comment]
> For example, if combat-trainer tries to wield a weapon but equipment-manager returns false, then that's a signal that either (a) they aren't able to hold it, or (b) their gear config is wrong. Whether the combat script stays in combat or not I think is the responsibility of the calling script, not equipment-manager.
> 
> My two kronars :)

The only additional thing I'm thinking about here is this. Is it a product of DR's silly parser that you can't `wield` a weapon when you have an injured hand but you can `get` a weapon instead, and still function properly for combat training?

Because if that's the case, we probably need to handle it in equipment manager and not in the calling script, since under our current predicate function paradigm, the calling script only knows whether we did or did not successfully wield the weapon, and has no understanding of the granularity of failing to wield; e.g. whether the weapon doesn't exist or we're too injured to wield.

**Review by rpherbig — APPROVED** [review]
I think fixing the hang is the first step and the PR is fine as is.

If a volunteer wants to look into the other ideas, all the better, but that shouldn't hold up this fix.

**Pull request merged**
