### PR TITLE
[script] [workorders] Change 'search' to 'exists' to minimize roundtime

### PR DESCRIPTION
**Pull request by Raykyn55**
Minor edit that changes from search to exists, removing the 5 second search roundtime and replacing it with a quick tap.

### CODE REVIEW

**Review by rpherbig — CHANGES_REQUESTED** [review]
I agree that `exists?` is the better choice here, _except_ apparently we tried that a while back and it didn't work with all containers. We actually changed it to `exists?` in #2842 and reverted back to `search?` in #2920.

If you can test those containers and tell us that they work with `exists?` now, you have my support for this change.

**Comment by Raykyn55** [comment]
Do we have a list of these bags? Is it long? I saw where you reverted, but seems odd to have such a long rt for everyone if these bags are rare. At the very least an opt-in for search could sort that. Even better, how about since it just grabs it anyways, lets skip the exists/search entirely and just check against get.

**Comment by Raykyn55** [comment]
Or even just do the count, skip the first two steps.

**Comment by rpherbig** [comment]
> Or even just do the count, skip the first two steps.

Less steps is better IMO. Can you test that it works?

**Comment by Raykyn55** [comment]
> 

I'lll make the change and give it a try, but if tap doesn't work with these bags, will count? I don't have one to check.

**Comment by rpherbig** [comment]
@Dartellum can you chime in? I don't know the specifics of the original issue

**Comment by Dartellum** [comment]
Still has this challenge for several containers. Sarvatt called them special but they were just wyvern-sized backpacks from SimuCon. Some items will not tap in them. 

If you cannot tap the item, the script will purchase another. I found out `exists?` did not work because the characters were purchasing polish every run through. I would rather have the 18 second RT (I do not recall it that high and I carry almost 500 items all the time) than to warp to the `Junkyard` because I purchased the 19th tin of polish.

**Comment by Raykyn55** [comment]
How about this latest version? skips the tap/search, just goes for the get. If it gets, counts. if it fails, discards and purchases, then stows.

Hope you can get things from them!

**Comment by Raykyn55** [comment]
[log stain-glue.txt](https://github.com/rpherbig/dr-scripts/files/8598078/log.stain-glue.txt)

**Comment by Dartellum** [comment]
> 

I did not see the polish logic in there but that should work. I would need to test. My wife and I have not logged in for a few months...

**Comment by Raykyn55** [comment]
I didn't change for polish yet, just doing small changes til we find one that works. I did change clamps, though.

**Comment by Raykyn55** [comment]
This one needs to be merged before #5784 can go through.

**Comment by MahtraDR** [comment]
@rpherbig Any concerns with merging this one in?

**Comment by Dartellum** [comment]
> 

How many people have tested? I am away this weekend and cannot do testing.

**Comment by Raykyn55** [comment]
Ive had this version running on 3 of my guys, miltiple crafts, since submitted.

**Comment by Dartellum** [comment]
> Ive had this version running on 3 of my guys, miltiple crafts, since submitted.

Do you do bone carving? I ask because the logic for it moved and want to make sure it still works.

**Review by rpherbig — APPROVED** [review]
It seems fine in principle, but I'd prefer this not to be merged until the conversation with @Dartellum is resolved.

**Comment by Raykyn55** [comment]
> > Ive had this version running on 3 of my guys, miltiple crafts, since submitted.
> 
> Do you do bone carving? I ask because the logic for it moved and want to make sure it still works.

I have, yes, but im not sure what move youre referencing. I can run it when i get back later.

**Comment by Raykyn55** [comment]
[bone-carving log.txt](https://github.com/rpherbig/dr-scripts/files/8934502/bone-carving.log.txt)

**Comment by Raykyn55** [comment]
There was a prefix missing, reason for the update. Also found that it's sourcing short cords from forging society.

**Comment by Raykyn55** [comment]
Added part rooms for Crossing and Riverhaven.

**Comment by MahtraDR** [comment]
@Dartellum The log for carving work orders looks good. Any concerns?

**Comment by asechrest** [comment]
> @Dartellum The log for carving work orders looks good. Any concerns?

Monitoring for @Dartellum 's comments on log. Looks good to merge if that's square.

**Comment by MahtraDR** [comment]
@rpherbig Happy to have this merged now?

**Comment by Dartellum** [comment]
> > @Dartellum The log for carving work orders looks good. Any concerns?
> 
> Monitoring for @Dartellum 's comments on log. Looks good to merge if that's square.

The log looks good.

**Review by Dartellum — APPROVED** [review]

**Review by Dartellum — APPROVED** [review]

**Pull request merged**
