### PR TITLE
combat-trainer.lic: add combat almanac support

### PR DESCRIPTION
**Pull request by Sarvatt**

### CODE REVIEW

**Comment by rpherbig** [comment]
❓ What does the almanac do?

I'm thinking if this affects a skill, it might be better as a training ability.

**Comment by Sarvatt** [comment]
the almanac gives you +17/34 mindstates in a random skill every 10 minutes, I would rather it be a training_ability but you cant map it to a specific skill. I was considering mapping it to enchanting that cant be trained so it always triggers on your timer though but thought that was too hacky :)

**Comment by rpherbig** [comment]
We have some examples of training abilities _not_ tied to a skill. Check out 'Favor Orb': https://github.com/rpherbig/dr-scripts/blob/master/combat-trainer.lic#L1880

**Comment by Sarvatt** [comment]
Ohh thanks for that, I had to do a lot of crap to shove it in where I did because I thought training_abilities wouldn't work, I'll update this tomorrow.

**Comment by Sarvatt** [comment]
closing this to push a new branch

**Pull request closed without merging**
