### PR TITLE
[data] [base-items] Changing to matching scrolls based on regex patterns instead of listing all nouns

### PR DESCRIPTION
**Pull request by MahtraDR**
To account for these:
```
scroll (3):                                                                                                                                                                                                                                   
    glittery-pink scroll labeled with Shadows                                                                                                                                                                                                 
    platinum-hued scroll labeled with Aura of Tongues (2)  
```

### CODE REVIEW

**Comment by BinuDR** [comment]
Is this for sorter.lic?

There are a lot of varying paper types from the various scroll stackers, plus a shop that sold paper you could use to replace the type in your stackers.

**Review by BinuDR — APPROVED** [review]

**Comment by BinuDR** [comment]
These two shops sold stackers and The Book Wyrm also sold custom paper.
<https://elanthipedia.play.net/The_Book_Wyrm>
<https://elanthipedia.play.net/Touch_of_Love>

**Comment by MahtraDR** [comment]
> Is this for sorter.lic?
> 
> 
> 
> There are a lot of varying paper types from the various scroll stackers, plus a shop that sold paper you could use to replace the type in your stackers.

It's for sorter.lic and stack-scrolls.lic. The scrolls aren't found to be stacked if we don't have the nouns in there.

**Comment by BinuDR** [comment]
For sort-scrolls, I added a yaml setting for custom paper types. 

```scroll_sorter:
  stacker: scroll folio
  stacker_container: haversack
  scroll_nouns: ['cerulean scroll', 'glittery-pink scroll', 'silver-stippled scroll', 'gold-stippled scroll']
  close_container: false
````

**Comment by KatoakDR** [comment]
I'm unfamiliar with this script, but can the yaml list `scroll_nouns:` be replaced with regex entries similar to what was done in https://github.com/rpherbig/dr-scripts/pull/5732

```yaml
scroll_nouns:
  - \b([\w\'\"\-]+) (scroll|vellum|bark|tablet|parchment|roll|papyrus)\b
  - seishaka leaf
  - ostracon
```

**Comment by MahtraDR** [comment]
> For sort-scrolls, I added a yaml setting for custom paper types.
> 
> ```
> scroll_sorter:
>   stacker: scroll folio
>   stacker_container: haversack
>   scroll_nouns: ['cerulean scroll', 'glittery-pink scroll', 'silver-stippled scroll', 'gold-stippled scroll']
>   close_container: false
> ```

That's really cool. Thanks!

**Comment by MahtraDR** [comment]
> For sort-scrolls, I added a yaml setting for custom paper types.
> 
> ```
> scroll_sorter:
>   stacker: scroll folio
>   stacker_container: haversack
>   scroll_nouns: ['cerulean scroll', 'glittery-pink scroll', 'silver-stippled scroll', 'gold-stippled scroll']
>   close_container: false
> ```

That's really cool. Thanks!

> I'm unfamiliar with this script, but can the yaml list `scroll_nouns:` be replaced with regex entries similar to what was done in #5732
> 
> https://regex101.com/r/11c1yY/1
> 
> ```yaml
> scroll_nouns:
>   - /\b([\w\'\"\-]+) (scroll|vellum|bark|tablet|parchment|roll|papyrus)\b/
>   - seishaka leaf
>   - ostracon
> ```

I don't know why this is so weird, but with the `/` tags around it, it just didn't work. This one works without. Go figure.

**Review by rpherbig — APPROVED** [review]

**Pull request merged**
