### PR TITLE
[base.yaml] Update lumber, ore and rocks

### PR DESCRIPTION
**Pull request by Ry7n**
Adds all rare and the useful common ore types to base.yaml in order to ensure auto-harvesting does
not drop something potentially valuable. Some of these may not drop from from harvesting,
but better safe than sorry.

### CODE REVIEW

**Comment by Sarvatt** [comment]
most of these weren't there because they aren't worth the time to harvest, maybe comment out the common ones?

**Comment by Ry7n** [comment]
I didn't realize oravir is available in the forging society. I'll comment out that one. The rest of the commons (lead, silver, bamboo) are all best-in-class for crafting and not available in the societies. If I missed one of those, let me know.

**Comment by jandersson** [comment]
It makes sense to me. RE: harvesting unwanted materials: I can see some of these not being reasonable defaults (lead and covellite jumped out), but It would encourage people to configure the script on the other hand.

**Comment by Ry7n** [comment]
> lead and covellite

FWIW, my thinking here is that lead is required for pewter, which pays more than double for work orders for both Alchemy and Forging, as well as being the best non-rare weighting metal. Covellite is third best (behind two rare metals) for crafting tongs.

**Pull request merged**
