### PR TITLE
[scripts][safe-room] Add support for new empath spell healing plant

### PR DESCRIPTION
**Pull request by MahtraDR**
Adding support for the new empath spell `Embrace of the Vela'Tohr` creates a plant that one can touch to get healed (the plant is like a wound bank) the empath can then come around later and heal the plant.

This PR adds the plant as a healing option to safe-room. By default, I've made the plant take priority over NPC empaths, and player empaths take priority over the plant. 

I haven't decided if I want it opt-in, or opt-out, or not optional?

### CODE REVIEW

**Comment by gmfaux** [comment]
If the plant is almost at capacity, and you are very wounded and touch it, I believe there is a chance that in taking your wounds it will reach its capacity and 'shut down', but you will still have wounds left over. In that case, you would have to either touch again if a plant/thicket is present, or proceed to other sources of healing?

**Comment by MahtraDR** [comment]
> If the plant is almost at capacity, and you are very wounded and touch it, I believe there is a chance that in taking your wounds it will reach its capacity and 'shut down', but you will still have wounds left over. In that case, you would have to either touch again if a plant/thicket is present, or proceed to other sources of healing?

As is, this change doesn't assume the plant is be all end all, it just tries to touch, in addition to whatever other source of healing it would normally do. In the scenario you describe, it would then proceed to wait for the autopath/empath to finish healing then.

**Comment by gmfaux** [comment]
@MahtraDR what if the room only has a plant and it dies?

**Comment by MahtraDR** [comment]
> @MahtraDR what if the room only has a plant and it dies?

In that scenario you won't get healed, and the logic flow continues as if there'd never been a plant, or empath in there.

**Comment by gmfaux** [comment]
Thanks for adding this!

**Pull request merged**
