### PR TITLE
spellmonitor.lic: handle trabe chalice

### PR DESCRIPTION
**Pull request by Sarvatt**
Closes: #3314

### CODE REVIEW

**Comment by Sarvatt** [comment]
https://rubular.com/r/avecAQ4eszsbuE

**Comment by Sarvatt** [comment]
Changed the regex to ignore anything before the comma since it has various states of breakage

https://rubular.com/r/THS3t5Yb97MuKm

**Comment by Tarhish** [comment]
I insist that Rubular leaves my mother out of this, but I'll check to see if I notice any odd behavior when I get home :-D

**Comment by Sarvatt** [comment]
ahh this is only handling the case where trabe chalice is the first spell in active spells, will fix

**Pull request closed without merging**
