### PR TITLE
Add a go2 fork which adds dragging support for dragonrealms.

### PR DESCRIPTION
**Pull request by Sarvatt**
I have been trying to get this commited to the real go2 for 7 months now and it hasn't been updated, might as well fork it.

### CODE REVIEW

**Comment by Sarvatt** [comment]
```--- go2.lic	2017-10-09 02:59:36.612427700 -0400
+++ go2.lic	2017-11-29 19:52:15.840723000 -0500
@@ -1094,8 +1094,10 @@
 					way = room.wayto[next_id]
 					if way =~ /^(north|northeast|east|southeast|south|southwest|west|northwest|n|ne|e|se|s|sw|w|nw|up|down|out)$/i
 						way = "drag #{setting_drag} #{way}"
+						result = move way
 					elsif way =~ /^go /i
 						way = way.sub(/^(?:go|climb) /i, "drag #{setting_drag} ")
+						result = move way
 					else
 						echo "error: drag feature doesn't know how to deal with this movement: #{way}"
 						exit
``` is the actual diff. We're thinking about adding a set !disc while moving addition in the future too.

**Comment by rpherbig** [comment]
❓ What do you mean by `!disc`?

**Comment by rpherbig** [comment]
@rcuhljr any thoughts on replacing `go2`?

**Comment by jandersson** [comment]
Im a big fan of forking go2 if thats possible. Feel like there are a lot of DR specific movement things (like this dragging update!) that could be contributed.

**Comment by jandersson** [comment]
Will ;repository pose an issue? IIRC it may auto-update official lich scripts

**Comment by Sarvatt** [comment]
as long as its a higher version it wont.

**Comment by jandersson** [comment]
It didn't explode when i manually merged it into my master branch

**Comment by jandersson** [comment]
Rubocop appears to work on this as well, the script still runs after correcting tons of things
`1 file inspected, 1928 offenses detected, 1837 offenses corrected`

**Pull request merged**
