### PR TITLE
[script] [skill-recorder] support `exp mods`

### PR DESCRIPTION
**Pull request by KatoakDR**
### Dependencies
* https://github.com/rpherbig/dr-scripts/pull/5490
* https://github.com/rpherbig/dr-scripts/pull/5548

### Background
* I would like `skill-recorder` to be able to leverage my actual `exp mods` amounts for Athletics checks
* I want to take advantage of my full skill buffs that are above the default 10% that `skill-recorder` awards

### Changes
* When checking ranks, use `DRSkill.getmodrank(skill)` to take advantage of true modified ranks not assumed ranks
* Use `DRSpells.known_spells['Resurrection']` to check if Cleric knows the ressurection spell instead of parsing output from `spells` in here; `spellmonitor` handles it
* Add new setting `skill_recorder_passive_delay` that is the number of seconds to wait between checks. Previously 30 seconds was hardcoded.
* In review with @Hiinky, moving the `exp mods` check to this script instead of `drinfomon` doing the polling to reduce calling this command for characters that don't want or need it.
  - Add new setting `skill_recorder_check_exp_mods` (boolean) for users to opt-in to more precise effective rank readings via `exp mods`. Default is `false` (original behavior).

### Config
_base.yaml_
```yaml
# The number of seconds the `skill-recorder` script waits
# between checking your guild, skills, and spells to know
# things like if your Thief is qualified to use passages
# or if you have enough effective ranks in Athletics for traveling.
skill_recorder_passive_delay: 30

# By default, `skill-recorder` script tracks your effective ranks
# for some skills, such as Athletics, based on a flat 10% increase
# if certain buffs are active. However, you actually may have more (or less)
# depending on how powerful your buff (or curse) is at the time.
# To take advantage of more precise effective ranks, set this to true.
# It will parse `exp mods` command to get your true effective ranks.
skill_recorder_check_exp_mods: false
```

### Tests
_unbuffed athletics_
```
> ,e echo UserVars.athletics ; ,e echo DRSkill.getmodrank('Athletics')

--- Lich: exec1 active.

[exec1: 493]

[exec1: 493]

--- Lich: exec1 has exited.
```
_buff athletics_
```
> khri flight

Knowing that a dose of paranoia is healthy for any aspiring Thief, your mind fixates on every possible avenue of escape available to you.
Roundtime: 3 sec.

(wait passive delay)

> ,e echo UserVars.athletics ; ,e echo DRSkill.getmodrank('Athletics')

--- Lich: exec1 active.

[exec1: 571]

[exec1: 571]

--- Lich: exec1 has exited.

> exp mods
The following skills are currently under the influence of a modifier:

+78(16%) Athletics (571 effective ranks)
+84(20%) Perception (506 effective ranks)
```
_remove buff_
```
> khri stop flight

You attempt to relax your mind from some of its meditative states.
You feel mentally fatigued as your heightened paranoia ceases to enhance your knowledge of nearby escape routes. 

(wait passive delay)

> ,e echo UserVars.athletics ; ,e echo DRSkill.getmodrank('Athletics')

--- Lich: exec1 active.

[exec1: 493]

[exec1: 493]

--- Lich: exec1 has exited.

> exp mods
The following skills are currently under the influence of a modifier:

+84(20%) Perception (506 effective ranks)
```

### CODE REVIEW

**Comment by rpherbig** [comment]
Looks good ✔️

**Comment by KatoakDR** [comment]
Putting back in draft while recruit testers

**Comment by KatoakDR** [comment]
[Recruited](https://discord.com/channels/745675889622384681/745675890242879671/943404060449574942) testers in Discord, but heard no follow ups in 24 hours; this is ready to merge

**Comment by MahtraDR** [comment]
ranger
```
 >exp ath                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                              
           SKILL: Rank/Percent towards next rank/Amount learning/Mindstate fraction                                                                                                                                                           
        Athletics:    628 21.44% clear          (0/34)                                                                                                                                                                                        
                                                                                                                                                                                                                                              
 Time Development Points: 669  Favors: 45  Deaths: 28  Departs: 2                                                                                                                                                                             
 Rested EXP Stored: 5:59 hours  Usable This Cycle: 5:36 hours  Cycle Refreshes: 19:32 hours                                                                                                                                                   
 Overall state of mind: clear                                                                                                                                                                                                                 
 EXP HELP for more information                                                                                                                                                                                                                
 >exp mods                                                                                                                                                                                                                                    
 The following skills are currently under the influence of a modifier:                                                                                                                                                                        
 +125 Athletics                                                                                                                                                                                                                               
 Alshabi Kamisama goes east.                                                                                                                                                                                                                  
 >;e echo UserVars.athletics                                                                                                                                                                                                                  
 --- Lich: exec1 active.                                                                                                                                                                                                                      
 [exec1: 628]                                                                                                                                                                                                                                 
 --- Lich: exec1 has exited.                                                                                                                                                                                                                  
 >;e echo DRSkill.getmodrank('Athletics')                                                                                                                                                                                                     
 --- Lich: exec1 active.                                                                                                                                                                                                                      
 [exec1: 753]                                                                                                                                                                                                                                 
 --- Lich: exec1 has exited.               
```

cleric
```
 >;e echo UserVars.know_rezz                                                                                                                                                                                                                  
 --- Lich: exec1 active.                                                                                                                                                                                                                      
 [exec1: true]                                                                                                                                                                                                                                
 --- Lich: exec1 has exited.            
```

Looks good to me.

**Pull request merged**
