### PR TITLE
additional bput slip stalk confirmation messages

### PR DESCRIPTION
**Pull request by intangibles**
new confirmation message on bput slip stalk

### CODE REVIEW

**Comment by rcuhljr** [comment]
So it was possible to slip without RT?

**Comment by intangibles** [comment]
Yeah, unfortunately. I never caught this until things were too hard.  Maybe I should return hide? again on failure? Since there is no RT.

[combat-trainer]>stalk

You quickly slip into hiding to prepare to stalk.
The sky giant notices your attempt to hide!
The sky giant discovers you, ruining your hiding place!
Stalking is an inherently stealthy endeavor, try being out of sight.

**Comment by intangibles** [comment]
Let's hold off on this PR for now then, I'll do some testing to see how returning on failure with no RT works.

**Comment by intangibles** [comment]
Although it's possible you could get into a crazy stalk loop.  Maybe not such a good idea.

**Pull request closed without merging**
