### PR TITLE
salomhe-setup.yaml

### PR DESCRIPTION
**Pull request by slecker**
https://github.com/rpherbig/dr-scripts/commit/848a2f2137ca045b7ec35f73b3335fcd726f1312

### CODE REVIEW

**Comment by rpherbig** [comment]
It looks like there are some conflicts preventing me from merging this.

**Comment by slecker** [comment]
I edited Saelihn-setup, was that the only one with conflicts? Thanks!

**Comment by rpherbig** [comment]
Yes, but GitHub still reports conflicts.

**Comment by slecker** [comment]
Huzzah!

**Pull request closed without merging**
