### PR TITLE
[script] [buff-watcher] New script to keep buffs active

### PR DESCRIPTION
**Pull request by KatoakDR**
### Background
* Sometimes you want to keep your buffs up all the time, even when you're out of combat, and even when not running T2 or training-manager
* And if not for the buff's benefits then for the magical skill training it can provide as you're milling around town
* Similar in principle to `wand-watcher` that keeps buffs active via wands

### Credits
* Inspired by requests and code from B-Money42, Blackheart, and VTCifer

### Changes
* New script `buff-watcher` modeled after `wand-watcher` and `buff`
* Adds new configuration settings that mirror those used with `wand-watcher`
* Designed to be run in the background, and suitable as an autostart

### Usage
* `;buff-watcher [buff-set-name]`
  - If no buff set name is specified at script start then will use `buff_watcher_name:` else the 'default' buff set
* `;e autostart('buff-watcher', false)`
  - Also suitable as an autostart

### Notes
* This script _can_ be used by Barbarians, but it would be a waste of your inner fire out of combat
* This script _can_ be used by Necromancers, just beware of justice zones and which buffs you put up

### Configuration
Shamelessly copied from wand-watcher's config.

<details>
<summary>click to toggle</summary>

```yaml
# Name of the buff list defined in waggle_sets: whose abilities to monitor and keep active on you.
buff_watcher_name: default

# Don't try to rebuff while these scripts are running.
buff_watcher_no_use_scripts:
- buff
- athletics
- burgle
- steal
- pick
- locksmithing
- go2
- get2
- bescort
- stabbity
- hunting-buddy
- combat-trainer
- healme
- feed-cloak

# Don't try to rebuff while in these rooms (genearlly anti-magic rooms), can use roomnumber, title or regex that matches the title.
buff_watcher_no_use_rooms:
  - 1900                                          # Crossing bank teller - included with regex below but shown for example
  - Knife Clan, Triage                            # Dokt - silenced room
  - !ruby/regexp '/^(?:First )?Provincial Bank,/' # Crossing Bank - mapped, but 1 regex- -> 3 rooms
  - !ruby/regexp '/Carousel (?:Booth|Chamber)$/'  # Vaults - unmapped silenced / nomagic

# Wait n seconds on startup before doing anything [Optional - defaults to 10 s]
buff_watcher_startup_delay: 10

# How long to wait between checks to recasting    [Optional - defaults to 60 s]
buff_watcher_passive_delay: 60
```
</details>

## Tests
<details>
<summary>click to toggle</summary>

### as thief with hands full, does not need to empty hands to activate khri
```
>glance

You glance down to see a vault book in your right hand and a coil of heavy rope in your left hand.

> ,buff-watcher

--- Lich: buff-watcher active.

--- Lich: faux-atmo paused.

--- Lich: tarantula paused.

--- Lich: almanac paused.

--- Lich: sanowret-crystal paused.

[buff-watcher]>Khri Dampen

Focusing your mind, you attempt to attune your senses to even your most minor movements.  You quickly feel more comfortable with your ability to control your motions to prevent detection.
Roundtime: 3 sec.
>
--- Lich: faux-atmo unpaused.

--- Lich: tarantula unpaused.

--- Lich: almanac unpaused.

--- Lich: sanowret-crystal unpaused.
```

### as barbarian with hands full, does not need to empty hands to activate ability
```
>glance

You glance down to see a vault book in your right hand and a coil of heavy rope in your left hand.

> ,buff-watcher combat

--- Lich: buff-watcher active.

--- Lich: faux-atmo paused.

--- Lich: almanac paused.

--- Lich: sanowret-crystal paused.

[buff-watcher]>med tenacity

You must be sitting to properly reinforce your physical resistance.
>
[buff-watcher]>sit

You sit down.

s>
[buff-watcher]>med tenacity

You begin to meditate upon the chakrel amulet, your inner fire swelling as you center your mind, body, and spirit.
Roundtime: 7 sec.
s>
Peering into the flame you visualize swords, teeth and worse all rending your flesh.
s>
You draw the flames close and bring forth a physical hardening to your body.
s>
The flame infuses your flesh, reinforcing it against physical damage!
You feel a jolt as your vision snaps shut.
s>
[buff-watcher]>stand

You stand back up.

>
--- Lich: faux-atmo unpaused.

--- Lich: almanac unpaused.

--- Lich: sanowret-crystal unpaused.
```

### as magic user with hands full and worn/no cambrinth, does not need to empty hands to cast spell
```
>glance

You glance down to see a vault book in your right hand and a coil of heavy rope in your left hand.

,buff-watcher
--- Lich: buff-watcher active.

>
[buff-watcher]>release mana

You aren't harnessing any mana.
>
[buff-watcher]>prep MAF 6

With meditative movements you prepare your body for the Manifest Force spell.
>
[buff-watcher]>charge my cambrinth armband 11

You harness a small amount of energy and attempt to channel it into your cambrinth armband.
You are able to channel all the energy into the armband.
The cambrinth armband absorbs all of the energy.
Roundtime: 3 sec.

...
```

### as magic user with hands full and stored cambrinth, empties left hand for cambrinth use then picks it back up
```
> ,buff-watcher

--- Lich: buff-watcher active.

> release ic

Your skin loses its protective numbness.

--- Lich: almanac paused.

--- Lich: tendme paused.

[buff-watcher]>glance

You glance down to see a vault book in your right hand and a coil of heavy rope in your left hand.
>
[buff-watcher]>lower ground left

You lower the rope and place it on the ground at your feet.
>
[buff-watcher]>release mana

You aren't harnessing any mana.
>
[buff-watcher]>prep IC 5

With meditative movements you prepare your body for the Iron Constitution spell.
>
[buff-watcher]>remove my cambrinth armband

You remove a braided cambrinth armband from your upper arm.
>

[buff-watcher]>charge my cambrinth armband 7

You harness a small amount of energy and attempt to channel it into your cambrinth armband.
You are able to channel all the energy into the armband.
The cambrinth armband absorbs all of the energy.
Roundtime: 3 sec.
>
[buff-watcher]>invoke my cambrinth armband

The cambrinth armband pulses with Life energy.  You reach for its center and forge a magical link to it, readying all of its mana for your use.
Roundtime: 1 sec.
>
[buff-watcher]>wear my cambrinth armband

You attach a braided cambrinth armband to your upper arm.
>

[buff-watcher]>cast

You gesture.
Your cambrinth armband emits a loud *snap* as it discharges all its power to aid your spell.
The pattern secretes a liquid, dusky light which cascades down your body like thick honey, numbing your skin as it covers you from head to toe before thinning out.

>
[buff-watcher]>get my heavy rope

You pick up the rope lying at your feet.
>
--- Lich: almanac unpaused.

--- Lich: tendme unpaused.

```
</details>

### CODE REVIEW

**Comment by rpherbig** [comment]
Code looks good ✔️ 

I suggest getting away from the 'waggle' naming as much as possible, it just seems to cause confusion. Thoughts?

**Comment by KatoakDR** [comment]
> Code looks good ✔️

Thanks ☺️

> I suggest getting away from the 'waggle' naming as much as possible, it just seems to cause confusion. Thoughts?

To clarify, are you referring to rename the class from WaggleWatcher to BuffWatcher (to match the file name) and/or something else?

**Comment by rpherbig** [comment]
Class name, settings, args, etc. Thoughts?

**Comment by KatoakDR** [comment]
> Class name, settings, args, etc. Thoughts?

Sure, what term do you suggest to replace “waggle”? The YAML setting where you define them is called “waggle_sets”, too.

**Comment by rpherbig** [comment]
`Buff`? Waggle is an artifact of the old days, I'd much rather use terms that are more intuitive

**Comment by KatoakDR** [comment]
> `Buff`? Waggle is an artifact of the old days, I'd much rather use terms that are more intuitive

I've replaced uses of 'waggle' with 'buff', thanks

**Pull request merged**
