### PR TITLE
[data] [base-help] Create base-help.yaml

### PR DESCRIPTION
**Pull request by asechrest**
Second component part of robust help output for scripts. Again, thanks to @rcuhljr for help fleshing out this idea.

This new file works in concert with:

- #5712 

This file serves as a help file of yaml settings. The purpose of this file is to provide the base of information that a call to `;<script-name> help` will pull yaml settings help output from. The aforementioned change to `dependency`, separately, provides the structure that parses and outputs the data when a user calls the help argument.

**Background:**
Why do this? DR Lich's total number of yaml settings has grown significantly. One of the most common questions we have from users is: what yaml settings are used in this script? We of course have a substantially long file called `base.yaml` that contains most of our yaml settings, with some, but not all. of them code-commented. But many users don't know where to access that file, and it's long enough that it's difficult to reference. Further, Ruby doesn't parse code comments, so there is no way to draw on those comments to output help information.

**The advantages:**
Creating this help file of yaml settings, along with the changes to dependency that are backward-compatible, allow us to build this file over time into a complete yaml settings help document that can be drawn upon in-game to output help information. Further, this requires no changes in the scripts themselves. Rather, we're building the information in a separate file, manually. While that has downsides, the upsides is that we don't need to change every script, and, this project can be abandoned without any detriment to the project, if in the future the devs decide to do so.

**Examples of what this will look like:**

Within base-help.yaml we'll build our yaml settings like this, giving a general description, a list of all scripts that reference this yaml setting, and a specific description of how the yaml setting works with each script:

```yaml
# crafting_container: # This is the actual name of the setting as specified in base/character yamls
#   description: # This is the general description of the setting itself
#   referenced_by: # Here you should specify which scripts, by their script name, use this setting
#     - clean-leather
#     - carve-bead
#   specific_descriptions: # Here you should specify, by script name, the specific use of the setting
#     clean-leather: Scraper, preservatives and cleaned hides go here.
#     carve-bead: Carving knife and shaper go here.

hometown:
  description: Town you wish to live and work in.
  referenced_by:
    - clean-leather
  specific_descriptions:
    clean-leather: Used to look up Stock vendor to buy from and banking settings.
```

Doing so will allow us to have robust yaml settings output like this:

image

### CODE REVIEW

**Comment by rpherbig** [comment]
How will the script help text be stored? ("This script automates cleaning animal hides and...")

**Comment by asechrest** [comment]
> How will the script help text be stored? ("This script automates cleaning animal hides and...")

Good question. I believe you're asking about the _SCRIPT SUMMARY:_ output showing in that screenshot. Currently, since I'm designing help output to flow through ArgParser, my idea is just to have an optional arg that's a brief script summary. Like this:

```
def main
  arg_definitions = [
    [
      { name: 'debug', regex: /debug/i, optional: true, description: 'Runs the script with debug messages.' },
      { name: 'mode', options: %w[brief short next], optional: true, description: 'Only display requirements you don\'t meet' },
      { name: 'target', regex: /^\d+$/, optional: true, description: 'See requirements for a specific circle' },
      { name: 'script_summary', optional: true, description: 'Checks your circle and skills to next circle. Optionally checks skills for a target circle.'}
    ]
  ]
```

I do recognize that this is a _touch_ out of the ordinary since that script summary line may not meet the definition of a script argument, but it's something I can wrap into ArgParser and also something easy to be added (or not!) without any detriment to current function that I can figure.

If you're asking about the yaml settings help output text showing in the screenshot, that would be stored in what you've rightly suggested should be called `base-help.yaml` over on my other PR.

Appreciate the comments very much.

**Comment by rpherbig** [comment]
> > How will the script help text be stored? ("This script automates cleaning animal hides and...")
> 
> Good question. I believe you're asking about the _SCRIPT SUMMARY:_ output showing in that screenshot. Currently, since I'm designing help output to flow through ArgParser, my idea is just to have an optional arg that's a brief script summary. Like this:

Crazy idea: what about base-help having both settings info and script info? I.e. the settings as are currently proposed; then script summary + arg definitions. Then, since all that is in a YAML file, anything can easily read it in and have the basic info about any script as needed.

**Comment by asechrest** [comment]
> Crazy idea: what about base-help having both settings info and script info? I.e. the settings as are currently proposed; then script summary + arg definitions. Then, since all that is in a YAML file, anything can easily read it in and have the basic info about any script as needed.

Does your idea completely offload script argument definitions to the yaml? So the `base-help.yaml` would have:

1. The complete argument definitions including regex, whether optional or required, and description?
2. The script summary?
3. The help information for the yaml settings used in the script?

I would say that I'm trying my best to do this such that I keep the need for a lot of code changes to existing scripts to a minimum.

**Comment by rpherbig** [comment]
> Does your idea completely offload script argument definitions to the yaml?

It could, which could mean it's too big of a change to make at this time. I just figured I'd bring the idea up for discussion. I don't want to re-scope your PR to infinity :)

**Comment by asechrest** [comment]
> > Does your idea completely offload script argument definitions to the yaml?
> 
> It could, which could mean it's too big of a change to make at this time. I just figured I'd bring the idea up for discussion. I don't want to re-scope your PR to infinity :)

With 20-20 hindsight, I think there's an argument for a base.yaml to rule them all. It holds all base settings, all descriptions of those settings, all scripts that call that setting, and specific descriptions of how those scripts use that setting. Sort of a combination of this idea of a `base-help.yaml` and our current `base.yaml`.

_But_ I feel like that's just a bit too much turmoil for the maturity of the project, the code changes involved, and the users who are substantially averse to change. So I'm thinking this separate help file does the job and allows us to bail from the approach without any detriment.

**Comment by rpherbig** [comment]
> But I feel like that's just a bit too much turmoil for the maturity of the project, the code changes involved, and the users who are substantially averse to change. So I'm thinking this separate help file does the job and allows us to bail from the approach without any detriment.

Works for me. We can always change things later (or not!)

**Review by rpherbig — APPROVED** [review]

**Review by MahtraDR — COMMENTED** [review]
This is a test comment in a review.

**Comment by asechrest** [comment]
@rcuhljr knocked some sanity into me and suggested we ought to release this and allow the community to perhaps help build the help file out. I like that idea, because it's a huge project, and it takes some effort to get into the mood to do it.

**Pull request merged**
