### PR TITLE
[scripts][almanac] Add priority skills list for pickanacks

### PR DESCRIPTION
**Pull request by MahtraDR**
As per title. In draft so I can test the rspec testing.

### CODE REVIEW

**Comment by Raykyn55** [comment]
That rubocop is neat

**Comment by MahtraDR** [comment]
> That rubocop is neat

Very neat.

If you look at https://github.com/rpherbig/dr-scripts/pull/6402 it has the model I'll implement, which runs rubocop just on the file(s) being modified in the PR.

**Comment by MahtraDR** [comment]
> That rubocop is neat

It's setup to trigger on a commit push, if you commit any code to an open PR it'll run on your PRs too.

**Comment by Raykyn55** [comment]
> 

oh, cool, i was going to ask how i could get it to insult my coding too :)

**Comment by MahtraDR** [comment]
> > 
> 
> oh, cool, i was going to ask how i could get it to insult my coding too :)

You can run it locally too. Just install rubocop, copy our config from the repo <https://github.com/rpherbig/dr-scripts/blob/master/.rubocop.yml> and run away :) I can auto-fix many issues too.

**Pull request merged**
