### PR TITLE
[script][first-aid] - Allow training granularity for FA/Scholarship/Both

### PR DESCRIPTION
**Pull request by asechrest**
Adds args to allow you to focus on first aid, scholarship, or both. Also adds settings to base-help.yaml.

Defaults to checking `First Aid` skill if none is specified, to retain prior behavior.

### CODE REVIEW

**Comment by Dartellum** [comment]
As a side note, the `attunement` script has an arg for scholarship too:
```ruby
{
          name: 'sigil',
          regex: /sigil/,
          optional: true,
          description: 'Do sigil walking (scholarship training) instead of regular attunement walking'
        }
```

**Comment by Smaptastic** [comment]
Using `;first-aid first aid` seems to break it for me, but that's not a big deal since the default targets the First Aid skill so it's kinda a redundant argument. Works fine for me with default, scholarship, and both.

**Comment by asechrest** [comment]
> 

Thanks for testing, and I know why. Having a script argument with a space, and without enclosing quotes, will cause the script to think the second word is an additional argument. Since this script only has one argument, it fusses at you because it thinks you have two. Will work on a fix.

**Comment by Smaptastic** [comment]
The change looks good. There wasn't a need for first aid as a setting, given that it's default. Works perfectly for both and scholarship. Ship it.

**Pull request merged**
